-- Drop the owned table set together so internal foreign-key cycles need no CASCADE.
DROP TABLE IF EXISTS
    computer_checkpoint_runs,
    computer_specs,
    computer_object_pins,
    computer_instances,
    run_waits,
    computer_checkpoint_objects,
    computer_checkpoints,
    telemetry_outbox,
    run_leases,
    control_outbox,
    public_access_tokens,
    tokens,
    secret_resolutions,
    computer_disk_version_roots,
    computer_disk_versions,
    computer_object_edges,
    computer_object_keys,
    computer_objects,
    computer_data_keys,
    computer_commands,
    session_events,
    session_messages,
    session_turns,
    run_attempts,
    runs,
    sessions,
    computer_secrets,
    computers,
    schedule_secrets,
    schedules,
    idempotency_claims,
    deployment_definitions,
    deployments,
    artifacts,
    worker_host_credentials,
    worker_hosts,
    worker_pool_cpu_shapes,
    worker_pools,
    vm_platforms,
    worker_groups,
    worker_group_tokens,
    cas_objects,
    cas_upload_reclaims,
    cas_blobs,
    secret_versions,
    secrets,
    device_codes,
    api_keys,
    magic_links,
    invitations,
    auth_sessions,
    environments,
    projects,
    org_members,
    auth_identities,
    users,
    regions,
    organizations;

DROP TYPE IF EXISTS wait_kind;
DROP TYPE IF EXISTS artifact_kind;
DROP TYPE IF EXISTS magic_link_purpose;
DROP TYPE IF EXISTS org_member_role;
DROP TYPE IF EXISTS telemetry_stream_kind;
