DROP INDEX IF EXISTS public_access_token_scopes_stream_idx;
DROP INDEX IF EXISTS public_access_token_scopes_token_idx;
DROP INDEX IF EXISTS public_access_tokens_scope_expiry_idx;
DROP INDEX IF EXISTS stream_records_idempotency_idx;
DROP INDEX IF EXISTS stream_records_sequence_idx;
DROP INDEX IF EXISTS streams_session_name_idx;
DROP INDEX IF EXISTS deployment_streams_lookup_idx;
DROP INDEX IF EXISTS workspace_leases_expiry_idx;
DROP INDEX IF EXISTS workspace_leases_one_active_writer_workspace_mount_idx;
DROP INDEX IF EXISTS workspace_leases_one_active_writer_workspace_idx;
DROP INDEX IF EXISTS workspace_operation_idempotencies_environment_idx;
DROP INDEX IF EXISTS workspace_operation_idempotencies_workspace_idx;
DROP INDEX IF EXISTS workspace_process_operations_active_process_idx;
DROP INDEX IF EXISTS workspace_process_operations_worker_claim_idx;
DROP INDEX IF EXISTS workspace_process_operations_claim_idx;
DROP INDEX IF EXISTS workspace_mounts_heartbeat_idx;
DROP INDEX IF EXISTS workspace_mounts_one_active_idx;
DROP INDEX IF EXISTS workspace_versions_workspace_created_idx;
DROP INDEX IF EXISTS workspaces_external_id_idx;
DROP INDEX IF EXISTS workspaces_tags_idx;
DROP INDEX IF EXISTS workspaces_state_idx;
DROP INDEX IF EXISTS session_runs_timeline_idx;
DROP INDEX IF EXISTS session_run_requests_pending_idx;
DROP INDEX IF EXISTS session_start_idempotencies_expiry_idx;
DROP INDEX IF EXISTS sessions_tags_idx;
DROP INDEX IF EXISTS sessions_scope_status_updated_idx;
DROP INDEX IF EXISTS sessions_external_id_idx;
DROP INDEX IF EXISTS tasks_scope_updated_idx;
DROP INDEX IF EXISTS waits_expiry_idx;
DROP INDEX IF EXISTS waits_timer_due_idx;
DROP INDEX IF EXISTS waits_token_idx;
DROP INDEX IF EXISTS waits_stream_record_idx;
DROP INDEX IF EXISTS waits_stream_pending_idx;
DROP INDEX IF EXISTS waits_scope_state_idx;
DROP INDEX IF EXISTS run_waits_run_state_idx;
DROP INDEX IF EXISTS tokens_callback_fingerprint_pending_idx;
DROP INDEX IF EXISTS tokens_timeout_pending_idx;
DROP INDEX IF EXISTS tokens_idempotency_idx;
DROP INDEX IF EXISTS tokens_scope_state_idx;
DROP INDEX IF EXISTS meter_events_run_meter_idx;
DROP INDEX IF EXISTS meter_events_trace_idx;
DROP INDEX IF EXISTS meter_events_scope_meter_time_idx;
DROP INDEX IF EXISTS meter_events_idempotency_idx;
DROP INDEX IF EXISTS run_operations_idempotency_idx;
DROP INDEX IF EXISTS telemetry_outbox_written_gc_idx;
DROP INDEX IF EXISTS telemetry_outbox_ingest_claim_idx;
DROP INDEX IF EXISTS telemetry_outbox_ingest_ready_idx;
DROP INDEX IF EXISTS telemetry_outbox_publish_ready_idx;
DROP INDEX IF EXISTS telemetry_outbox_idempotency_idx;
DROP INDEX IF EXISTS telemetry_outbox_deployment_id_idx;
DROP INDEX IF EXISTS telemetry_outbox_run_id_idx;
DROP INDEX IF EXISTS deletion_jobs_org_status_requested_idx;
DROP INDEX IF EXISTS runtime_checkpoints_run_state_idx;
DROP INDEX IF EXISTS runtime_checkpoint_artifacts_role_idx;
DROP INDEX IF EXISTS run_leases_worker_instance_status_idx;
DROP INDEX IF EXISTS run_leases_active_concurrency_idx;
DROP INDEX IF EXISTS run_leases_active_lease_idx;
DROP INDEX IF EXISTS run_leases_attempt_number_idx;
DROP INDEX IF EXISTS run_leases_one_active_per_run_idx;
DROP INDEX IF EXISTS run_state_snapshots_run_created_idx;
DROP INDEX IF EXISTS telemetry_outbox_run_attempt_number_idx;
DROP INDEX IF EXISTS telemetry_outbox_run_lease_idx;
DROP INDEX IF EXISTS telemetry_outbox_run_log_observed_idx;
DROP INDEX IF EXISTS deployment_sandboxes_lookup_idx;
DROP INDEX IF EXISTS deployment_tasks_lookup_idx;
DROP INDEX IF EXISTS artifacts_digest_idx;
DROP INDEX IF EXISTS artifacts_runtime_substrate_digest_uidx;
DROP INDEX IF EXISTS artifacts_scope_kind_created_idx;
DROP INDEX IF EXISTS deployment_promotions_environment_created_idx;
DROP INDEX IF EXISTS deployment_promotions_deployment_idx;
DROP INDEX IF EXISTS environments_current_deployment_idx;
DROP INDEX IF EXISTS deployments_reusable_build_key_idx;
DROP INDEX IF EXISTS secrets_key_id_updated_idx;
DROP INDEX IF EXISTS device_codes_pending_expiry_idx;
DROP INDEX IF EXISTS api_key_grants_unique_idx;
DROP INDEX IF EXISTS worker_instance_credentials_worker_instance_one_active_idx;
DROP INDEX IF EXISTS worker_bootstrap_tokens_active_idx;
DROP INDEX IF EXISTS api_keys_scope_active_name_idx;
DROP INDEX IF EXISTS api_keys_org_active_idx;
DROP INDEX IF EXISTS magic_links_invitation_active_idx;
DROP INDEX IF EXISTS magic_links_email_purpose_recent_idx;
DROP INDEX IF EXISTS magic_links_active_token_idx;
DROP INDEX IF EXISTS invitations_email_lookup_idx;
DROP INDEX IF EXISTS invitations_pending_invitee_idx;
DROP INDEX IF EXISTS auth_sessions_expiry_active_idx;
DROP INDEX IF EXISTS auth_sessions_user_active_idx;
DROP INDEX IF EXISTS org_members_user_active_idx;
DROP INDEX IF EXISTS environments_org_project_slug_idx;
DROP INDEX IF EXISTS projects_org_slug_idx;
DROP INDEX IF EXISTS runs_scope_status_created_idx;
DROP INDEX IF EXISTS runs_scope_created_idx;
DROP INDEX IF EXISTS runs_schedule_instance_id_idx;
DROP INDEX IF EXISTS runs_schedule_id_idx;
DROP INDEX IF EXISTS runs_schedule_idx;
DROP INDEX IF EXISTS runs_queued_expiry_idx;
DROP INDEX IF EXISTS runs_queued_queue_scope_idx;
DROP INDEX IF EXISTS runs_org_status_created_idx;
DROP INDEX IF EXISTS runs_org_created_idx;
DROP INDEX IF EXISTS worker_instances_capacity_idx;
DROP INDEX IF EXISTS worker_commands_worker_replay_idx;
DROP INDEX IF EXISTS worker_commands_ready_idx;
DROP INDEX IF EXISTS worker_commands_runtime_resume_wait_once_idx;
DROP INDEX IF EXISTS worker_commands_runtime_checkpoint_wait_once_idx;
DROP INDEX IF EXISTS runtime_instances_adoption_expiry_idx;
DROP INDEX IF EXISTS runtime_instances_adopting_workspace_uidx;
DROP INDEX IF EXISTS runtime_instances_workspace_active_uidx;
DROP INDEX IF EXISTS runtime_instances_lost_sweep_idx;
DROP INDEX IF EXISTS runtime_instances_worker_active_idx;
DROP INDEX IF EXISTS runtime_instances_coverage_idx;
DROP INDEX IF EXISTS runtime_instances_ready_claim_idx;
DROP INDEX IF EXISTS worker_instances_worker_group_status_seen_idx;
DROP INDEX IF EXISTS worker_instances_status_seen_idx;
DROP INDEX IF EXISTS run_leases_worker_group_idx;
DROP INDEX IF EXISTS deployments_worker_group_status_idx;
DROP INDEX IF EXISTS runs_dispatch_repair_idx;
DROP INDEX IF EXISTS task_schedule_instances_index_due_idx;
DROP INDEX IF EXISTS task_schedule_instances_environment_idx;
DROP INDEX IF EXISTS task_schedules_scope_created_idx;
DROP INDEX IF EXISTS task_schedules_user_dedup_active_idx;
DROP INDEX IF EXISTS task_schedules_internal_dedup_active_idx;
DROP INDEX IF EXISTS stream_records_correlation_sequence_idx;
DROP INDEX IF EXISTS runtime_release_selections_singleton_idx;
DROP INDEX IF EXISTS users_primary_email_lower_idx;
DROP INDEX IF EXISTS environments_one_default_idx;
DROP INDEX IF EXISTS projects_one_default_idx;
DROP TABLE IF EXISTS worker_commands;
DROP TRIGGER IF EXISTS runtime_checkpoint_restores_set_updated_at ON runtime_checkpoint_restores;
DROP INDEX IF EXISTS runtime_checkpoint_restores_run_idx;
DROP TABLE IF EXISTS runtime_checkpoint_restores;
ALTER TABLE runtime_instances DROP CONSTRAINT IF EXISTS runtime_instances_owner_run_wait_id_fkey;
ALTER TABLE runtime_instances DROP CONSTRAINT IF EXISTS runtime_instances_org_id_owner_run_wait_id_fkey;
ALTER TABLE run_waits DROP CONSTRAINT IF EXISTS run_waits_owner_runtime_instance_id_fkey;
DROP TABLE IF EXISTS run_waits;
DROP TABLE IF EXISTS waits;
DROP TABLE IF EXISTS session_run_requests;
DROP TABLE IF EXISTS stream_records;
DROP TABLE IF EXISTS public_access_token_scopes;
DROP TABLE IF EXISTS public_access_tokens;
DROP TABLE IF EXISTS tokens;
DROP TABLE IF EXISTS streams;
DROP TABLE IF EXISTS deployment_streams;
DROP TABLE IF EXISTS meter_events;
DROP TABLE IF EXISTS runtime_checkpoint_artifacts;
ALTER TABLE run_leases DROP CONSTRAINT IF EXISTS run_leases_restore_runtime_checkpoint_id_fkey;
ALTER TABLE runs DROP CONSTRAINT IF EXISTS runs_latest_runtime_checkpoint_id_fkey;
ALTER TABLE runtime_checkpoints DROP CONSTRAINT IF EXISTS runtime_checkpoints_owner_runtime_instance_id_fkey;
DROP TABLE IF EXISTS runtime_checkpoints;
DROP TYPE IF EXISTS runtime_checkpoint_restore_status;
DROP TYPE IF EXISTS runtime_checkpoint_artifact_role;
DROP TYPE IF EXISTS runtime_checkpoint_state;
DROP TABLE IF EXISTS workspace_operation_idempotencies;
DROP TABLE IF EXISTS workspace_process_operations;
DROP TABLE IF EXISTS workspace_process_stream_receipts;
DROP TABLE IF EXISTS workspace_process_stream_chunks;
ALTER TABLE workspaces DROP CONSTRAINT IF EXISTS workspaces_current_version_id_fkey;
ALTER TABLE workspace_leases DROP CONSTRAINT IF EXISTS workspace_leases_acquired_version_id_fkey;
ALTER TABLE workspace_leases DROP CONSTRAINT IF EXISTS workspace_leases_base_version_id_fkey;
ALTER TABLE workspace_mounts DROP CONSTRAINT IF EXISTS workspace_mounts_base_version_id_fkey;
ALTER TABLE runtime_instances DROP CONSTRAINT IF EXISTS runtime_instances_owner_workspace_version_id_fkey;
DROP TABLE IF EXISTS workspace_versions;
ALTER TABLE workspace_leases DROP CONSTRAINT IF EXISTS workspace_leases_owner_process_id_fkey;
DROP TABLE IF EXISTS workspace_processes;
DROP TABLE IF EXISTS workspace_leases;
ALTER TABLE runs DROP CONSTRAINT IF EXISTS runs_workspace_mount_id_fkey;
ALTER TABLE workspace_mounts DROP CONSTRAINT IF EXISTS workspace_mounts_runtime_instance_id_fkey;
ALTER TABLE runtime_instances DROP CONSTRAINT IF EXISTS runtime_instances_owner_workspace_id_fkey;
ALTER TABLE runtime_instances DROP CONSTRAINT IF EXISTS runtime_instances_owner_run_id_fkey;
ALTER TABLE runtime_instances DROP CONSTRAINT IF EXISTS runtime_instances_owner_run_lease_id_fkey;
DROP TABLE IF EXISTS runtime_instances;
DROP TABLE IF EXISTS workspace_mounts;
ALTER TABLE sessions DROP CONSTRAINT IF EXISTS sessions_org_id_worker_group_id_project_id_environment_id__fkey;
ALTER TABLE sessions DROP CONSTRAINT IF EXISTS sessions_org_id_project_id_environment_id_workspace_id_fkey;
ALTER TABLE sessions DROP CONSTRAINT IF EXISTS sessions_org_id_worker_group_id_project_id_environment_id_workspac_fkey;
ALTER TABLE runs DROP CONSTRAINT IF EXISTS runs_org_id_worker_group_id_project_id_environment_id_work_fkey;
ALTER TABLE runs DROP CONSTRAINT IF EXISTS runs_org_id_project_id_environment_id_workspace_id_fkey;
ALTER TABLE runs DROP CONSTRAINT IF EXISTS runs_org_id_worker_group_id_project_id_environment_id_workspace_id_fkey;
DROP TABLE IF EXISTS workspaces;
DROP TABLE IF EXISTS session_start_idempotencies;
DROP TABLE IF EXISTS session_runs;
ALTER TABLE runs DROP CONSTRAINT IF EXISTS runs_session_id_fkey;
ALTER TABLE runs DROP CONSTRAINT IF EXISTS runs_org_id_worker_group_id_project_id_environment_id_sess_fkey;
ALTER TABLE runs DROP CONSTRAINT IF EXISTS runs_org_id_project_id_environment_id_session_id_task_id_fkey;
ALTER TABLE runs DROP CONSTRAINT IF EXISTS runs_org_id_worker_group_id_project_id_environment_id_session_id_t_fkey;
ALTER TABLE sessions DROP CONSTRAINT IF EXISTS sessions_current_run_id_fkey;
ALTER TABLE sessions DROP CONSTRAINT IF EXISTS sessions_org_id_worker_group_id_project_id_environment_id__fkey1;
ALTER TABLE sessions DROP CONSTRAINT IF EXISTS sessions_org_id_project_id_environment_id_task_id_fkey;
ALTER TABLE sessions DROP CONSTRAINT IF EXISTS sessions_org_id_worker_group_id_project_id_environment_id_task_id_fkey;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS auth_sessions;
ALTER TABLE run_leases DROP CONSTRAINT IF EXISTS run_leases_restore_checkpoint_id_fkey;
ALTER TABLE runs DROP CONSTRAINT IF EXISTS runs_latest_checkpoint_id_fkey;
DROP TABLE IF EXISTS checkpoint_artifacts;
DROP TABLE IF EXISTS checkpoint_workspace_snapshots;
DROP TABLE IF EXISTS checkpoint_runtime_snapshots;
DROP TYPE IF EXISTS checkpoint_artifact_role;
DROP TABLE IF EXISTS checkpoints;
ALTER TABLE runs DROP CONSTRAINT IF EXISTS runs_current_run_lease_id_fkey;
ALTER TABLE telemetry_outbox DROP CONSTRAINT IF EXISTS telemetry_outbox_run_lease_id_fkey;
DROP TABLE IF EXISTS run_state_snapshots;
DROP TABLE IF EXISTS run_leases;
DROP TABLE IF EXISTS telemetry_outbox;
DROP TABLE IF EXISTS worker_instance_credentials;
DROP TABLE IF EXISTS worker_bootstrap_tokens;
DROP TABLE IF EXISTS run_operations;
DROP TABLE IF EXISTS runs;
DROP TABLE IF EXISTS task_schedule_instances;
DROP TABLE IF EXISTS task_schedules;
DROP TYPE IF EXISTS task_schedule_type;
DROP TABLE IF EXISTS deployment_tasks;
DROP TABLE IF EXISTS deployment_queues;
DROP TRIGGER IF EXISTS runtime_substrate_artifacts_set_updated_at ON runtime_substrate_artifacts;
DROP TABLE IF EXISTS runtime_substrate_artifacts;
DROP TABLE IF EXISTS deployment_sandboxes;
DROP TABLE IF EXISTS tasks;
ALTER TABLE environments DROP CONSTRAINT IF EXISTS environments_current_deployment_fk;
DROP TABLE IF EXISTS deployment_promotions;
DROP TABLE IF EXISTS deployment_version_counters;
ALTER TABLE environments DROP COLUMN IF EXISTS current_deployment_id;
DROP TABLE IF EXISTS deployments;
DROP TABLE IF EXISTS artifacts;
DROP TABLE IF EXISTS worker_instances;
DROP TRIGGER IF EXISTS worker_groups_set_updated_at ON worker_groups;
DROP TABLE IF EXISTS worker_groups;
DROP TABLE IF EXISTS runtime_release_selections;
DROP TABLE IF EXISTS runtime_releases;
DROP TABLE IF EXISTS secrets;
DROP TYPE IF EXISTS telemetry_outbox_state;
DROP TYPE IF EXISTS telemetry_stream_kind;
DROP TYPE IF EXISTS worker_group_state;
DROP TYPE IF EXISTS worker_trust_tier;
DROP TYPE IF EXISTS worker_instance_status;
DROP TYPE IF EXISTS runtime_instance_state;
DROP TYPE IF EXISTS run_operation_status;
DROP TYPE IF EXISTS run_operation_kind;
DROP TYPE IF EXISTS run_terminal_outcome;
DROP TYPE IF EXISTS run_execution_status;
DROP TYPE IF EXISTS public_access_token_scope_type;
DROP TYPE IF EXISTS public_access_token_state;
DROP TYPE IF EXISTS run_wait_state;
DROP TYPE IF EXISTS worker_command_kind;
DROP TYPE IF EXISTS wait_state;
DROP TYPE IF EXISTS wait_kind;
DROP TYPE IF EXISTS token_state;
DROP TYPE IF EXISTS stream_record_source_type;
DROP TYPE IF EXISTS stream_direction;
DROP TYPE IF EXISTS workspace_process_state;
DROP TYPE IF EXISTS workspace_filesystem_mode;
DROP TYPE IF EXISTS workspace_lease_state;
DROP TYPE IF EXISTS workspace_lease_kind;
DROP TYPE IF EXISTS workspace_operation_idempotency_kind;
DROP TYPE IF EXISTS workspace_operation_kind;
DROP TYPE IF EXISTS workspace_operation_state;
DROP TYPE IF EXISTS workspace_mount_state;
DROP TYPE IF EXISTS workspace_version_kind;
DROP TYPE IF EXISTS workspace_version_state;
DROP TYPE IF EXISTS workspace_dirty_state;
DROP TYPE IF EXISTS workspace_desired_state;
DROP TYPE IF EXISTS workspace_state;
DROP TYPE IF EXISTS session_status;
DROP TYPE IF EXISTS checkpoint_status;
DROP TYPE IF EXISTS deployment_status;
DROP TYPE IF EXISTS run_lease_status;
DROP TYPE IF EXISTS run_status;
DROP TYPE IF EXISTS artifact_kind;
DROP TABLE IF EXISTS cas_objects;
DROP TABLE IF EXISTS secrets;
DROP TABLE IF EXISTS device_codes;
DROP TYPE IF EXISTS device_code_status;
DROP TABLE IF EXISTS api_key_grants;
DROP TABLE IF EXISTS api_keys;
DROP TABLE IF EXISTS magic_links;
DROP TYPE IF EXISTS magic_link_purpose;
DROP TABLE IF EXISTS invitations;
DROP TABLE IF EXISTS environments;
DROP TABLE IF EXISTS projects;
ALTER TABLE organizations DROP COLUMN IF EXISTS default_region_id;
DROP TABLE IF EXISTS regions;
DROP TYPE IF EXISTS region_visibility;
DROP TYPE IF EXISTS region_state;
DROP TABLE IF EXISTS deletion_jobs;
DROP TYPE IF EXISTS deletion_job_target_type;
DROP TYPE IF EXISTS deletion_job_status;
DROP TABLE IF EXISTS org_members;
DROP TYPE IF EXISTS org_member_role;
DROP TABLE IF EXISTS auth_identities;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS organizations;
DROP FUNCTION IF EXISTS set_updated_at();
