ALTER TABLE run_checkpoints DROP CONSTRAINT IF EXISTS run_checkpoints_run_wait_id_fkey;
DROP TABLE IF EXISTS run_waits;
DROP TABLE IF EXISTS outbox_messages;
DROP TABLE IF EXISTS public_access_tokens;
DROP TABLE IF EXISTS tokens;
ALTER TABLE telemetry_outbox DROP CONSTRAINT IF EXISTS telemetry_outbox_meter_event_id_fkey;
DROP TABLE IF EXISTS meter_events;
DROP TABLE IF EXISTS run_checkpoint_artifacts;
ALTER TABLE runtime_instances DROP CONSTRAINT IF EXISTS runtime_instances_restore_checkpoint_workspace_fkey;
ALTER TABLE runtime_instances DROP CONSTRAINT IF EXISTS runtime_instances_restore_checkpoint_execution_fkey;
DROP TABLE IF EXISTS run_checkpoints;
DROP TYPE IF EXISTS run_checkpoint_artifact_role;
DROP TABLE IF EXISTS secret_resolutions;
ALTER TABLE workspaces DROP CONSTRAINT IF EXISTS workspaces_head_version_id_fkey;
ALTER TABLE workspace_leases DROP CONSTRAINT IF EXISTS workspace_leases_base_version_id_fkey;
ALTER TABLE workspace_mounts DROP CONSTRAINT IF EXISTS workspace_mounts_base_version_id_fkey;
ALTER TABLE runs DROP CONSTRAINT IF EXISTS runs_base_workspace_version_fk;
ALTER TABLE run_attempts DROP CONSTRAINT IF EXISTS run_attempts_base_workspace_version_fk;
DROP TABLE IF EXISTS workspace_versions CASCADE;
ALTER TABLE workspace_leases DROP CONSTRAINT IF EXISTS workspace_leases_owner_process_id_fkey;
ALTER TABLE runtime_instances DROP CONSTRAINT IF EXISTS runtime_instances_reserved_process_id_workspace_id_fkey;
DROP TABLE IF EXISTS workspace_processes;
DROP TABLE IF EXISTS workspace_leases;
ALTER TABLE workspace_mounts DROP CONSTRAINT IF EXISTS workspace_mounts_runtime_instance_id_fkey;
ALTER TABLE run_leases DROP CONSTRAINT IF EXISTS run_leases_runtime_instance_id_fkey;
DROP TABLE IF EXISTS runtime_instances;
DROP TABLE IF EXISTS workspace_mounts;
ALTER TABLE runs DROP CONSTRAINT IF EXISTS runs_org_id_project_id_environment_id_workspace_id_fkey;
DROP TABLE IF EXISTS workspace_secrets;
DROP TABLE IF EXISTS workspaces CASCADE;
DROP TABLE IF EXISTS auth_sessions;
ALTER TABLE runs DROP CONSTRAINT IF EXISTS runs_current_run_lease_id_fkey;
ALTER TABLE telemetry_outbox DROP CONSTRAINT IF EXISTS telemetry_outbox_run_lease_id_fkey;
DROP TABLE IF EXISTS run_leases;
ALTER TABLE runs DROP CONSTRAINT IF EXISTS runs_current_attempt_fk;
DROP TABLE IF EXISTS session_records;
DROP TABLE IF EXISTS run_attempts;
DROP TABLE IF EXISTS telemetry_outbox;
DROP TABLE IF EXISTS worker_observations;
DROP TABLE IF EXISTS worker_instance_credentials;
ALTER TABLE sessions DROP CONSTRAINT IF EXISTS sessions_current_run_fk;
ALTER TABLE sessions DROP CONSTRAINT IF EXISTS sessions_failure_run_fk;
DROP TABLE IF EXISTS runs;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS schedule_secrets;
DROP TABLE IF EXISTS schedules;
DROP TABLE IF EXISTS registry_credential_resolutions;
DROP TABLE IF EXISTS idempotency_claims;
DROP TABLE IF EXISTS runtime_substrates;
DROP TABLE IF EXISTS deployment_definitions;
ALTER TABLE environments DROP CONSTRAINT IF EXISTS environments_current_deployment_fk;
DROP TABLE IF EXISTS deployment_promotions;
ALTER TABLE environments DROP COLUMN IF EXISTS current_deployment_id;
ALTER TABLE deployments DROP CONSTRAINT IF EXISTS deployments_current_build_lease_id_fkey;
DROP TABLE IF EXISTS deployment_build_leases;
DROP TABLE IF EXISTS deployments;
DROP TABLE IF EXISTS artifacts;
DROP TABLE IF EXISTS worker_instances;
DROP TABLE IF EXISTS worker_groups;
DROP TABLE IF EXISTS worker_group_tokens;
DROP TABLE IF EXISTS runtime_identities;
ALTER TABLE secrets DROP CONSTRAINT IF EXISTS secrets_current_version_fk;
DROP TABLE IF EXISTS secret_versions;
DROP TABLE IF EXISTS secrets;
DROP TYPE IF EXISTS telemetry_stream_kind;
DROP TYPE IF EXISTS run_checkpoint_kind;
DROP TYPE IF EXISTS wait_kind;
DROP TYPE IF EXISTS workspace_version_kind;
DROP TYPE IF EXISTS artifact_kind;
DROP TABLE IF EXISTS cas_objects;
DROP TABLE IF EXISTS device_codes;
DROP TABLE IF EXISTS api_key_grants;
DROP TABLE IF EXISTS api_keys;
DROP TABLE IF EXISTS magic_links;
DROP TYPE IF EXISTS magic_link_purpose;
DROP TABLE IF EXISTS invitations;
DROP TABLE IF EXISTS environments;
DROP TABLE IF EXISTS projects;
ALTER TABLE organizations DROP COLUMN IF EXISTS default_region_id;
DROP TABLE IF EXISTS regions;
DROP TYPE IF EXISTS region_visibility;
DROP TABLE IF EXISTS deletion_jobs;
DROP TYPE IF EXISTS deletion_job_target_type;
DROP TABLE IF EXISTS org_members;
DROP TYPE IF EXISTS org_member_role;
DROP TABLE IF EXISTS auth_identities;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS organizations;
