name: Setup Nix
description: Install Nix.
runs:
  using: composite
  steps:
    - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3
      with:
        github_access_token: ${{ github.token }}
