// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ArtifactKind string

const (
	ArtifactKindDeploymentProgram        ArtifactKind = "deployment_program"
	ArtifactKindWorkspaceImage           ArtifactKind = "workspace_image"
	ArtifactKindRunCheckpointConfig      ArtifactKind = "run_checkpoint_config"
	ArtifactKindRunCheckpointVMState     ArtifactKind = "run_checkpoint_vm_state"
	ArtifactKindRunCheckpointMemory      ArtifactKind = "run_checkpoint_memory"
	ArtifactKindRunCheckpointScratchDisk ArtifactKind = "run_checkpoint_scratch_disk"
	ArtifactKindWorkspaceVersion         ArtifactKind = "workspace_version"
)

func (e *ArtifactKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ArtifactKind(s)
	case string:
		*e = ArtifactKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ArtifactKind: %T", src)
	}
	return nil
}

type NullArtifactKind struct {
	ArtifactKind ArtifactKind `json:"artifact_kind"`
	Valid        bool         `json:"valid"` // Valid is true if ArtifactKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullArtifactKind) Scan(value interface{}) error {
	if value == nil {
		ns.ArtifactKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ArtifactKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullArtifactKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ArtifactKind), nil
}

type MagicLinkPurpose string

const (
	MagicLinkPurposeLogin        MagicLinkPurpose = "login"
	MagicLinkPurposeInviteAccept MagicLinkPurpose = "invite_accept"
)

func (e *MagicLinkPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MagicLinkPurpose(s)
	case string:
		*e = MagicLinkPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for MagicLinkPurpose: %T", src)
	}
	return nil
}

type NullMagicLinkPurpose struct {
	MagicLinkPurpose MagicLinkPurpose `json:"magic_link_purpose"`
	Valid            bool             `json:"valid"` // Valid is true if MagicLinkPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMagicLinkPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.MagicLinkPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MagicLinkPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMagicLinkPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MagicLinkPurpose), nil
}

type OrgMemberRole string

const (
	OrgMemberRoleOwner     OrgMemberRole = "owner"
	OrgMemberRoleAdmin     OrgMemberRole = "admin"
	OrgMemberRoleDeveloper OrgMemberRole = "developer"
	OrgMemberRoleViewer    OrgMemberRole = "viewer"
)

func (e *OrgMemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrgMemberRole(s)
	case string:
		*e = OrgMemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for OrgMemberRole: %T", src)
	}
	return nil
}

type NullOrgMemberRole struct {
	OrgMemberRole OrgMemberRole `json:"org_member_role"`
	Valid         bool          `json:"valid"` // Valid is true if OrgMemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrgMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.OrgMemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrgMemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrgMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrgMemberRole), nil
}

type TelemetryStreamKind string

const (
	TelemetryStreamKindRunLog TelemetryStreamKind = "run_log"
	TelemetryStreamKindEvent  TelemetryStreamKind = "event"
)

func (e *TelemetryStreamKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TelemetryStreamKind(s)
	case string:
		*e = TelemetryStreamKind(s)
	default:
		return fmt.Errorf("unsupported scan type for TelemetryStreamKind: %T", src)
	}
	return nil
}

type NullTelemetryStreamKind struct {
	TelemetryStreamKind TelemetryStreamKind `json:"telemetry_stream_kind"`
	Valid               bool                `json:"valid"` // Valid is true if TelemetryStreamKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTelemetryStreamKind) Scan(value interface{}) error {
	if value == nil {
		ns.TelemetryStreamKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TelemetryStreamKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTelemetryStreamKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TelemetryStreamKind), nil
}

type WaitKind string

const (
	WaitKindToken      WaitKind = "token"
	WaitKindTimer      WaitKind = "timer"
	WaitKindChild      WaitKind = "child"
	WaitKindActorInput WaitKind = "actor_input"
)

func (e *WaitKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WaitKind(s)
	case string:
		*e = WaitKind(s)
	default:
		return fmt.Errorf("unsupported scan type for WaitKind: %T", src)
	}
	return nil
}

type NullWaitKind struct {
	WaitKind WaitKind `json:"wait_kind"`
	Valid    bool     `json:"valid"` // Valid is true if WaitKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWaitKind) Scan(value interface{}) error {
	if value == nil {
		ns.WaitKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WaitKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWaitKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WaitKind), nil
}

type APIKey struct {
	ID              pgtype.UUID        `json:"id"`
	OrgID           pgtype.UUID        `json:"org_id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	EnvironmentID   pgtype.UUID        `json:"environment_id"`
	CreatedByUserID pgtype.UUID        `json:"created_by_user_id"`
	Role            OrgMemberRole      `json:"role"`
	Permissions     []string           `json:"permissions"`
	Name            string             `json:"name"`
	KeyPrefix       string             `json:"key_prefix"`
	TokenHash       []byte             `json:"token_hash"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
}

type Artifact struct {
	ID                        pgtype.UUID        `json:"id"`
	OrgID                     pgtype.UUID        `json:"org_id"`
	ProjectID                 pgtype.UUID        `json:"project_id"`
	EnvironmentID             pgtype.UUID        `json:"environment_id"`
	Digest                    string             `json:"digest"`
	Kind                      ArtifactKind       `json:"kind"`
	SizeBytes                 int64              `json:"size_bytes"`
	MediaType                 string             `json:"media_type"`
	CreatedByWorkerInstanceID pgtype.UUID        `json:"created_by_worker_instance_id"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
}

type AuthIdentity struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Provider    string             `json:"provider"`
	Subject     string             `json:"subject"`
	Email       pgtype.Text        `json:"email"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

type AuthSession struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  []byte             `json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type CasObject struct {
	OrgID     pgtype.UUID        `json:"org_id"`
	Digest    string             `json:"digest"`
	SizeBytes int64              `json:"size_bytes"`
	MediaType string             `json:"media_type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ComputerInitialization struct {
	ID                    pgtype.UUID        `json:"id"`
	EnvironmentID         pgtype.UUID        `json:"environment_id"`
	ComputerID            pgtype.UUID        `json:"computer_id"`
	VersionID             pgtype.UUID        `json:"version_id"`
	RuntimeInstanceID     pgtype.UUID        `json:"runtime_instance_id"`
	RuntimeDesiredVersion int64              `json:"runtime_desired_version"`
	OwnershipGeneration   int64              `json:"ownership_generation"`
	WriterGeneration      int64              `json:"writer_generation"`
	Digest                string             `json:"digest"`
	SizeBytes             int64              `json:"size_bytes"`
	LogicalBytes          int64              `json:"logical_bytes"`
	MediaType             string             `json:"media_type"`
	InitialConfig         []byte             `json:"initial_config"`
	Status                string             `json:"status"`
	ArtifactID            pgtype.UUID        `json:"artifact_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	ConsumedAt            pgtype.Timestamptz `json:"consumed_at"`
	AbandonedAt           pgtype.Timestamptz `json:"abandoned_at"`
}

type ControlOutbox struct {
	ID             pgtype.UUID        `json:"id"`
	Topic          string             `json:"topic"`
	Payload        []byte             `json:"payload"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	AvailableAt    pgtype.Timestamptz `json:"available_at"`
	ClaimedBy      pgtype.Text        `json:"claimed_by"`
	ClaimExpiresAt pgtype.Timestamptz `json:"claim_expires_at"`
	LastError      pgtype.Text        `json:"last_error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
}

type Deployment struct {
	ID                    pgtype.UUID        `json:"id"`
	OrgID                 pgtype.UUID        `json:"org_id"`
	ProjectID             pgtype.UUID        `json:"project_id"`
	EnvironmentID         pgtype.UUID        `json:"environment_id"`
	Version               string             `json:"version"`
	BundleDigest          string             `json:"bundle_digest"`
	RuntimeArtifactDigest string             `json:"runtime_artifact_digest"`
	ProgramArtifactID     pgtype.UUID        `json:"program_artifact_id"`
	ProgramIndexDigest    []byte             `json:"program_index_digest"`
	QueueConfig           []byte             `json:"queue_config"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type DeploymentDefinition struct {
	ID              pgtype.UUID        `json:"id"`
	EnvironmentID   pgtype.UUID        `json:"environment_id"`
	DeploymentID    pgtype.UUID        `json:"deployment_id"`
	Kind            string             `json:"kind"`
	DeclaredID      string             `json:"declared_id"`
	ManifestVersion int32              `json:"manifest_version"`
	Manifest        []byte             `json:"manifest"`
	ManifestDigest  []byte             `json:"manifest_digest"`
	ArtifactID      pgtype.UUID        `json:"artifact_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type DeviceCode struct {
	ID                  pgtype.UUID        `json:"id"`
	OrgID               pgtype.UUID        `json:"org_id"`
	UserCodeHash        []byte             `json:"user_code_hash"`
	DeviceCodeHash      []byte             `json:"device_code_hash"`
	DecidedByUserID     pgtype.UUID        `json:"decided_by_user_id"`
	Status              string             `json:"status"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	PollIntervalSeconds int32              `json:"poll_interval_seconds"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	DecidedAt           pgtype.Timestamptz `json:"decided_at"`
	ConsumedAt          pgtype.Timestamptz `json:"consumed_at"`
}

type Environment struct {
	ID                  pgtype.UUID        `json:"id"`
	OrgID               pgtype.UUID        `json:"org_id"`
	ProjectID           pgtype.UUID        `json:"project_id"`
	Slug                string             `json:"slug"`
	Name                string             `json:"name"`
	ColorHex            string             `json:"color_hex"`
	IsDefault           bool               `json:"is_default"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CurrentDeploymentID pgtype.UUID        `json:"current_deployment_id"`
}

type IdempotencyClaim struct {
	ID                 pgtype.UUID        `json:"id"`
	EnvironmentID      pgtype.UUID        `json:"environment_id"`
	Operation          string             `json:"operation"`
	SlotHash           []byte             `json:"slot_hash"`
	RequestFingerprint []byte             `json:"request_fingerprint"`
	Status             string             `json:"status"`
	Receipt            []byte             `json:"receipt"`
	AcceptedAt         pgtype.Timestamptz `json:"accepted_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	RetiredAt          pgtype.Timestamptz `json:"retired_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
}

type Invitation struct {
	ID               pgtype.UUID        `json:"id"`
	OrgID            pgtype.UUID        `json:"org_id"`
	InviteeEmail     string             `json:"invitee_email"`
	Role             OrgMemberRole      `json:"role"`
	InvitedByUserID  pgtype.UUID        `json:"invited_by_user_id"`
	TokenHash        []byte             `json:"token_hash"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt       pgtype.Timestamptz `json:"accepted_at"`
	AcceptedByUserID pgtype.UUID        `json:"accepted_by_user_id"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	RevokedByUserID  pgtype.UUID        `json:"revoked_by_user_id"`
}

type MagicLink struct {
	ID               pgtype.UUID        `json:"id"`
	Purpose          MagicLinkPurpose   `json:"purpose"`
	TokenHash        []byte             `json:"token_hash"`
	Email            string             `json:"email"`
	OrgID            pgtype.UUID        `json:"org_id"`
	InvitationID     pgtype.UUID        `json:"invitation_id"`
	RedirectAfter    pgtype.Text        `json:"redirect_after"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	SentAt           pgtype.Timestamptz `json:"sent_at"`
	DeliveryFailedAt pgtype.Timestamptz `json:"delivery_failed_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt       pgtype.Timestamptz `json:"consumed_at"`
	ConsumedByUserID pgtype.UUID        `json:"consumed_by_user_id"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
}

type OrgMember struct {
	OrgID       pgtype.UUID        `json:"org_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        OrgMemberRole      `json:"role"`
	DisplayName pgtype.Text        `json:"display_name"`
	DisabledAt  pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Organization struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID              pgtype.UUID        `json:"id"`
	OrgID           pgtype.UUID        `json:"org_id"`
	DefaultRegionID string             `json:"default_region_id"`
	Slug            string             `json:"slug"`
	Name            string             `json:"name"`
	IsDefault       bool               `json:"is_default"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type PublicAccessToken struct {
	ID         pgtype.UUID        `json:"id"`
	TokenID    pgtype.UUID        `json:"token_id"`
	TokenHash  []byte             `json:"token_hash"`
	Status     string             `json:"status"`
	Metadata   []byte             `json:"metadata"`
	CreatedBy  []byte             `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ExpiredAt  pgtype.Timestamptz `json:"expired_at"`
	MaxUses    pgtype.Int4        `json:"max_uses"`
	UsedCount  int32              `json:"used_count"`
}

type Region struct {
	ID          string             `json:"id"`
	DisplayName string             `json:"display_name"`
	Location    string             `json:"location"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Run struct {
	ID                        pgtype.UUID        `json:"id"`
	OrgID                     pgtype.UUID        `json:"org_id"`
	ProjectID                 pgtype.UUID        `json:"project_id"`
	EnvironmentID             pgtype.UUID        `json:"environment_id"`
	DeploymentID              pgtype.UUID        `json:"deployment_id"`
	DeploymentDefinitionID    pgtype.UUID        `json:"deployment_definition_id"`
	EntrypointKind            string             `json:"entrypoint_kind"`
	EntrypointDeclaredID      string             `json:"entrypoint_declared_id"`
	SessionID                 pgtype.UUID        `json:"session_id"`
	CauseKind                 string             `json:"cause_kind"`
	ScheduleID                pgtype.UUID        `json:"schedule_id"`
	ScheduleGeneration        pgtype.Int8        `json:"schedule_generation"`
	ScheduledAt               pgtype.Timestamptz `json:"scheduled_at"`
	PreviousScheduledAt       pgtype.Timestamptz `json:"previous_scheduled_at"`
	ScheduleTimezone          pgtype.Text        `json:"schedule_timezone"`
	ParentRunID               pgtype.UUID        `json:"parent_run_id"`
	ParentOwnsLifecycle       pgtype.Bool        `json:"parent_owns_lifecycle"`
	WorkspaceID               pgtype.UUID        `json:"workspace_id"`
	BaseWorkspaceVersionID    pgtype.UUID        `json:"base_workspace_version_id"`
	SessionInputStartSequence pgtype.Int8        `json:"session_input_start_sequence"`
	SessionInputHighWatermark pgtype.Int8        `json:"session_input_high_watermark"`
	Payload                   []byte             `json:"payload"`
	Output                    []byte             `json:"output"`
	Failure                   []byte             `json:"failure"`
	Status                    string             `json:"status"`
	Revision                  int64              `json:"revision"`
	CurrentAttemptNumber      int32              `json:"current_attempt_number"`
	CurrentRunLeaseID         pgtype.UUID        `json:"current_run_lease_id"`
	Metadata                  []byte             `json:"metadata"`
	Tags                      []string           `json:"tags"`
	QueueName                 string             `json:"queue_name"`
	ConcurrencyKey            pgtype.Text        `json:"concurrency_key"`
	QueueConcurrencyLimit     pgtype.Int8        `json:"queue_concurrency_limit"`
	Priority                  int32              `json:"priority"`
	QueueOriginAt             pgtype.Timestamptz `json:"queue_origin_at"`
	QueueScoreAt              pgtype.Timestamptz `json:"queue_score_at"`
	QueuedExpiresAt           pgtype.Timestamptz `json:"queued_expires_at"`
	MaxActiveDurationMs       int64              `json:"max_active_duration_ms"`
	RetryPolicy               []byte             `json:"retry_policy"`
	ActiveElapsedMs           int64              `json:"active_elapsed_ms"`
	ActiveStartedAt           pgtype.Timestamptz `json:"active_started_at"`
	TraceID                   pgtype.Text        `json:"trace_id"`
	RootSpanID                string             `json:"root_span_id"`
	ClaimID                   pgtype.UUID        `json:"claim_id"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	FirstLeaseAt              pgtype.Timestamptz `json:"first_lease_at"`
	StartedAt                 pgtype.Timestamptz `json:"started_at"`
	RetryAt                   pgtype.Timestamptz `json:"retry_at"`
	RuntimePreparationCount   int32              `json:"runtime_preparation_count"`
	NextRuntimePreparationAt  pgtype.Timestamptz `json:"next_runtime_preparation_at"`
	TerminalAt                pgtype.Timestamptz `json:"terminal_at"`
}

type RunAttempt struct {
	RunID                        pgtype.UUID        `json:"run_id"`
	Number                       int32              `json:"number"`
	EntrypointKind               string             `json:"entrypoint_kind"`
	WorkspaceID                  pgtype.UUID        `json:"workspace_id"`
	EntrypointEnteredAt          pgtype.Timestamptz `json:"entrypoint_entered_at"`
	SessionInputStartSequence    pgtype.Int8        `json:"session_input_start_sequence"`
	BaseWorkspaceVersionID       pgtype.UUID        `json:"base_workspace_version_id"`
	TerminalSessionInputSequence pgtype.Int8        `json:"terminal_session_input_sequence"`
	TerminalOutcome              pgtype.Text        `json:"terminal_outcome"`
	TerminalReasonCode           pgtype.Text        `json:"terminal_reason_code"`
	TerminalError                []byte             `json:"terminal_error"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	TerminalAt                   pgtype.Timestamptz `json:"terminal_at"`
}

type RunCheckpoint struct {
	ID                            pgtype.UUID        `json:"id"`
	RunID                         pgtype.UUID        `json:"run_id"`
	AttemptNumber                 int32              `json:"attempt_number"`
	RunWaitID                     pgtype.UUID        `json:"run_wait_id"`
	SourceRunLeaseID              pgtype.UUID        `json:"source_run_lease_id"`
	SourceWorkspaceLeaseID        pgtype.UUID        `json:"source_workspace_lease_id"`
	WorkspaceID                   pgtype.UUID        `json:"workspace_id"`
	BaseWorkspaceVersionID        pgtype.UUID        `json:"base_workspace_version_id"`
	PrivateWorkspaceVersionID     pgtype.UUID        `json:"private_workspace_version_id"`
	RuntimeConfigArtifactID       pgtype.UUID        `json:"runtime_config_artifact_id"`
	VMStateArtifactID             pgtype.UUID        `json:"vm_state_artifact_id"`
	MemoryArtifactID              pgtype.UUID        `json:"memory_artifact_id"`
	ScratchDiskArtifactID         pgtype.UUID        `json:"scratch_disk_artifact_id"`
	ActorSpeculativeInputSequence pgtype.Int8        `json:"actor_speculative_input_sequence"`
	Status                        string             `json:"status"`
	RestoreManifest               []byte             `json:"restore_manifest"`
	ReadyRequestFingerprint       pgtype.Text        `json:"ready_request_fingerprint"`
	FailedRequestFingerprint      pgtype.Text        `json:"failed_request_fingerprint"`
	ExpiresAt                     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
	ReadyAt                       pgtype.Timestamptz `json:"ready_at"`
	InvalidatedAt                 pgtype.Timestamptz `json:"invalidated_at"`
	InvalidationReasonCode        pgtype.Text        `json:"invalidation_reason_code"`
}

type RunLease struct {
	ID                               pgtype.UUID        `json:"id"`
	OrgID                            pgtype.UUID        `json:"org_id"`
	ProjectID                        pgtype.UUID        `json:"project_id"`
	EnvironmentID                    pgtype.UUID        `json:"environment_id"`
	RunID                            pgtype.UUID        `json:"run_id"`
	WorkspaceID                      pgtype.UUID        `json:"workspace_id"`
	RegionID                         string             `json:"region_id"`
	LeaseSequence                    int64              `json:"lease_sequence"`
	AttemptNumber                    int32              `json:"attempt_number"`
	WorkerGroupID                    pgtype.UUID        `json:"worker_group_id"`
	WorkerInstanceID                 pgtype.UUID        `json:"worker_instance_id"`
	WorkerEpoch                      int64              `json:"worker_epoch"`
	RuntimeInstanceID                pgtype.UUID        `json:"runtime_instance_id"`
	RuntimeIdentityID                string             `json:"runtime_identity_id"`
	RequestedCPUMillis               int64              `json:"requested_cpu_millis"`
	RequestedMemoryBytes             int64              `json:"requested_memory_bytes"`
	RequestedGuestEphemeralDiskBytes int64              `json:"requested_guest_ephemeral_disk_bytes"`
	RequestedExecutionSlots          int32              `json:"requested_execution_slots"`
	TraceID                          pgtype.Text        `json:"trace_id"`
	SpanID                           pgtype.Text        `json:"span_id"`
	ParentSpanID                     pgtype.Text        `json:"parent_span_id"`
	Traceparent                      pgtype.Text        `json:"traceparent"`
	Status                           string             `json:"status"`
	StartDeadlineAt                  pgtype.Timestamptz `json:"start_deadline_at"`
	ClaimedAt                        pgtype.Timestamptz `json:"claimed_at"`
	StartedAt                        pgtype.Timestamptz `json:"started_at"`
	RenewedAt                        pgtype.Timestamptz `json:"renewed_at"`
	ExpiresAt                        pgtype.Timestamptz `json:"expires_at"`
	PreviousExpiresAt                pgtype.Timestamptz `json:"previous_expires_at"`
	FinalizationOperationID          pgtype.UUID        `json:"finalization_operation_id"`
	FinalizationKind                 pgtype.Text        `json:"finalization_kind"`
	FinalizationStartedAt            pgtype.Timestamptz `json:"finalization_started_at"`
	FinalizationRequestFingerprint   pgtype.Text        `json:"finalization_request_fingerprint"`
	CheckpointedAt                   pgtype.Timestamptz `json:"checkpointed_at"`
	TerminalAt                       pgtype.Timestamptz `json:"terminal_at"`
	TerminalReasonCode               pgtype.Text        `json:"terminal_reason_code"`
	TerminalError                    []byte             `json:"terminal_error"`
	TerminalRequestFingerprint       pgtype.Text        `json:"terminal_request_fingerprint"`
	CreatedAt                        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                        pgtype.Timestamptz `json:"updated_at"`
}

type RunWait struct {
	ID                             pgtype.UUID        `json:"id"`
	EnvironmentID                  pgtype.UUID        `json:"environment_id"`
	RunID                          pgtype.UUID        `json:"run_id"`
	WorkspaceID                    pgtype.UUID        `json:"workspace_id"`
	TurnSessionID                  pgtype.UUID        `json:"turn_session_id"`
	TurnID                         pgtype.UUID        `json:"turn_id"`
	TurnRunGeneration              pgtype.Int8        `json:"turn_run_generation"`
	Kind                           WaitKind           `json:"kind"`
	ConditionStatus                string             `json:"condition_status"`
	DueAt                          pgtype.Timestamptz `json:"due_at"`
	TimeoutAt                      pgtype.Timestamptz `json:"timeout_at"`
	IdleTimeoutMs                  pgtype.Int8        `json:"idle_timeout_ms"`
	TokenID                        pgtype.UUID        `json:"token_id"`
	ChildRunID                     pgtype.UUID        `json:"child_run_id"`
	ChildTargetDeclaredID          pgtype.Text        `json:"child_target_declared_id"`
	ChildClaimID                   pgtype.UUID        `json:"child_claim_id"`
	ChildRequest                   []byte             `json:"child_request"`
	SessionID                      pgtype.UUID        `json:"session_id"`
	AfterInputSequence             pgtype.Int8        `json:"after_input_sequence"`
	ConditionResult                []byte             `json:"condition_result"`
	ConditionError                 []byte             `json:"condition_error"`
	ConditionTerminalAt            pgtype.Timestamptz `json:"condition_terminal_at"`
	ConditionReasonCode            pgtype.Text        `json:"condition_reason_code"`
	CompletedTurnID                pgtype.UUID        `json:"completed_turn_id"`
	SuspensionStatus               string             `json:"suspension_status"`
	TokenRegistrationRunRevision   pgtype.Int8        `json:"token_registration_run_revision"`
	RegistrationRequestFingerprint pgtype.Text        `json:"registration_request_fingerprint"`
	ExpectedRunRevision            int64              `json:"expected_run_revision"`
	AttemptNumber                  int32              `json:"attempt_number"`
	ActorSpeculativeInputSequence  pgtype.Int8        `json:"actor_speculative_input_sequence"`
	CurrentRunLeaseID              pgtype.UUID        `json:"current_run_lease_id"`
	PriorRunLeaseID                pgtype.UUID        `json:"prior_run_lease_id"`
	CheckpointRequestVersion       int64              `json:"checkpoint_request_version"`
	CheckpointAckVersion           int64              `json:"checkpoint_ack_version"`
	CheckpointDueAt                pgtype.Timestamptz `json:"checkpoint_due_at"`
	SuspendCheckpointID            pgtype.UUID        `json:"suspend_checkpoint_id"`
	ResumeAttachID                 pgtype.UUID        `json:"resume_attach_id"`
	ResumeRequestVersion           int64              `json:"resume_request_version"`
	ResumeAckVersion               int64              `json:"resume_ack_version"`
	BaseWorkspaceVersionID         pgtype.UUID        `json:"base_workspace_version_id"`
	BaseWorkspaceContentDigest     pgtype.Text        `json:"base_workspace_content_digest"`
	ResumeWorkspaceVersionID       pgtype.UUID        `json:"resume_workspace_version_id"`
	OwnershipGeneration            pgtype.Int8        `json:"ownership_generation"`
	ParentWriterGeneration         pgtype.Int8        `json:"parent_writer_generation"`
	ChildWriterGeneration          pgtype.Int8        `json:"child_writer_generation"`
	ResumeWriterGeneration         pgtype.Int8        `json:"resume_writer_generation"`
	Metadata                       []byte             `json:"metadata"`
	Tags                           []string           `json:"tags"`
	SuspensionTerminalAt           pgtype.Timestamptz `json:"suspension_terminal_at"`
	SuspensionReasonCode           pgtype.Text        `json:"suspension_reason_code"`
	SuspensionError                []byte             `json:"suspension_error"`
	CreatedAt                      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                      pgtype.Timestamptz `json:"updated_at"`
}

type RuntimeIdentity struct {
	ID                        string             `json:"id"`
	RuntimeArch               string             `json:"runtime_arch"`
	VMRuntimeContract         string             `json:"vm_runtime_contract"`
	VMRuntimeDescriptorDigest string             `json:"vm_runtime_descriptor_digest"`
	FirecrackerDigest         string             `json:"firecracker_digest"`
	FirecrackerVersion        string             `json:"firecracker_version"`
	SnapshotFormatVersion     string             `json:"snapshot_format_version"`
	HostKernelRelease         string             `json:"host_kernel_release"`
	CPUTemplateKind           string             `json:"cpu_template_kind"`
	CPUTemplateDigest         pgtype.Text        `json:"cpu_template_digest"`
	KernelDigest              string             `json:"kernel_digest"`
	InitramfsDigest           string             `json:"initramfs_digest"`
	RootfsDigest              string             `json:"rootfs_digest"`
	FirstSeenAt               pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt                pgtype.Timestamptz `json:"last_seen_at"`
}

type RuntimeInstance struct {
	ID                              pgtype.UUID        `json:"id"`
	OrgID                           pgtype.UUID        `json:"org_id"`
	WorkerGroupID                   pgtype.UUID        `json:"worker_group_id"`
	ProjectID                       pgtype.UUID        `json:"project_id"`
	EnvironmentID                   pgtype.UUID        `json:"environment_id"`
	RegionID                        string             `json:"region_id"`
	WorkerInstanceID                pgtype.UUID        `json:"worker_instance_id"`
	RuntimeIdentityID               string             `json:"runtime_identity_id"`
	DeploymentDefinitionID          pgtype.UUID        `json:"deployment_definition_id"`
	RuntimeSubstrateID              pgtype.UUID        `json:"runtime_substrate_id"`
	WorkerEpoch                     int64              `json:"worker_epoch"`
	VMVCPUCount                     int32              `json:"vm_vcpu_count"`
	CPUConfigDigest                 string             `json:"cpu_config_digest"`
	ReservedCPUMillis               int64              `json:"reserved_cpu_millis"`
	ReservedMemoryBytes             int64              `json:"reserved_memory_bytes"`
	ReservedGuestEphemeralDiskBytes int64              `json:"reserved_guest_ephemeral_disk_bytes"`
	ReservedExecutionSlots          int32              `json:"reserved_execution_slots"`
	WorkspaceID                     pgtype.UUID        `json:"workspace_id"`
	ProgramDeploymentID             pgtype.UUID        `json:"program_deployment_id"`
	RestoreCheckpointID             pgtype.UUID        `json:"restore_checkpoint_id"`
	ReservedRunID                   pgtype.UUID        `json:"reserved_run_id"`
	ReservedAttemptNumber           pgtype.Int4        `json:"reserved_attempt_number"`
	ReservedProcessID               pgtype.UUID        `json:"reserved_process_id"`
	ReservedWorkspaceVersionID      pgtype.UUID        `json:"reserved_workspace_version_id"`
	PreparationExpiresAt            pgtype.Timestamptz `json:"preparation_expires_at"`
	ReservationExpiresAt            pgtype.Timestamptz `json:"reservation_expires_at"`
	DesiredState                    string             `json:"desired_state"`
	DesiredVersion                  int64              `json:"desired_version"`
	DesiredAt                       pgtype.Timestamptz `json:"desired_at"`
	DesiredReason                   string             `json:"desired_reason"`
	ObservedState                   string             `json:"observed_state"`
	ObservedVersion                 int64              `json:"observed_version"`
	ObservedDesiredVersion          int64              `json:"observed_desired_version"`
	ObservedAt                      pgtype.Timestamptz `json:"observed_at"`
	AllocatedAt                     pgtype.Timestamptz `json:"allocated_at"`
	ReadyAt                         pgtype.Timestamptz `json:"ready_at"`
	TerminalAt                      pgtype.Timestamptz `json:"terminal_at"`
	ReclaimedAt                     pgtype.Timestamptz `json:"reclaimed_at"`
	ReclaimEvidence                 []byte             `json:"reclaim_evidence"`
	TerminalReasonCode              pgtype.Text        `json:"terminal_reason_code"`
	TerminalError                   []byte             `json:"terminal_error"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
}

type RuntimeSubstrate struct {
	ID                     pgtype.UUID        `json:"id"`
	OrgID                  pgtype.UUID        `json:"org_id"`
	ProjectID              pgtype.UUID        `json:"project_id"`
	EnvironmentID          pgtype.UUID        `json:"environment_id"`
	DeploymentDefinitionID pgtype.UUID        `json:"deployment_definition_id"`
	SubstrateDigest        string             `json:"substrate_digest"`
	SubstrateFormat        string             `json:"substrate_format"`
	SubstrateContract      string             `json:"substrate_contract"`
	SubstrateSizeBytes     int64              `json:"substrate_size_bytes"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type Schedule struct {
	ID                     pgtype.UUID        `json:"id"`
	EnvironmentID          pgtype.UUID        `json:"environment_id"`
	TaskDeclaredID         string             `json:"task_declared_id"`
	DeploymentDefinitionID pgtype.UUID        `json:"deployment_definition_id"`
	DeploymentID           pgtype.UUID        `json:"deployment_id"`
	CronPattern            string             `json:"cron_pattern"`
	Timezone               string             `json:"timezone"`
	CronSemanticsVersion   string             `json:"cron_semantics_version"`
	Generation             int64              `json:"generation"`
	Status                 string             `json:"status"`
	Revision               int64              `json:"revision"`
	EffectiveFrom          pgtype.Timestamptz `json:"effective_from"`
	NextFireAt             pgtype.Timestamptz `json:"next_fire_at"`
	LastFireAt             pgtype.Timestamptz `json:"last_fire_at"`
	ClaimedBy              pgtype.Text        `json:"claimed_by"`
	ClaimExpiresAt         pgtype.Timestamptz `json:"claim_expires_at"`
	RetryStep              pgtype.Int2        `json:"retry_step"`
	RetryAfter             pgtype.Timestamptz `json:"retry_after"`
	LastFailure            []byte             `json:"last_failure"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type ScheduleSecret struct {
	ScheduleID      pgtype.UUID        `json:"schedule_id"`
	EnvironmentID   pgtype.UUID        `json:"environment_id"`
	PlacementKind   string             `json:"placement_kind"`
	PlacementTarget string             `json:"placement_target"`
	SecretID        pgtype.UUID        `json:"secret_id"`
	Mode            string             `json:"mode"`
	AllowedOrigins  []string           `json:"allowed_origins"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Secret struct {
	ID                   pgtype.UUID        `json:"id"`
	EnvironmentID        pgtype.UUID        `json:"environment_id"`
	Name                 string             `json:"name"`
	Status               string             `json:"status"`
	Revision             int64              `json:"revision"`
	CurrentVersionID     pgtype.UUID        `json:"current_version_id"`
	RevocationGeneration int64              `json:"revocation_generation"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	RevokedAt            pgtype.Timestamptz `json:"revoked_at"`
}

type SecretResolution struct {
	ID                   pgtype.UUID        `json:"id"`
	WorkspaceID          pgtype.UUID        `json:"workspace_id"`
	RunID                pgtype.UUID        `json:"run_id"`
	AttemptNumber        pgtype.Int4        `json:"attempt_number"`
	ProcessID            pgtype.UUID        `json:"process_id"`
	PlacementKind        string             `json:"placement_kind"`
	PlacementTarget      string             `json:"placement_target"`
	SecretID             pgtype.UUID        `json:"secret_id"`
	SecretVersionID      pgtype.UUID        `json:"secret_version_id"`
	RevocationGeneration int64              `json:"revocation_generation"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type SecretVersion struct {
	ID         pgtype.UUID        `json:"id"`
	SecretID   pgtype.UUID        `json:"secret_id"`
	Version    int64              `json:"version"`
	Nonce      []byte             `json:"nonce"`
	Ciphertext []byte             `json:"ciphertext"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID                        pgtype.UUID        `json:"id"`
	EnvironmentID             pgtype.UUID        `json:"environment_id"`
	ActorDeclaredID           string             `json:"actor_declared_id"`
	DeploymentDefinitionID    pgtype.UUID        `json:"deployment_definition_id"`
	WorkspaceID               pgtype.UUID        `json:"workspace_id"`
	Key                       pgtype.Text        `json:"key"`
	CurrentRunID              pgtype.UUID        `json:"current_run_id"`
	RunGeneration             int64              `json:"run_generation"`
	Revision                  int64              `json:"revision"`
	ActiveTurnID              pgtype.UUID        `json:"active_turn_id"`
	DispatchHoldID            pgtype.UUID        `json:"dispatch_hold_id"`
	DispatchHoldRunID         pgtype.UUID        `json:"dispatch_hold_run_id"`
	DispatchHoldAttemptNumber pgtype.Int4        `json:"dispatch_hold_attempt_number"`
	DispatchHoldRunGeneration pgtype.Int8        `json:"dispatch_hold_run_generation"`
	DispatchHoldReason        pgtype.Text        `json:"dispatch_hold_reason"`
	Failure                   []byte             `json:"failure"`
	FailureRunID              pgtype.UUID        `json:"failure_run_id"`
	NextInputSequence         int64              `json:"next_input_sequence"`
	CommittedInputSequence    int64              `json:"committed_input_sequence"`
	NextEventSequence         int64              `json:"next_event_sequence"`
	RunQueueName              string             `json:"run_queue_name"`
	RunConcurrencyKey         pgtype.Text        `json:"run_concurrency_key"`
	RunQueueConcurrencyLimit  pgtype.Int8        `json:"run_queue_concurrency_limit"`
	RunPriority               int32              `json:"run_priority"`
	RunQueueTtlMs             pgtype.Int8        `json:"run_queue_ttl_ms"`
	RunMaxActiveDurationMs    int64              `json:"run_max_active_duration_ms"`
	RunRetryPolicy            []byte             `json:"run_retry_policy"`
	RunMetadata               []byte             `json:"run_metadata"`
	RunTags                   []string           `json:"run_tags"`
	Status                    string             `json:"status"`
	CloseSequence             pgtype.Int8        `json:"close_sequence"`
	CancelRequestedAt         pgtype.Timestamptz `json:"cancel_requested_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	ClosedAt                  pgtype.Timestamptz `json:"closed_at"`
	FailedAt                  pgtype.Timestamptz `json:"failed_at"`
}

type SessionEvent struct {
	ID                    pgtype.UUID        `json:"id"`
	EnvironmentID         pgtype.UUID        `json:"environment_id"`
	SessionID             pgtype.UUID        `json:"session_id"`
	TurnID                pgtype.UUID        `json:"turn_id"`
	MessageID             pgtype.UUID        `json:"message_id"`
	WorkspaceID           pgtype.UUID        `json:"workspace_id"`
	Sequence              int64              `json:"sequence"`
	Kind                  string             `json:"kind"`
	Data                  []byte             `json:"data"`
	ProducerRunID         pgtype.UUID        `json:"producer_run_id"`
	ProducerAttemptNumber pgtype.Int4        `json:"producer_attempt_number"`
	RunGeneration         pgtype.Int8        `json:"run_generation"`
	WorkspaceVersionID    pgtype.UUID        `json:"workspace_version_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type SessionMessage struct {
	ID                 pgtype.UUID        `json:"id"`
	EnvironmentID      pgtype.UUID        `json:"environment_id"`
	SessionID          pgtype.UUID        `json:"session_id"`
	TurnID             pgtype.UUID        `json:"turn_id"`
	RunID              pgtype.UUID        `json:"run_id"`
	AttemptNumber      int32              `json:"attempt_number"`
	RunGeneration      int64              `json:"run_generation"`
	Data               []byte             `json:"data"`
	AcceptedSequence   int64              `json:"accepted_sequence"`
	Status             string             `json:"status"`
	DeliveryID         pgtype.UUID        `json:"delivery_id"`
	DeliveryRunLeaseID pgtype.UUID        `json:"delivery_run_lease_id"`
	Outcome            []byte             `json:"outcome"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	HandlingAt         pgtype.Timestamptz `json:"handling_at"`
	TerminalAt         pgtype.Timestamptz `json:"terminal_at"`
}

type SessionTurn struct {
	ID                         pgtype.UUID        `json:"id"`
	EnvironmentID              pgtype.UUID        `json:"environment_id"`
	SessionID                  pgtype.UUID        `json:"session_id"`
	Sequence                   int64              `json:"sequence"`
	Data                       []byte             `json:"data"`
	SourceRunID                pgtype.UUID        `json:"source_run_id"`
	Status                     string             `json:"status"`
	RunGeneration              pgtype.Int8        `json:"run_generation"`
	RunID                      pgtype.UUID        `json:"run_id"`
	AttemptNumber              pgtype.Int4        `json:"attempt_number"`
	ReadyRunLeaseID            pgtype.UUID        `json:"ready_run_lease_id"`
	SettlementStartedAt        pgtype.Timestamptz `json:"settlement_started_at"`
	InterruptRequestedAt       pgtype.Timestamptz `json:"interrupt_requested_at"`
	TerminalEventID            pgtype.UUID        `json:"terminal_event_id"`
	TerminalRequestFingerprint pgtype.Text        `json:"terminal_request_fingerprint"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
}

type TelemetryOutbox struct {
	ID                 int64               `json:"id"`
	OrgID              pgtype.UUID         `json:"org_id"`
	StreamKind         TelemetryStreamKind `json:"stream_kind"`
	SourceKind         string              `json:"source_kind"`
	SourceID           pgtype.UUID         `json:"source_id"`
	StreamName         string              `json:"stream_name"`
	IdempotencyKey     pgtype.Text         `json:"idempotency_key"`
	ProjectID          pgtype.UUID         `json:"project_id"`
	EnvironmentID      pgtype.UUID         `json:"environment_id"`
	RunID              pgtype.UUID         `json:"run_id"`
	DeploymentID       pgtype.UUID         `json:"deployment_id"`
	RunLeaseID         pgtype.UUID         `json:"run_lease_id"`
	AttemptNumber      pgtype.Int4         `json:"attempt_number"`
	TraceID            pgtype.Text         `json:"trace_id"`
	SpanID             pgtype.Text         `json:"span_id"`
	ParentSpanID       pgtype.Text         `json:"parent_span_id"`
	Traceparent        pgtype.Text         `json:"traceparent"`
	Category           string              `json:"category"`
	Severity           string              `json:"severity"`
	Source             string              `json:"source"`
	Kind               string              `json:"kind"`
	Message            string              `json:"message"`
	Payload            []byte              `json:"payload"`
	Content            []byte              `json:"content"`
	SizeBytes          pgtype.Int8         `json:"size_bytes"`
	IngestSizeBytes    int64               `json:"ingest_size_bytes"`
	ObservedSeq        pgtype.Int8         `json:"observed_seq"`
	RedactionClass     string              `json:"redaction_class"`
	RetentionClass     string              `json:"retention_class"`
	SnapshotVersion    pgtype.Int8         `json:"snapshot_version"`
	Status             string              `json:"status"`
	RetryCount         int32               `json:"retry_count"`
	NextRetryAt        pgtype.Timestamptz  `json:"next_retry_at"`
	WrittenAt          pgtype.Timestamptz  `json:"written_at"`
	PublishedAt        pgtype.Timestamptz  `json:"published_at"`
	PublishAttempts    int32               `json:"publish_attempts"`
	PublishLockedUntil pgtype.Timestamptz  `json:"publish_locked_until"`
	IngestError        string              `json:"ingest_error"`
	PublishError       string              `json:"publish_error"`
	ObservedAt         pgtype.Timestamptz  `json:"observed_at"`
	CreatedAt          pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz  `json:"updated_at"`
}

type Token struct {
	ID                        pgtype.UUID        `json:"id"`
	OrgID                     pgtype.UUID        `json:"org_id"`
	ProjectID                 pgtype.UUID        `json:"project_id"`
	EnvironmentID             pgtype.UUID        `json:"environment_id"`
	Status                    string             `json:"status"`
	ExpiresAt                 pgtype.Timestamptz `json:"expires_at"`
	CallbackSecretFingerprint []byte             `json:"callback_secret_fingerprint"`
	CompletionFingerprint     []byte             `json:"completion_fingerprint"`
	Result                    []byte             `json:"result"`
	Error                     []byte             `json:"error"`
	Metadata                  []byte             `json:"metadata"`
	Tags                      []string           `json:"tags"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	CompletedAt               pgtype.Timestamptz `json:"completed_at"`
	ExpiredAt                 pgtype.Timestamptz `json:"expired_at"`
	CancelledAt               pgtype.Timestamptz `json:"cancelled_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	DisplayName     string             `json:"display_name"`
	ProfileImageURL pgtype.Text        `json:"profile_image_url"`
	PrimaryEmail    pgtype.Text        `json:"primary_email"`
	Admin           bool               `json:"admin"`
	DisabledAt      pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type WorkerGroup struct {
	ID            pgtype.UUID        `json:"id"`
	TokenID       pgtype.UUID        `json:"token_id"`
	RegionID      string             `json:"region_id"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	Status        string             `json:"status"`
	ClaimVersion  int64              `json:"claim_version"`
	PrimaryPoolID pgtype.UUID        `json:"primary_pool_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type WorkerGroupToken struct {
	ID         pgtype.UUID        `json:"id"`
	TokenHash  []byte             `json:"token_hash"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type WorkerInstance struct {
	ID                           pgtype.UUID        `json:"id"`
	ResourceID                   string             `json:"resource_id"`
	WorkerGroupID                pgtype.UUID        `json:"worker_group_id"`
	WorkerPoolID                 pgtype.UUID        `json:"worker_pool_id"`
	Status                       string             `json:"status"`
	ClaimVersion                 int64              `json:"claim_version"`
	CurrentEpoch                 pgtype.Int8        `json:"current_epoch"`
	CurrentServiceID             pgtype.UUID        `json:"current_service_id"`
	RuntimeIdentityID            pgtype.Text        `json:"runtime_identity_id"`
	SubstrateFormat              string             `json:"substrate_format"`
	SubstrateContract            string             `json:"substrate_contract"`
	EpochCPUMillis               int64              `json:"epoch_cpu_millis"`
	EpochMemoryBytes             int64              `json:"epoch_memory_bytes"`
	EpochGuestEphemeralDiskBytes int64              `json:"epoch_guest_ephemeral_disk_bytes"`
	PerVMCPUMillis               int64              `json:"per_vm_cpu_millis"`
	PerVMMemoryBytes             int64              `json:"per_vm_memory_bytes"`
	PerVMGuestEphemeralDiskBytes int64              `json:"per_vm_guest_ephemeral_disk_bytes"`
	MaxVMSlots                   int32              `json:"max_vm_slots"`
	MaxRuntimeStarts             int32              `json:"max_runtime_starts"`
	CPUEnvironment               []byte             `json:"cpu_environment"`
	CPUEnvironmentDigest         pgtype.Text        `json:"cpu_environment_digest"`
	ObservedAt                   pgtype.Timestamptz `json:"observed_at"`
	RunPausedReason              pgtype.Text        `json:"run_paused_reason"`
	RuntimePausedReason          pgtype.Text        `json:"runtime_paused_reason"`
	EpochStartedAt               pgtype.Timestamptz `json:"epoch_started_at"`
	ActivatedAt                  pgtype.Timestamptz `json:"activated_at"`
	DrainingAt                   pgtype.Timestamptz `json:"draining_at"`
	TerminationReadyAt           pgtype.Timestamptz `json:"termination_ready_at"`
	LostAt                       pgtype.Timestamptz `json:"lost_at"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
}

type WorkerInstanceCredential struct {
	ID               pgtype.UUID        `json:"id"`
	WorkerGroupID    pgtype.UUID        `json:"worker_group_id"`
	WorkerInstanceID pgtype.UUID        `json:"worker_instance_id"`
	KeyPrefix        string             `json:"key_prefix"`
	ClaimVersion     int64              `json:"claim_version"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	SecretHash       []byte             `json:"secret_hash"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
}

type WorkerPool struct {
	ID                              pgtype.UUID        `json:"id"`
	WorkerGroupID                   pgtype.UUID        `json:"worker_group_id"`
	Name                            string             `json:"name"`
	Status                          string             `json:"status"`
	ClaimVersion                    int64              `json:"claim_version"`
	RuntimeIdentityID               pgtype.Text        `json:"runtime_identity_id"`
	SubstrateFormat                 pgtype.Text        `json:"substrate_format"`
	SubstrateContract               pgtype.Text        `json:"substrate_contract"`
	CapacityCPUMillis               pgtype.Int8        `json:"capacity_cpu_millis"`
	CapacityMemoryBytes             pgtype.Int8        `json:"capacity_memory_bytes"`
	CapacityGuestEphemeralDiskBytes pgtype.Int8        `json:"capacity_guest_ephemeral_disk_bytes"`
	PerVMCPUMillis                  pgtype.Int8        `json:"per_vm_cpu_millis"`
	PerVMMemoryBytes                pgtype.Int8        `json:"per_vm_memory_bytes"`
	PerVMGuestEphemeralDiskBytes    pgtype.Int8        `json:"per_vm_guest_ephemeral_disk_bytes"`
	MaxVMSlots                      pgtype.Int4        `json:"max_vm_slots"`
	SealedAt                        pgtype.Timestamptz `json:"sealed_at"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
}

type WorkerPoolCpuShape struct {
	WorkerPoolID    pgtype.UUID `json:"worker_pool_id"`
	VCPUCount       int32       `json:"vcpu_count"`
	CPUConfigDigest string      `json:"cpu_config_digest"`
}

type Workspace struct {
	ID                           pgtype.UUID        `json:"id"`
	EnvironmentID                pgtype.UUID        `json:"environment_id"`
	RegionID                     string             `json:"region_id"`
	SandboxDeclaredID            pgtype.Text        `json:"sandbox_declared_id"`
	DeploymentDefinitionID       pgtype.UUID        `json:"deployment_definition_id"`
	Key                          pgtype.Text        `json:"key"`
	Revision                     int64              `json:"revision"`
	OwnerSessionID               pgtype.UUID        `json:"owner_session_id"`
	OwnerRunID                   pgtype.UUID        `json:"owner_run_id"`
	OwnershipGeneration          int64              `json:"ownership_generation"`
	WriterGeneration             int64              `json:"writer_generation"`
	HeadVersionID                pgtype.UUID        `json:"head_version_id"`
	Status                       string             `json:"status"`
	DesiredState                 string             `json:"desired_state"`
	DirtyState                   string             `json:"dirty_state"`
	LastActivityAt               pgtype.Timestamptz `json:"last_activity_at"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                    pgtype.Timestamptz `json:"deleted_at"`
	SecretCaCertificate          []byte             `json:"secret_ca_certificate"`
	SecretCaPrivateKeyNonce      []byte             `json:"secret_ca_private_key_nonce"`
	SecretCaPrivateKeyCiphertext []byte             `json:"secret_ca_private_key_ciphertext"`
	SecretCaNotAfter             pgtype.Timestamptz `json:"secret_ca_not_after"`
}

type WorkspaceLease struct {
	ID                     pgtype.UUID        `json:"id"`
	OrgID                  pgtype.UUID        `json:"org_id"`
	WorkerGroupID          pgtype.UUID        `json:"worker_group_id"`
	ProjectID              pgtype.UUID        `json:"project_id"`
	EnvironmentID          pgtype.UUID        `json:"environment_id"`
	RegionID               string             `json:"region_id"`
	WorkerInstanceID       pgtype.UUID        `json:"worker_instance_id"`
	WorkerEpoch            int64              `json:"worker_epoch"`
	RuntimeInstanceID      pgtype.UUID        `json:"runtime_instance_id"`
	WorkspaceID            pgtype.UUID        `json:"workspace_id"`
	WorkspaceMountID       pgtype.UUID        `json:"workspace_mount_id"`
	Status                 string             `json:"status"`
	OwnerRunLeaseID        pgtype.UUID        `json:"owner_run_lease_id"`
	OwnerProcessID         pgtype.UUID        `json:"owner_process_id"`
	BaseWorkspaceVersionID pgtype.UUID        `json:"base_workspace_version_id"`
	OwnershipGeneration    int64              `json:"ownership_generation"`
	WriterGeneration       int64              `json:"writer_generation"`
	MountFencingGeneration int64              `json:"mount_fencing_generation"`
	FencingTokenHash       string             `json:"fencing_token_hash"`
	AcquiredAt             pgtype.Timestamptz `json:"acquired_at"`
	RenewedAt              pgtype.Timestamptz `json:"renewed_at"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	ReleasedAt             pgtype.Timestamptz `json:"released_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	TerminalAt             pgtype.Timestamptz `json:"terminal_at"`
	TerminalReasonCode     pgtype.Text        `json:"terminal_reason_code"`
	TerminalError          []byte             `json:"terminal_error"`
}

type WorkspaceMount struct {
	ID                         pgtype.UUID        `json:"id"`
	OrgID                      pgtype.UUID        `json:"org_id"`
	WorkerGroupID              pgtype.UUID        `json:"worker_group_id"`
	ProjectID                  pgtype.UUID        `json:"project_id"`
	EnvironmentID              pgtype.UUID        `json:"environment_id"`
	RegionID                   string             `json:"region_id"`
	WorkerInstanceID           pgtype.UUID        `json:"worker_instance_id"`
	WorkerEpoch                int64              `json:"worker_epoch"`
	WorkspaceID                pgtype.UUID        `json:"workspace_id"`
	MaterializedVersionID      pgtype.UUID        `json:"materialized_version_id"`
	RuntimeInstanceID          pgtype.UUID        `json:"runtime_instance_id"`
	GuestChannelTokenHash      string             `json:"guest_channel_token_hash"`
	GuestChannelTokenExpiresAt pgtype.Timestamptz `json:"guest_channel_token_expires_at"`
	Status                     string             `json:"status"`
	Request                    []byte             `json:"request"`
	DirtyGeneration            int64              `json:"dirty_generation"`
	FencingGeneration          int64              `json:"fencing_generation"`
	FinalizationKind           pgtype.Text        `json:"finalization_kind"`
	FinalizationReasonCode     pgtype.Text        `json:"finalization_reason_code"`
	FinalizationError          []byte             `json:"finalization_error"`
	StagedVersionID            pgtype.UUID        `json:"staged_version_id"`
	MountedAt                  pgtype.Timestamptz `json:"mounted_at"`
	UnmountedAt                pgtype.Timestamptz `json:"unmounted_at"`
	StoppedAt                  pgtype.Timestamptz `json:"stopped_at"`
	LostAt                     pgtype.Timestamptz `json:"lost_at"`
	FailedAt                   pgtype.Timestamptz `json:"failed_at"`
	TerminalAt                 pgtype.Timestamptz `json:"terminal_at"`
	TerminalReasonCode         pgtype.Text        `json:"terminal_reason_code"`
	TerminalError              []byte             `json:"terminal_error"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceProcess struct {
	ID                     pgtype.UUID        `json:"id"`
	OrgID                  pgtype.UUID        `json:"org_id"`
	ProjectID              pgtype.UUID        `json:"project_id"`
	EnvironmentID          pgtype.UUID        `json:"environment_id"`
	WorkspaceID            pgtype.UUID        `json:"workspace_id"`
	BaseWorkspaceVersionID pgtype.UUID        `json:"base_workspace_version_id"`
	RestoreDesiredState    string             `json:"restore_desired_state"`
	RegionID               pgtype.Text        `json:"region_id"`
	WorkerGroupID          pgtype.UUID        `json:"worker_group_id"`
	WorkerInstanceID       pgtype.UUID        `json:"worker_instance_id"`
	WorkerEpoch            pgtype.Int8        `json:"worker_epoch"`
	RuntimeInstanceID      pgtype.UUID        `json:"runtime_instance_id"`
	WorkspaceMountID       pgtype.UUID        `json:"workspace_mount_id"`
	Status                 string             `json:"status"`
	Revision               int64              `json:"revision"`
	Request                []byte             `json:"request"`
	Stdin                  []byte             `json:"stdin"`
	Stdout                 []byte             `json:"stdout"`
	Stderr                 []byte             `json:"stderr"`
	ClaimID                pgtype.UUID        `json:"claim_id"`
	ExitCode               pgtype.Int4        `json:"exit_code"`
	CreatedBySubjectType   string             `json:"created_by_subject_type"`
	CreatedBySubjectID     string             `json:"created_by_subject_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	StartedAt              pgtype.Timestamptz `json:"started_at"`
	ExitedAt               pgtype.Timestamptz `json:"exited_at"`
	TerminalAt             pgtype.Timestamptz `json:"terminal_at"`
	TerminalReasonCode     pgtype.Text        `json:"terminal_reason_code"`
	Error                  []byte             `json:"error"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceSecret struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	EnvironmentID   pgtype.UUID        `json:"environment_id"`
	PlacementKind   string             `json:"placement_kind"`
	PlacementTarget string             `json:"placement_target"`
	SecretID        pgtype.UUID        `json:"secret_id"`
	Mode            string             `json:"mode"`
	AllowedOrigins  []string           `json:"allowed_origins"`
	Placeholder     string             `json:"placeholder"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type WorkspaceVersion struct {
	ID                     pgtype.UUID        `json:"id"`
	EnvironmentID          pgtype.UUID        `json:"environment_id"`
	WorkspaceID            pgtype.UUID        `json:"workspace_id"`
	ParentVersionID        pgtype.UUID        `json:"parent_version_id"`
	ArtifactID             pgtype.UUID        `json:"artifact_id"`
	ContentDigest          pgtype.Text        `json:"content_digest"`
	SizeBytes              int64              `json:"size_bytes"`
	EntryCount             int32              `json:"entry_count"`
	Status                 string             `json:"status"`
	SourceWorkspaceLeaseID pgtype.UUID        `json:"source_workspace_lease_id"`
	OwnershipGeneration    int64              `json:"ownership_generation"`
	WriterGeneration       int64              `json:"writer_generation"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	PublishedAt            pgtype.Timestamptz `json:"published_at"`
	DiscardedAt            pgtype.Timestamptz `json:"discarded_at"`
}
