// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox_messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutboxMessages = `-- name: ClaimOutboxMessages :many
WITH candidates AS (
    SELECT id
    FROM outbox_messages
    WHERE (
        (state = 'pending' AND available_at <= now())
        OR
        (state = 'claimed' AND claim_expires_at <= now())
      )
      AND outbox_messages.lane = $3
      AND outbox_messages.topic = ANY($4::text[])
    ORDER BY available_at, id
    LIMIT $5
    FOR UPDATE SKIP LOCKED
)
UPDATE outbox_messages
SET state = 'claimed',
    attempts = attempts + 1,
    claimed_by = $1,
    claim_expires_at = $2
FROM candidates
WHERE outbox_messages.id = candidates.id
RETURNING outbox_messages.id, outbox_messages.lane, outbox_messages.topic, outbox_messages.partition_key, outbox_messages.payload, outbox_messages.state, outbox_messages.attempts, outbox_messages.available_at, outbox_messages.claimed_by, outbox_messages.claim_expires_at, outbox_messages.last_error, outbox_messages.created_at, outbox_messages.delivered_at
`

type ClaimOutboxMessagesParams struct {
	ClaimedBy      pgtype.Text        `json:"claimed_by"`
	ClaimExpiresAt pgtype.Timestamptz `json:"claim_expires_at"`
	Lane           string             `json:"lane"`
	Topics         []string           `json:"topics"`
	RowLimit       int32              `json:"row_limit"`
}

func (q *Queries) ClaimOutboxMessages(ctx context.Context, arg ClaimOutboxMessagesParams) ([]OutboxMessage, error) {
	rows, err := q.db.Query(ctx, claimOutboxMessages,
		arg.ClaimedBy,
		arg.ClaimExpiresAt,
		arg.Lane,
		arg.Topics,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxMessage
	for rows.Next() {
		var i OutboxMessage
		if err := rows.Scan(
			&i.ID,
			&i.Lane,
			&i.Topic,
			&i.PartitionKey,
			&i.Payload,
			&i.State,
			&i.Attempts,
			&i.AvailableAt,
			&i.ClaimedBy,
			&i.ClaimExpiresAt,
			&i.LastError,
			&i.CreatedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createOutboxMessage = `-- name: CreateOutboxMessage :one
INSERT INTO outbox_messages (
    id,
    lane,
    topic,
    partition_key,
    payload,
    available_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, lane, topic, partition_key, payload, state, attempts, available_at, claimed_by, claim_expires_at, last_error, created_at, delivered_at
`

type CreateOutboxMessageParams struct {
	ID           pgtype.UUID        `json:"id"`
	Lane         string             `json:"lane"`
	Topic        string             `json:"topic"`
	PartitionKey string             `json:"partition_key"`
	Payload      []byte             `json:"payload"`
	AvailableAt  pgtype.Timestamptz `json:"available_at"`
}

func (q *Queries) CreateOutboxMessage(ctx context.Context, arg CreateOutboxMessageParams) (OutboxMessage, error) {
	row := q.db.QueryRow(ctx, createOutboxMessage,
		arg.ID,
		arg.Lane,
		arg.Topic,
		arg.PartitionKey,
		arg.Payload,
		arg.AvailableAt,
	)
	var i OutboxMessage
	err := row.Scan(
		&i.ID,
		&i.Lane,
		&i.Topic,
		&i.PartitionKey,
		&i.Payload,
		&i.State,
		&i.Attempts,
		&i.AvailableAt,
		&i.ClaimedBy,
		&i.ClaimExpiresAt,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const createRunAdmissionOutbox = `-- name: CreateRunAdmissionOutbox :one
INSERT INTO outbox_messages (
    id,
    lane,
    topic,
    partition_key,
    payload,
    available_at
)
VALUES (
    $1,
    'control',
    'run.admit',
    $2::uuid::text,
    jsonb_build_object(
        'environmentId', $3::uuid::text,
        'runId', $4::uuid::text
    ),
    now()
)
RETURNING id, lane, topic, partition_key, payload, state, attempts, available_at, claimed_by, claim_expires_at, last_error, created_at, delivered_at
`

type CreateRunAdmissionOutboxParams struct {
	ID            pgtype.UUID `json:"id"`
	WorkspaceID   pgtype.UUID `json:"workspace_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	RunID         pgtype.UUID `json:"run_id"`
}

func (q *Queries) CreateRunAdmissionOutbox(ctx context.Context, arg CreateRunAdmissionOutboxParams) (OutboxMessage, error) {
	row := q.db.QueryRow(ctx, createRunAdmissionOutbox,
		arg.ID,
		arg.WorkspaceID,
		arg.EnvironmentID,
		arg.RunID,
	)
	var i OutboxMessage
	err := row.Scan(
		&i.ID,
		&i.Lane,
		&i.Topic,
		&i.PartitionKey,
		&i.Payload,
		&i.State,
		&i.Attempts,
		&i.AvailableAt,
		&i.ClaimedBy,
		&i.ClaimExpiresAt,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const deadLetterOutboxMessage = `-- name: DeadLetterOutboxMessage :one
UPDATE outbox_messages
SET state = 'dead_lettered',
    claimed_by = NULL,
    claim_expires_at = NULL,
    last_error = $1
WHERE id = $2
  AND state = 'claimed'
  AND claimed_by = $3
  AND attempts = $4
  AND claim_expires_at > now()
RETURNING id, lane, topic, partition_key, payload, state, attempts, available_at, claimed_by, claim_expires_at, last_error, created_at, delivered_at
`

type DeadLetterOutboxMessageParams struct {
	LastError    []byte      `json:"last_error"`
	ID           pgtype.UUID `json:"id"`
	ClaimedBy    pgtype.Text `json:"claimed_by"`
	ClaimAttempt int32       `json:"claim_attempt"`
}

func (q *Queries) DeadLetterOutboxMessage(ctx context.Context, arg DeadLetterOutboxMessageParams) (OutboxMessage, error) {
	row := q.db.QueryRow(ctx, deadLetterOutboxMessage,
		arg.LastError,
		arg.ID,
		arg.ClaimedBy,
		arg.ClaimAttempt,
	)
	var i OutboxMessage
	err := row.Scan(
		&i.ID,
		&i.Lane,
		&i.Topic,
		&i.PartitionKey,
		&i.Payload,
		&i.State,
		&i.Attempts,
		&i.AvailableAt,
		&i.ClaimedBy,
		&i.ClaimExpiresAt,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const deliverOutboxMessage = `-- name: DeliverOutboxMessage :one
UPDATE outbox_messages
SET state = 'delivered',
    claimed_by = NULL,
    claim_expires_at = NULL,
    last_error = NULL,
    delivered_at = now()
WHERE id = $1
  AND state = 'claimed'
  AND claimed_by = $2
  AND attempts = $3
  AND claim_expires_at > now()
RETURNING id, lane, topic, partition_key, payload, state, attempts, available_at, claimed_by, claim_expires_at, last_error, created_at, delivered_at
`

type DeliverOutboxMessageParams struct {
	ID           pgtype.UUID `json:"id"`
	ClaimedBy    pgtype.Text `json:"claimed_by"`
	ClaimAttempt int32       `json:"claim_attempt"`
}

func (q *Queries) DeliverOutboxMessage(ctx context.Context, arg DeliverOutboxMessageParams) (OutboxMessage, error) {
	row := q.db.QueryRow(ctx, deliverOutboxMessage, arg.ID, arg.ClaimedBy, arg.ClaimAttempt)
	var i OutboxMessage
	err := row.Scan(
		&i.ID,
		&i.Lane,
		&i.Topic,
		&i.PartitionKey,
		&i.Payload,
		&i.State,
		&i.Attempts,
		&i.AvailableAt,
		&i.ClaimedBy,
		&i.ClaimExpiresAt,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const retryOutboxMessage = `-- name: RetryOutboxMessage :one
UPDATE outbox_messages
SET state = 'pending',
    claimed_by = NULL,
    claim_expires_at = NULL,
    available_at = $1,
    last_error = $2
WHERE id = $3
  AND state = 'claimed'
  AND claimed_by = $4
  AND attempts = $5
  AND claim_expires_at > now()
RETURNING id, lane, topic, partition_key, payload, state, attempts, available_at, claimed_by, claim_expires_at, last_error, created_at, delivered_at
`

type RetryOutboxMessageParams struct {
	AvailableAt  pgtype.Timestamptz `json:"available_at"`
	LastError    []byte             `json:"last_error"`
	ID           pgtype.UUID        `json:"id"`
	ClaimedBy    pgtype.Text        `json:"claimed_by"`
	ClaimAttempt int32              `json:"claim_attempt"`
}

func (q *Queries) RetryOutboxMessage(ctx context.Context, arg RetryOutboxMessageParams) (OutboxMessage, error) {
	row := q.db.QueryRow(ctx, retryOutboxMessage,
		arg.AvailableAt,
		arg.LastError,
		arg.ID,
		arg.ClaimedBy,
		arg.ClaimAttempt,
	)
	var i OutboxMessage
	err := row.Scan(
		&i.ID,
		&i.Lane,
		&i.Topic,
		&i.PartitionKey,
		&i.Payload,
		&i.State,
		&i.Attempts,
		&i.AvailableAt,
		&i.ClaimedBy,
		&i.ClaimExpiresAt,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}
