// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (id, org_id, project_id, slug, name, is_default)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, org_id, project_id, slug, name, is_default, archived_at, created_at, updated_at
`

type CreateEnvironmentParams struct {
	ID        pgtype.UUID `json:"id"`
	OrgID     pgtype.UUID `json:"org_id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Slug      string      `json:"slug"`
	Name      string      `json:"name"`
	IsDefault bool        `json:"is_default"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.Slug,
		arg.Name,
		arg.IsDefault,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.IsDefault,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEnvironmentWithDefaultWorkerGroup = `-- name: CreateEnvironmentWithDefaultWorkerGroup :one
WITH environment AS (
    INSERT INTO environments (id, org_id, project_id, slug, name, is_default)
    VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        false
    )
    RETURNING id, org_id, project_id, slug, name, is_default, archived_at, created_at, updated_at
),
worker_group AS (
    INSERT INTO worker_groups (org_id, project_id, environment_id, slug, name, provisioning_mode, queue_name, region, capabilities, metadata)
    SELECT environment.org_id,
           environment.project_id,
           environment.id,
           'default',
           'Default',
           'customer_managed',
           projects.slug || '/' || environment.slug,
           '',
           '{}'::jsonb,
           '{}'::jsonb
      FROM environment
      JOIN projects ON projects.org_id = environment.org_id
                   AND projects.id = environment.project_id
    RETURNING id
)
SELECT environment.id, environment.org_id, environment.project_id, environment.slug, environment.name, environment.is_default, environment.archived_at, environment.created_at, environment.updated_at
  FROM environment
  JOIN worker_group ON true
`

type CreateEnvironmentWithDefaultWorkerGroupParams struct {
	ID        pgtype.UUID `json:"id"`
	OrgID     pgtype.UUID `json:"org_id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Slug      string      `json:"slug"`
	Name      string      `json:"name"`
}

type CreateEnvironmentWithDefaultWorkerGroupRow struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	Slug       string             `json:"slug"`
	Name       string             `json:"name"`
	IsDefault  bool               `json:"is_default"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateEnvironmentWithDefaultWorkerGroup(ctx context.Context, arg CreateEnvironmentWithDefaultWorkerGroupParams) (CreateEnvironmentWithDefaultWorkerGroupRow, error) {
	row := q.db.QueryRow(ctx, createEnvironmentWithDefaultWorkerGroup,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.Slug,
		arg.Name,
	)
	var i CreateEnvironmentWithDefaultWorkerGroupRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.IsDefault,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, org_id, slug, name, is_default)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, org_id, slug, name, is_default, archived_at, created_at, updated_at
`

type CreateProjectParams struct {
	ID        pgtype.UUID `json:"id"`
	OrgID     pgtype.UUID `json:"org_id"`
	Slug      string      `json:"slug"`
	Name      string      `json:"name"`
	IsDefault bool        `json:"is_default"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.OrgID,
		arg.Slug,
		arg.Name,
		arg.IsDefault,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.IsDefault,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectWithDefaultEnvironment = `-- name: CreateProjectWithDefaultEnvironment :one
WITH project AS (
    INSERT INTO projects (id, org_id, slug, name, is_default)
    VALUES (
        $1,
        $2,
        $3,
        $4,
        false
    )
    RETURNING id, org_id, slug, name, is_default, archived_at, created_at, updated_at
),
environment AS (
    INSERT INTO environments (id, org_id, project_id, slug, name, is_default)
    SELECT $5, project.org_id, project.id, 'default', 'Default', true
      FROM project
    RETURNING id
),
worker_group AS (
    INSERT INTO worker_groups (org_id, project_id, environment_id, slug, name, provisioning_mode, queue_name, region, capabilities, metadata)
    SELECT project.org_id,
           project.id,
           environment.id,
           'default',
           'Default',
           'customer_managed',
           project.slug || '/default',
           '',
           '{}'::jsonb,
           '{}'::jsonb
      FROM project
      JOIN environment ON true
    RETURNING id
)
SELECT project.id, project.org_id, project.slug, project.name, project.is_default, project.archived_at, project.created_at, project.updated_at
  FROM project
  JOIN environment ON true
  JOIN worker_group ON true
`

type CreateProjectWithDefaultEnvironmentParams struct {
	ID            pgtype.UUID `json:"id"`
	OrgID         pgtype.UUID `json:"org_id"`
	Slug          string      `json:"slug"`
	Name          string      `json:"name"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
}

type CreateProjectWithDefaultEnvironmentRow struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	Slug       string             `json:"slug"`
	Name       string             `json:"name"`
	IsDefault  bool               `json:"is_default"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateProjectWithDefaultEnvironment(ctx context.Context, arg CreateProjectWithDefaultEnvironmentParams) (CreateProjectWithDefaultEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, createProjectWithDefaultEnvironment,
		arg.ID,
		arg.OrgID,
		arg.Slug,
		arg.Name,
		arg.EnvironmentID,
	)
	var i CreateProjectWithDefaultEnvironmentRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.IsDefault,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, org_id, project_id, slug, name, is_default, archived_at, created_at, updated_at
  FROM environments
 WHERE org_id = $1
   AND project_id = $2
   AND id = $3
   AND archived_at IS NULL
`

type GetEnvironmentParams struct {
	OrgID     pgtype.UUID `json:"org_id"`
	ProjectID pgtype.UUID `json:"project_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) GetEnvironment(ctx context.Context, arg GetEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, arg.OrgID, arg.ProjectID, arg.ID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.IsDefault,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvironmentBySlug = `-- name: GetEnvironmentBySlug :one
SELECT id, org_id, project_id, slug, name, is_default, archived_at, created_at, updated_at
  FROM environments
 WHERE org_id = $1
   AND project_id = $2
   AND slug = $3
   AND archived_at IS NULL
`

type GetEnvironmentBySlugParams struct {
	OrgID     pgtype.UUID `json:"org_id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Slug      string      `json:"slug"`
}

func (q *Queries) GetEnvironmentBySlug(ctx context.Context, arg GetEnvironmentBySlugParams) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentBySlug, arg.OrgID, arg.ProjectID, arg.Slug)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.IsDefault,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, org_id, slug, name, is_default, archived_at, created_at, updated_at
  FROM projects
 WHERE org_id = $1
   AND id = $2
   AND archived_at IS NULL
`

type GetProjectParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, arg.OrgID, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.IsDefault,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, org_id, slug, name, is_default, archived_at, created_at, updated_at
  FROM projects
 WHERE org_id = $1
   AND slug = $2
   AND archived_at IS NULL
`

type GetProjectBySlugParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	Slug  string      `json:"slug"`
}

func (q *Queries) GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, arg.OrgID, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.IsDefault,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT id, org_id, project_id, slug, name, is_default, archived_at, created_at, updated_at
  FROM environments
 WHERE org_id = $1
   AND project_id = $2
   AND archived_at IS NULL
 ORDER BY is_default DESC, lower(slug), created_at ASC
`

type ListEnvironmentsParams struct {
	OrgID     pgtype.UUID `json:"org_id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) ListEnvironments(ctx context.Context, arg ListEnvironmentsParams) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironments, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Slug,
			&i.Name,
			&i.IsDefault,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, org_id, slug, name, is_default, archived_at, created_at, updated_at
  FROM projects
 WHERE org_id = $1
   AND archived_at IS NULL
 ORDER BY is_default DESC, lower(slug), created_at ASC
`

func (q *Queries) ListProjects(ctx context.Context, orgID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Slug,
			&i.Name,
			&i.IsDefault,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
