// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_github_repositories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const connectProjectGitHubRepository = `-- name: ConnectProjectGitHubRepository :one
WITH access_target AS (
    SELECT r.org_id,
           r.github_repository_id
      FROM github_repositories r
      JOIN github_app_installations i
        ON i.org_id = r.org_id
       AND i.installation_id = r.installation_id
     WHERE r.org_id = $4
       AND r.github_repository_id = $5
       AND r.deleted_at IS NULL
       AND i.suspended_at IS NULL
       AND i.deleted_at IS NULL
     FOR UPDATE OF r, i
)
INSERT INTO project_github_repositories (
    id,
    org_id,
    project_id,
    github_repository_id,
    connected_by_user_id
)
SELECT $1,
       access_target.org_id,
       $2,
       access_target.github_repository_id,
       $3
  FROM access_target
ON CONFLICT (org_id, project_id, github_repository_id) DO UPDATE
   SET connected_by_user_id = EXCLUDED.connected_by_user_id,
       updated_at = now()
RETURNING id, org_id, project_id, github_repository_id, connected_by_user_id, created_at, updated_at
`

type ConnectProjectGitHubRepositoryParams struct {
	ID                 pgtype.UUID `json:"id"`
	ProjectID          pgtype.UUID `json:"project_id"`
	ConnectedByUserID  pgtype.UUID `json:"connected_by_user_id"`
	OrgID              pgtype.UUID `json:"org_id"`
	GithubRepositoryID int64       `json:"github_repository_id"`
}

func (q *Queries) ConnectProjectGitHubRepository(ctx context.Context, arg ConnectProjectGitHubRepositoryParams) (ProjectGithubRepository, error) {
	row := q.db.QueryRow(ctx, connectProjectGitHubRepository,
		arg.ID,
		arg.ProjectID,
		arg.ConnectedByUserID,
		arg.OrgID,
		arg.GithubRepositoryID,
	)
	var i ProjectGithubRepository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.GithubRepositoryID,
		&i.ConnectedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disconnectProjectGitHubRepository = `-- name: DisconnectProjectGitHubRepository :one
DELETE FROM project_github_repositories pgr
 USING github_repositories r
  JOIN github_app_installations i
    ON i.org_id = r.org_id
   AND i.installation_id = r.installation_id
 WHERE pgr.org_id = $1
   AND pgr.project_id = $2
   AND pgr.github_repository_id = $3
   AND r.org_id = pgr.org_id
   AND r.github_repository_id = pgr.github_repository_id
   AND r.deleted_at IS NULL
   AND i.suspended_at IS NULL
   AND i.deleted_at IS NULL
RETURNING pgr.id, pgr.org_id, pgr.project_id, pgr.github_repository_id, pgr.connected_by_user_id, pgr.created_at, pgr.updated_at
`

type DisconnectProjectGitHubRepositoryParams struct {
	OrgID              pgtype.UUID `json:"org_id"`
	ProjectID          pgtype.UUID `json:"project_id"`
	GithubRepositoryID int64       `json:"github_repository_id"`
}

func (q *Queries) DisconnectProjectGitHubRepository(ctx context.Context, arg DisconnectProjectGitHubRepositoryParams) (ProjectGithubRepository, error) {
	row := q.db.QueryRow(ctx, disconnectProjectGitHubRepository, arg.OrgID, arg.ProjectID, arg.GithubRepositoryID)
	var i ProjectGithubRepository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.GithubRepositoryID,
		&i.ConnectedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveProjectGitHubRepository = `-- name: GetActiveProjectGitHubRepository :one
SELECT pgr.id AS project_github_repository_id,
       r.installation_id,
       r.github_repository_id,
       r.full_name,
       r.name AS repository_name
  FROM project_github_repositories pgr
  JOIN github_repositories r
    ON r.org_id = pgr.org_id
   AND r.github_repository_id = pgr.github_repository_id
  JOIN github_app_installations i
    ON i.org_id = r.org_id
   AND i.installation_id = r.installation_id
 WHERE pgr.org_id = $1
   AND pgr.project_id = $2
   AND pgr.github_repository_id = $3
   AND r.deleted_at IS NULL
   AND i.suspended_at IS NULL
   AND i.deleted_at IS NULL
 LIMIT 1
`

type GetActiveProjectGitHubRepositoryParams struct {
	OrgID              pgtype.UUID `json:"org_id"`
	ProjectID          pgtype.UUID `json:"project_id"`
	GithubRepositoryID int64       `json:"github_repository_id"`
}

type GetActiveProjectGitHubRepositoryRow struct {
	ProjectGithubRepositoryID pgtype.UUID `json:"project_github_repository_id"`
	InstallationID            int64       `json:"installation_id"`
	GithubRepositoryID        int64       `json:"github_repository_id"`
	FullName                  string      `json:"full_name"`
	RepositoryName            string      `json:"repository_name"`
}

func (q *Queries) GetActiveProjectGitHubRepository(ctx context.Context, arg GetActiveProjectGitHubRepositoryParams) (GetActiveProjectGitHubRepositoryRow, error) {
	row := q.db.QueryRow(ctx, getActiveProjectGitHubRepository, arg.OrgID, arg.ProjectID, arg.GithubRepositoryID)
	var i GetActiveProjectGitHubRepositoryRow
	err := row.Scan(
		&i.ProjectGithubRepositoryID,
		&i.InstallationID,
		&i.GithubRepositoryID,
		&i.FullName,
		&i.RepositoryName,
	)
	return i, err
}

const getActiveProjectGitHubRepositoryByFullName = `-- name: GetActiveProjectGitHubRepositoryByFullName :one
SELECT pgr.id AS project_github_repository_id,
       r.installation_id,
       r.github_repository_id,
       r.full_name,
       r.name AS repository_name
  FROM project_github_repositories pgr
  JOIN github_repositories r
    ON r.org_id = pgr.org_id
   AND r.github_repository_id = pgr.github_repository_id
  JOIN github_app_installations i
    ON i.org_id = r.org_id
   AND i.installation_id = r.installation_id
 WHERE pgr.org_id = $1
   AND pgr.project_id = $2
   AND lower(r.full_name) = lower($3)
   AND r.deleted_at IS NULL
   AND i.suspended_at IS NULL
   AND i.deleted_at IS NULL
 LIMIT 1
`

type GetActiveProjectGitHubRepositoryByFullNameParams struct {
	OrgID     pgtype.UUID `json:"org_id"`
	ProjectID pgtype.UUID `json:"project_id"`
	FullName  string      `json:"full_name"`
}

type GetActiveProjectGitHubRepositoryByFullNameRow struct {
	ProjectGithubRepositoryID pgtype.UUID `json:"project_github_repository_id"`
	InstallationID            int64       `json:"installation_id"`
	GithubRepositoryID        int64       `json:"github_repository_id"`
	FullName                  string      `json:"full_name"`
	RepositoryName            string      `json:"repository_name"`
}

func (q *Queries) GetActiveProjectGitHubRepositoryByFullName(ctx context.Context, arg GetActiveProjectGitHubRepositoryByFullNameParams) (GetActiveProjectGitHubRepositoryByFullNameRow, error) {
	row := q.db.QueryRow(ctx, getActiveProjectGitHubRepositoryByFullName, arg.OrgID, arg.ProjectID, arg.FullName)
	var i GetActiveProjectGitHubRepositoryByFullNameRow
	err := row.Scan(
		&i.ProjectGithubRepositoryID,
		&i.InstallationID,
		&i.GithubRepositoryID,
		&i.FullName,
		&i.RepositoryName,
	)
	return i, err
}

const listActiveProjectGitHubRepositories = `-- name: ListActiveProjectGitHubRepositories :many
SELECT pgr.id AS project_github_repository_id,
       r.installation_id,
       r.github_repository_id,
       r.full_name,
       r.name AS repository_name
  FROM project_github_repositories pgr
  JOIN github_repositories r
    ON r.org_id = pgr.org_id
   AND r.github_repository_id = pgr.github_repository_id
  JOIN github_app_installations i
    ON i.org_id = r.org_id
   AND i.installation_id = r.installation_id
 WHERE pgr.org_id = $1
   AND pgr.project_id = $2
   AND r.deleted_at IS NULL
   AND i.suspended_at IS NULL
   AND i.deleted_at IS NULL
 ORDER BY lower(r.full_name)
`

type ListActiveProjectGitHubRepositoriesParams struct {
	OrgID     pgtype.UUID `json:"org_id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

type ListActiveProjectGitHubRepositoriesRow struct {
	ProjectGithubRepositoryID pgtype.UUID `json:"project_github_repository_id"`
	InstallationID            int64       `json:"installation_id"`
	GithubRepositoryID        int64       `json:"github_repository_id"`
	FullName                  string      `json:"full_name"`
	RepositoryName            string      `json:"repository_name"`
}

func (q *Queries) ListActiveProjectGitHubRepositories(ctx context.Context, arg ListActiveProjectGitHubRepositoriesParams) ([]ListActiveProjectGitHubRepositoriesRow, error) {
	rows, err := q.db.Query(ctx, listActiveProjectGitHubRepositories, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveProjectGitHubRepositoriesRow
	for rows.Next() {
		var i ListActiveProjectGitHubRepositoriesRow
		if err := rows.Scan(
			&i.ProjectGithubRepositoryID,
			&i.InstallationID,
			&i.GithubRepositoryID,
			&i.FullName,
			&i.RepositoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
