// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) (int64, error)
	ActivateWorkerHost(ctx context.Context, arg ActivateWorkerHostParams) (WorkerHost, error)
	AppendDeploymentEvent(ctx context.Context, arg AppendDeploymentEventParams) (int64, error)
	ApproveDeviceCode(ctx context.Context, arg ApproveDeviceCodeParams) (DeviceCode, error)
	// Each dependent stage locks one supply row before the next, matching runtime
	// admission and lifecycle operations. A joined FOR UPDATE does not guarantee order.
	AuthenticateWorkerHostSecret(ctx context.Context, arg AuthenticateWorkerHostSecretParams) (AuthenticateWorkerHostSecretRow, error)
	AuthorizeActivatingWorkerHostSecret(ctx context.Context, arg AuthorizeActivatingWorkerHostSecretParams) (AuthorizeActivatingWorkerHostSecretRow, error)
	AuthorizeRecoveringWorkerHostSecret(ctx context.Context, arg AuthorizeRecoveringWorkerHostSecretParams) (AuthorizeRecoveringWorkerHostSecretRow, error)
	AuthorizeWorkerDrainReplay(ctx context.Context, arg AuthorizeWorkerDrainReplayParams) (AuthorizeWorkerDrainReplayRow, error)
	AuthorizeWorkerFenceReplay(ctx context.Context, arg AuthorizeWorkerFenceReplayParams) (AuthorizeWorkerFenceReplayRow, error)
	AuthorizeWorkerHostSecret(ctx context.Context, arg AuthorizeWorkerHostSecretParams) (AuthorizeWorkerHostSecretRow, error)
	// The data-modifying CTE always runs in the same statement. Certification does
	// not depend on its inserted row count: every inherited key may already be direct.
	CertifyComputerObject(ctx context.Context, arg CertifyComputerObjectParams) (int64, error)
	ClaimControlOutbox(ctx context.Context, arg ClaimControlOutboxParams) ([]ControlOutbox, error)
	ClaimEventIngestBatch(ctx context.Context, arg ClaimEventIngestBatchParams) ([]ClaimEventIngestBatchRow, error)
	ClaimLiveTelemetryOutbox(ctx context.Context, arg ClaimLiveTelemetryOutboxParams) ([]ClaimLiveTelemetryOutboxRow, error)
	// Claim only scheduling responsibility, not permission to adopt the digest.
	// A crashed sweeper becomes eligible again; repeated deletion is idempotent.
	ClaimRetiredCasBlobs(ctx context.Context, rowLimit int32) ([]string, error)
	// Retained upload IDs get independent, fair retry scheduling. Historical IDs
	// must not monopolize the digest's deadline or starve completed-version cleanup.
	ClaimRetiredCasUploads(ctx context.Context, arg ClaimRetiredCasUploadsParams) ([]string, error)
	CompletePlatformRetryKey(ctx context.Context, arg CompletePlatformRetryKeyParams) (PlatformRetryKey, error)
	CompleteWorkerDrain(ctx context.Context, arg CompleteWorkerDrainParams) (CompleteWorkerDrainRow, error)
	// Physical Computer closure is recorded before this supply acknowledgement.
	// Quarantined allocations remain unfenced and continue blocking activation.
	CompleteWorkerStartupRecovery(ctx context.Context, arg CompleteWorkerStartupRecoveryParams) (WorkerHost, error)
	ConfirmWorkerHostProviderAbsent(ctx context.Context, workerHostID pgtype.UUID) (ConfirmWorkerHostProviderAbsentRow, error)
	ConsumeDeviceCode(ctx context.Context, deviceCodeHash []byte) (DeviceCode, error)
	ConsumeMagicLink(ctx context.Context, arg ConsumeMagicLinkParams) (int64, error)
	ControlOutboxLifecycle(ctx context.Context, deadLetterLimit int64) (ControlOutboxLifecycleRow, error)
	CountOrganizations(ctx context.Context) (int64, error)
	CountReadyWorkerPoolHosts(ctx context.Context, arg CountReadyWorkerPoolHostsParams) (int64, error)
	CountRecentMagicLinks(ctx context.Context, arg CountRecentMagicLinksParams) (int64, error)
	CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error)
	CreateComputerCommand(ctx context.Context, arg CreateComputerCommandParams) (ComputerCommand, error)
	CreateControlOutbox(ctx context.Context, arg CreateControlOutboxParams) (ControlOutbox, error)
	CreateDeviceCode(ctx context.Context, arg CreateDeviceCodeParams) (DeviceCode, error)
	CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error)
	CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) (MagicLink, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreatePendingWorkerPool(ctx context.Context, arg CreatePendingWorkerPoolParams) (WorkerPool, error)
	CreatePlatformRetryKey(ctx context.Context, arg CreatePlatformRetryKeyParams) (PlatformRetryKey, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProjectWithDefaultEnvironment(ctx context.Context, arg CreateProjectWithDefaultEnvironmentParams) (CreateProjectWithDefaultEnvironmentRow, error)
	CreateRegion(ctx context.Context, arg CreateRegionParams) (Region, error)
	CreateSecret(ctx context.Context, arg CreateSecretParams) (CreateSecretRow, error)
	CreateWorkerGroup(ctx context.Context, arg CreateWorkerGroupParams) (WorkerGroup, error)
	DeadLetterControlOutbox(ctx context.Context, arg DeadLetterControlOutboxParams) (ControlOutbox, error)
	DeadLetterUnsupportedControlOutbox(ctx context.Context, arg DeadLetterUnsupportedControlOutboxParams) ([]ControlOutbox, error)
	DeliverControlOutbox(ctx context.Context, arg DeliverControlOutboxParams) (ControlOutbox, error)
	DenyDeviceCode(ctx context.Context, arg DenyDeviceCodeParams) (DeviceCode, error)
	DisableOrgMemberAndRevokeOrgSessions(ctx context.Context, arg DisableOrgMemberAndRevokeOrgSessionsParams) (DisableOrgMemberAndRevokeOrgSessionsRow, error)
	DrainWorkerHost(ctx context.Context, arg DrainWorkerHostParams) (DrainWorkerHostRow, error)
	// EnrollHost owns the deciding authority locks and physical-custody exclusion.
	EnrollWorkerHost(ctx context.Context, arg EnrollWorkerHostParams) (EnrollWorkerHostRow, error)
	EnsureOrgMember(ctx context.Context, arg EnsureOrgMemberParams) (OrgMember, error)
	EnsureRegion(ctx context.Context, arg EnsureRegionParams) error
	FenceWorkerHost(ctx context.Context, arg FenceWorkerHostParams) (FenceWorkerHostRow, error)
	GetActiveInvitation(ctx context.Context, tokenHash []byte) (GetActiveInvitationRow, error)
	GetActiveInvitationByID(ctx context.Context, id pgtype.UUID) (GetActiveInvitationByIDRow, error)
	GetActiveMagicLinkByTokenHash(ctx context.Context, tokenHash []byte) (GetActiveMagicLinkByTokenHashRow, error)
	GetAuthSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetAuthSessionByTokenHashRow, error)
	GetCapacityWorkerHost(ctx context.Context, workerHostID pgtype.UUID) (GetCapacityWorkerHostRow, error)
	GetCasObject(ctx context.Context, arg GetCasObjectParams) (CasObject, error)
	GetCommand(ctx context.Context, arg GetCommandParams) (ComputerCommand, error)
	GetCommandLogState(ctx context.Context, arg GetCommandLogStateParams) (ComputerCommand, error)
	GetComputerCommandByRetryKey(ctx context.Context, arg GetComputerCommandByRetryKeyParams) (ComputerCommand, error)
	GetComputerCommandTarget(ctx context.Context, arg GetComputerCommandTargetParams) (GetComputerCommandTargetRow, error)
	GetCurrentSecretValue(ctx context.Context, arg GetCurrentSecretValueParams) (SecretVersion, error)
	GetDeviceCodeByUserCodeHash(ctx context.Context, userCodeHash []byte) (DeviceCode, error)
	GetDeviceCodeForPoll(ctx context.Context, deviceCodeHash []byte) (DeviceCode, error)
	GetEnvironment(ctx context.Context, arg GetEnvironmentParams) (Environment, error)
	GetOrgMemberForManagement(ctx context.Context, arg GetOrgMemberForManagementParams) (GetOrgMemberForManagementRow, error)
	GetPendingInvitationByEmail(ctx context.Context, arg GetPendingInvitationByEmailParams) (GetPendingInvitationByEmailRow, error)
	GetPlatformRetryKey(ctx context.Context, arg GetPlatformRetryKeyParams) (PlatformRetryKey, error)
	GetProject(ctx context.Context, arg GetProjectParams) (Project, error)
	GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error)
	GetRegion(ctx context.Context, id string) (Region, error)
	GetRevocableInvitation(ctx context.Context, arg GetRevocableInvitationParams) (GetRevocableInvitationRow, error)
	GetScheduleByID(ctx context.Context, arg GetScheduleByIDParams) (AgentSchedule, error)
	GetSecret(ctx context.Context, arg GetSecretParams) (Secret, error)
	GetSecretSnapshot(ctx context.Context, arg GetSecretSnapshotParams) (GetSecretSnapshotRow, error)
	GetSecretSnapshotByName(ctx context.Context, arg GetSecretSnapshotByNameParams) (GetSecretSnapshotByNameRow, error)
	GetSecretVersion(ctx context.Context, arg GetSecretVersionParams) (SecretVersion, error)
	GetTelemetryOutboxLifecycle(ctx context.Context, retainFor pgtype.Interval) (GetTelemetryOutboxLifecycleRow, error)
	GetUserOnboardingState(ctx context.Context, arg GetUserOnboardingStateParams) (GetUserOnboardingStateRow, error)
	GetWorkerGroup(ctx context.Context, id pgtype.UUID) (WorkerGroup, error)
	GetWorkerGroupByRegionName(ctx context.Context, arg GetWorkerGroupByRegionNameParams) (WorkerGroup, error)
	GetWorkerGroupStatus(ctx context.Context, workerGroupID pgtype.UUID) (GetWorkerGroupStatusRow, error)
	GetWorkerHostPoolID(ctx context.Context, arg GetWorkerHostPoolIDParams) (pgtype.UUID, error)
	GetWorkerHostStatus(ctx context.Context, arg GetWorkerHostStatusParams) (GetWorkerHostStatusRow, error)
	GetWorkerHostStatusByResource(ctx context.Context, arg GetWorkerHostStatusByResourceParams) (GetWorkerHostStatusByResourceRow, error)
	GetWorkerPoolByGroupName(ctx context.Context, arg GetWorkerPoolByGroupNameParams) (WorkerPool, error)
	GrantUserAdmin(ctx context.Context, userID pgtype.UUID) error
	InsertWorkerPoolCPUShape(ctx context.Context, arg InsertWorkerPoolCPUShapeParams) (int64, error)
	IssueAPIKey(ctx context.Context, arg IssueAPIKeyParams) (APIKey, error)
	ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]ListAPIKeysRow, error)
	// Only abandoned uploads are retirement candidates. Memberships in any org and
	// registered owners pin availability with FKs; these NOT EXISTS clauses avoid
	// routine conflicts but are not the concurrency barrier.
	ListAbandonedCasBlobs(ctx context.Context, rowLimit int32) ([]string, error)
	// Physical reservations retain their pools independently of the queued demand budget.
	ListAllocationPlanningChargedPools(ctx context.Context, workerGroupID pgtype.UUID) ([]pgtype.UUID, error)
	// Planning counts physical Computer/preparation demand once. Session processes
	// and Commands on a resident Computer consume its existing allocation.
	ListAllocationPlanningDemand(ctx context.Context, arg ListAllocationPlanningDemandParams) ([]ListAllocationPlanningDemandRow, error)
	ListCapacityWorkerHosts(ctx context.Context, arg ListCapacityWorkerHostsParams) ([]ListCapacityWorkerHostsRow, error)
	ListCapacityWorkerPools(ctx context.Context, arg ListCapacityWorkerPoolsParams) ([]ListCapacityWorkerPoolsRow, error)
	ListEnvironments(ctx context.Context, arg ListEnvironmentsParams) ([]Environment, error)
	ListInvitations(ctx context.Context, arg ListInvitationsParams) ([]ListInvitationsRow, error)
	ListOrgMembers(ctx context.Context, orgID pgtype.UUID) ([]ListOrgMembersRow, error)
	ListOrganizationIDs(ctx context.Context, rowLimit int32) ([]pgtype.UUID, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	ListRegions(ctx context.Context) ([]Region, error)
	ListRetiredCasUploads(ctx context.Context, digest string) ([]string, error)
	ListSchedules(ctx context.Context, arg ListSchedulesParams) ([]AgentSchedule, error)
	ListSecrets(ctx context.Context, arg ListSecretsParams) ([]ListSecretsRow, error)
	ListStaleWorkerFenceCandidates(ctx context.Context, arg ListStaleWorkerFenceCandidatesParams) ([]ListStaleWorkerFenceCandidatesRow, error)
	ListWorkerCapacityBins(ctx context.Context, arg ListWorkerCapacityBinsParams) ([]ListWorkerCapacityBinsRow, error)
	ListWorkerGroupRetainedProfiles(ctx context.Context, arg ListWorkerGroupRetainedProfilesParams) ([]ListWorkerGroupRetainedProfilesRow, error)
	ListWorkerGroups(ctx context.Context, arg ListWorkerGroupsParams) ([]WorkerGroup, error)
	ListWorkerPoolCPUShapes(ctx context.Context, workerPoolID pgtype.UUID) ([]WorkerPoolCpuShape, error)
	ListWorkerPools(ctx context.Context, workerGroupID pgtype.UUID) ([]WorkerPool, error)
	LockComputerCommand(ctx context.Context, arg LockComputerCommandParams) (ComputerCommand, error)
	LockComputerObject(ctx context.Context, arg LockComputerObjectParams) (ComputerObject, error)
	LockMagicLinkRecipient(ctx context.Context, lockKey int64) error
	LockOrganizationForProjectDefaults(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	LockOrganizationsForSelfHostedSetup(ctx context.Context) error
	LockPlatformRetryKey(ctx context.Context, arg LockPlatformRetryKeyParams) (LockPlatformRetryKeyRow, error)
	// Worker Host fence for dispatch and Computer preparation. The caller
	// (workergroup.LockDispatchSupply) must already hold the Worker Group and Pool share
	// locks and have validated their status. This query locks the Worker Host and
	// checks epoch, observation freshness and platform. Admission also requires an
	// active host without a Run pause; continuation of admitted work accepts a
	// draining host and ignores pauses. admitting reports whether the locked host
	// could admit new work, including the VM pause.
	LockRunEligibleWorkerHost(ctx context.Context, arg LockRunEligibleWorkerHostParams) (bool, error)
	LockWorkerDrainCompletion(ctx context.Context, arg LockWorkerDrainCompletionParams) (LockWorkerDrainCompletionRow, error)
	LockWorkerGroupCreationRegion(ctx context.Context, lockKey int64) error
	LockWorkerGroupForPoolMutation(ctx context.Context, workerGroupID pgtype.UUID) (WorkerGroup, error)
	LockWorkerGroupMutation(ctx context.Context, lockKey int64) error
	LockWorkerHostForActivation(ctx context.Context, arg LockWorkerHostForActivationParams) (WorkerHost, error)
	LockWorkerPool(ctx context.Context, arg LockWorkerPoolParams) (WorkerPool, error)
	LockWorkerPoolActiveHosts(ctx context.Context, arg LockWorkerPoolActiveHostsParams) ([]pgtype.UUID, error)
	MarkLiveTelemetryOutboxBatchFailed(ctx context.Context, arg MarkLiveTelemetryOutboxBatchFailedParams) (int64, error)
	MarkLiveTelemetryOutboxBatchPublished(ctx context.Context, arg MarkLiveTelemetryOutboxBatchPublishedParams) (int64, error)
	MarkMagicLinkDeliveryFailed(ctx context.Context, id pgtype.UUID) (int64, error)
	MarkMagicLinkSent(ctx context.Context, id pgtype.UUID) (int64, error)
	MarkTelemetryOutboxBatchFailed(ctx context.Context, arg MarkTelemetryOutboxBatchFailedParams) (int64, error)
	MarkTelemetryOutboxWritten(ctx context.Context, arg MarkTelemetryOutboxWrittenParams) (int64, error)
	MarkWorkerHostLost(ctx context.Context, arg MarkWorkerHostLostParams) (MarkWorkerHostLostRow, error)
	PruneDeliveredControlOutbox(ctx context.Context, arg PruneDeliveredControlOutboxParams) (int64, error)
	PruneExpiredComputerCommandResults(ctx context.Context, rowLimit int32) (int64, error)
	PruneExpiredPlatformRetryReceipts(ctx context.Context, rowLimit int32) (int64, error)
	PruneTelemetryOutboxWritten(ctx context.Context, arg PruneTelemetryOutboxWrittenParams) (int64, error)
	// Host loss revokes credentials without confirming physical absence.
	// Allocation owners reconcile logical state; only confirmed stop releases custody.
	RecheckAndFenceStaleWorkerHost(ctx context.Context, arg RecheckAndFenceStaleWorkerHostParams) (RecheckAndFenceStaleWorkerHostRow, error)
	RecordCasBlobReclamation(ctx context.Context, arg RecordCasBlobReclamationParams) error
	RecordWorkerObservation(ctx context.Context, arg RecordWorkerObservationParams) (WorkerHost, error)
	RefreshAuthSession(ctx context.Context, arg RefreshAuthSessionParams) error
	RegisterRetiredCasUpload(ctx context.Context, arg RegisterRetiredCasUploadParams) error
	RequestComputerCommandCancellation(ctx context.Context, arg RequestComputerCommandCancellationParams) (ComputerCommand, error)
	RetainComputerDiskRoot(ctx context.Context, arg RetainComputerDiskRootParams) (pgtype.UUID, error)
	// Commit before making any remote calls. Never clear retired_at or remove this
	// row: an in-flight upload can finish after a successful empty sweep.
	RetireAbandonedCasBlob(ctx context.Context, digest string) (int64, error)
	RetryControlOutbox(ctx context.Context, arg RetryControlOutboxParams) (ControlOutbox, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error)
	RevokeAuthSessionByTokenHash(ctx context.Context, tokenHash []byte) (int64, error)
	RevokeAuthSessionsForUser(ctx context.Context, userID pgtype.UUID) (int64, error)
	RevokeExpiredInvitationsByEmail(ctx context.Context, arg RevokeExpiredInvitationsByEmailParams) (int64, error)
	RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (int64, error)
	RevokeOpenMagicLinksForRecipient(ctx context.Context, arg RevokeOpenMagicLinksForRecipientParams) (int64, error)
	RevokeSecret(ctx context.Context, arg RevokeSecretParams) (Secret, error)
	RotateSecret(ctx context.Context, arg RotateSecretParams) (Secret, error)
	RotateWorkerGroupToken(ctx context.Context, arg RotateWorkerGroupTokenParams) (WorkerGroupToken, error)
	SealWorkerPool(ctx context.Context, arg SealWorkerPoolParams) (WorkerPool, error)
	SetInitialWorkerGroupPrimaryPool(ctx context.Context, arg SetInitialWorkerGroupPrimaryPoolParams) (WorkerGroup, error)
	SetWorkerGroupPrimaryPool(ctx context.Context, arg SetWorkerGroupPrimaryPoolParams) (WorkerGroup, error)
	TouchActiveAPIKeyByTokenHash(ctx context.Context, tokenHash []byte) (TouchActiveAPIKeyByTokenHashRow, error)
	TransitionWorkerGroupStatus(ctx context.Context, arg TransitionWorkerGroupStatusParams) (TransitionWorkerGroupStatusRow, error)
	TransitionWorkerPoolLifecycle(ctx context.Context, arg TransitionWorkerPoolLifecycleParams) (WorkerPool, error)
	UpdateEnvironmentDetails(ctx context.Context, arg UpdateEnvironmentDetailsParams) (Environment, error)
	UpdateOrgMemberRole(ctx context.Context, arg UpdateOrgMemberRoleParams) (OrgMember, error)
	UpdateProjectDetails(ctx context.Context, arg UpdateProjectDetailsParams) (Project, error)
	UpdateRegionMetadata(ctx context.Context, arg UpdateRegionMetadataParams) (Region, error)
	UpdateWorkerGroupDescription(ctx context.Context, arg UpdateWorkerGroupDescriptionParams) (WorkerGroup, error)
	UpsertAuthIdentity(ctx context.Context, arg UpsertAuthIdentityParams) (UpsertAuthIdentityRow, error)
	UpsertCasObject(ctx context.Context, arg UpsertCasObjectParams) (CasObject, error)
	UpsertMagicLinkAuthIdentity(ctx context.Context, arg UpsertMagicLinkAuthIdentityParams) (UpsertMagicLinkAuthIdentityRow, error)
	UpsertVMPlatform(ctx context.Context, arg UpsertVMPlatformParams) (VMPlatform, error)
}

var _ Querier = (*Queries)(nil)
