// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: regions.sql

package db

import (
	"context"
)

const ensureRegion = `-- name: EnsureRegion :one
INSERT INTO regions (id, provider, provider_region, display_name, state, visibility, location, static_ips)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5::region_state,
    $6::region_visibility,
    $7,
    $8::text[]
)
ON CONFLICT (id) DO UPDATE
   SET provider = EXCLUDED.provider,
       provider_region = EXCLUDED.provider_region,
       display_name = EXCLUDED.display_name
RETURNING id, provider, provider_region, display_name, state, visibility, location, static_ips, created_at, updated_at
`

type EnsureRegionParams struct {
	ID             string           `json:"id"`
	Provider       string           `json:"provider"`
	ProviderRegion string           `json:"provider_region"`
	DisplayName    string           `json:"display_name"`
	State          RegionState      `json:"state"`
	Visibility     RegionVisibility `json:"visibility"`
	Location       string           `json:"location"`
	StaticIps      []string         `json:"static_ips"`
}

func (q *Queries) EnsureRegion(ctx context.Context, arg EnsureRegionParams) (Region, error) {
	row := q.db.QueryRow(ctx, ensureRegion,
		arg.ID,
		arg.Provider,
		arg.ProviderRegion,
		arg.DisplayName,
		arg.State,
		arg.Visibility,
		arg.Location,
		arg.StaticIps,
	)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderRegion,
		&i.DisplayName,
		&i.State,
		&i.Visibility,
		&i.Location,
		&i.StaticIps,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegion = `-- name: GetRegion :one
SELECT id, provider, provider_region, display_name, state, visibility, location, static_ips, created_at, updated_at
  FROM regions
 WHERE id = $1
`

func (q *Queries) GetRegion(ctx context.Context, id string) (Region, error) {
	row := q.db.QueryRow(ctx, getRegion, id)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderRegion,
		&i.DisplayName,
		&i.State,
		&i.Visibility,
		&i.Location,
		&i.StaticIps,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRegions = `-- name: ListRegions :many
SELECT id, provider, provider_region, display_name, state, visibility, location, static_ips, created_at, updated_at
  FROM regions
 ORDER BY lower(display_name), id
`

func (q *Queries) ListRegions(ctx context.Context) ([]Region, error) {
	rows, err := q.db.Query(ctx, listRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Region
	for rows.Next() {
		var i Region
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ProviderRegion,
			&i.DisplayName,
			&i.State,
			&i.Visibility,
			&i.Location,
			&i.StaticIps,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
