// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: run_waits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelRunWait = `-- name: CancelRunWait :one
UPDATE run_waits
   SET state = 'cancelled',
       cancelled_at = COALESCE(run_waits.cancelled_at, now()),
       updated_at = now()
 WHERE org_id = $1
   AND id = $2
   AND state = 'checkpointed_waiting'
RETURNING id, public_id, org_id, worker_group_id, project_id, environment_id, run_id, kind, correlation_id, state, timeout_at, runtime_checkpoint_due_at, runtime_checkpoint_started_at, live_wait_started_at, owner_runtime_instance_id, owner_runtime_epoch, owner_run_id, owner_run_lease_id, owner_run_state_version, owner_worker_instance_id, runtime_checkpoint_id, workspace_version_id, active_elapsed_ms_at_park, parked_at, resolved_at, resuming_at, resumed_at, cancelled_at, created_at, updated_at
`

type CancelRunWaitParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) CancelRunWait(ctx context.Context, arg CancelRunWaitParams) (RunWait, error) {
	row := q.db.QueryRow(ctx, cancelRunWait, arg.OrgID, arg.ID)
	var i RunWait
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.WorkerGroupID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.RunID,
		&i.Kind,
		&i.CorrelationID,
		&i.State,
		&i.TimeoutAt,
		&i.RuntimeCheckpointDueAt,
		&i.RuntimeCheckpointStartedAt,
		&i.LiveWaitStartedAt,
		&i.OwnerRuntimeInstanceID,
		&i.OwnerRuntimeEpoch,
		&i.OwnerRunID,
		&i.OwnerRunLeaseID,
		&i.OwnerRunStateVersion,
		&i.OwnerWorkerInstanceID,
		&i.RuntimeCheckpointID,
		&i.WorkspaceVersionID,
		&i.ActiveElapsedMsAtPark,
		&i.ParkedAt,
		&i.ResolvedAt,
		&i.ResumingAt,
		&i.ResumedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelRunWaitsForRun = `-- name: CancelRunWaitsForRun :many
UPDATE run_waits
   SET state = 'cancelled',
       cancelled_at = COALESCE(run_waits.cancelled_at, now()),
       updated_at = now()
 WHERE org_id = $1
   AND run_id = $2
   AND state = 'checkpointed_waiting'
RETURNING id, public_id, org_id, worker_group_id, project_id, environment_id, run_id, kind, correlation_id, state, timeout_at, runtime_checkpoint_due_at, runtime_checkpoint_started_at, live_wait_started_at, owner_runtime_instance_id, owner_runtime_epoch, owner_run_id, owner_run_lease_id, owner_run_state_version, owner_worker_instance_id, runtime_checkpoint_id, workspace_version_id, active_elapsed_ms_at_park, parked_at, resolved_at, resuming_at, resumed_at, cancelled_at, created_at, updated_at
`

type CancelRunWaitsForRunParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	RunID pgtype.UUID `json:"run_id"`
}

func (q *Queries) CancelRunWaitsForRun(ctx context.Context, arg CancelRunWaitsForRunParams) ([]RunWait, error) {
	rows, err := q.db.Query(ctx, cancelRunWaitsForRun, arg.OrgID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunWait
	for rows.Next() {
		var i RunWait
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrgID,
			&i.WorkerGroupID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.RunID,
			&i.Kind,
			&i.CorrelationID,
			&i.State,
			&i.TimeoutAt,
			&i.RuntimeCheckpointDueAt,
			&i.RuntimeCheckpointStartedAt,
			&i.LiveWaitStartedAt,
			&i.OwnerRuntimeInstanceID,
			&i.OwnerRuntimeEpoch,
			&i.OwnerRunID,
			&i.OwnerRunLeaseID,
			&i.OwnerRunStateVersion,
			&i.OwnerWorkerInstanceID,
			&i.RuntimeCheckpointID,
			&i.WorkspaceVersionID,
			&i.ActiveElapsedMsAtPark,
			&i.ParkedAt,
			&i.ResolvedAt,
			&i.ResumingAt,
			&i.ResumedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimRuntimeCheckpointWait = `-- name: ClaimRuntimeCheckpointWait :one
WITH scope AS (
    SELECT run_waits.id, run_waits.public_id, run_waits.org_id, run_waits.worker_group_id, run_waits.project_id, run_waits.environment_id, run_waits.run_id, run_waits.kind, run_waits.correlation_id, run_waits.state, run_waits.timeout_at, run_waits.runtime_checkpoint_due_at, run_waits.runtime_checkpoint_started_at, run_waits.live_wait_started_at, run_waits.owner_runtime_instance_id, run_waits.owner_runtime_epoch, run_waits.owner_run_id, run_waits.owner_run_lease_id, run_waits.owner_run_state_version, run_waits.owner_worker_instance_id, run_waits.runtime_checkpoint_id, run_waits.workspace_version_id, run_waits.active_elapsed_ms_at_park, run_waits.parked_at, run_waits.resolved_at, run_waits.resuming_at, run_waits.resumed_at, run_waits.cancelled_at, run_waits.created_at, run_waits.updated_at,
           runs.workspace_id,
           workspace_leases.id AS workspace_lease_id,
           workspace_leases.workspace_mount_id,
           workspace_mounts.runtime_instance_id,
           workspace_mounts.dirty_generation,
           workspaces.current_version_id AS current_workspace_version_id,
           worker_instances.runtime_id,
           worker_instances.runtime_arch,
           worker_instances.runtime_abi,
           worker_instances.kernel_digest,
           worker_instances.initramfs_digest,
           worker_instances.rootfs_digest,
           worker_instances.cni_profile,
           runtime_instances.runtime_key_hash
      FROM run_waits
      JOIN runs ON runs.org_id = run_waits.org_id
               AND runs.project_id = run_waits.project_id
               AND runs.environment_id = run_waits.environment_id
               AND runs.id = run_waits.run_id
      JOIN workspaces ON workspaces.org_id = runs.org_id
                     AND workspaces.project_id = runs.project_id
                     AND workspaces.environment_id = runs.environment_id
                     AND workspaces.id = runs.workspace_id
      JOIN run_leases ON run_leases.org_id = run_waits.org_id
                     AND run_leases.run_id = run_waits.run_id
                     AND run_leases.id = run_waits.owner_run_lease_id
      JOIN worker_instances ON worker_instances.id = run_leases.worker_instance_id
                           AND worker_instances.runtime_id <> ''
                           AND worker_instances.runtime_arch <> ''
                           AND worker_instances.runtime_abi <> ''
                           AND worker_instances.kernel_digest <> ''
                           AND worker_instances.initramfs_digest <> ''
                           AND worker_instances.rootfs_digest <> ''
                           AND worker_instances.cni_profile <> ''
      JOIN workspace_leases ON workspace_leases.org_id = runs.org_id
                           AND workspace_leases.project_id = runs.project_id
                           AND workspace_leases.environment_id = runs.environment_id
                           AND workspace_leases.workspace_id = runs.workspace_id
                           AND workspace_leases.owner_run_id = runs.id
                           AND workspace_leases.lease_kind = 'write'
                           AND workspace_leases.state = 'active'
                           AND workspace_leases.released_at IS NULL
                           AND workspace_leases.expires_at > now()
      JOIN workspace_mounts ON workspace_mounts.org_id = workspace_leases.org_id
                                     AND workspace_mounts.project_id = workspace_leases.project_id
                                     AND workspace_mounts.environment_id = workspace_leases.environment_id
                                     AND workspace_mounts.workspace_id = workspace_leases.workspace_id
                                     AND workspace_mounts.id = workspace_leases.workspace_mount_id
      JOIN runtime_instances
        ON runtime_instances.org_id = workspace_mounts.org_id
       AND runtime_instances.id = workspace_mounts.runtime_instance_id
       AND runtime_instances.worker_instance_id = run_waits.owner_worker_instance_id
       AND runtime_instances.id = run_waits.owner_runtime_instance_id
       AND runtime_instances.runtime_epoch = run_waits.owner_runtime_epoch
       AND runtime_instances.owner_run_id = run_waits.run_id
       AND runtime_instances.owner_run_lease_id = run_waits.owner_run_lease_id
       AND runtime_instances.owner_run_wait_id = run_waits.id
       AND runtime_instances.owner_run_state_version = run_waits.owner_run_state_version
       AND runtime_instances.workspace_mount_id = workspace_mounts.id
       AND runtime_instances.state IN ('waiting_hot', 'checkpointing')
     WHERE run_waits.org_id = $1
       AND run_waits.project_id = $2
       AND run_waits.environment_id = $3
       AND run_waits.run_id = $4
       AND run_waits.id = $5
       AND run_waits.owner_run_lease_id = $6
       AND run_waits.owner_worker_instance_id = $7
       AND run_waits.state IN ('live_waiting', 'checkpointing')
       AND runs.status = 'running'
       AND runs.current_run_lease_id = $6
       AND run_leases.worker_instance_id = $7
       AND run_leases.status IN ('leased', 'running')
       AND run_leases.lease_expires_at > now()
     FOR UPDATE OF run_waits, runs, workspace_leases, workspace_mounts, runtime_instances
),
claimed_checkpoint AS (
    INSERT INTO runtime_checkpoints (
        id,
        org_id,
        worker_group_id,
        project_id,
        environment_id,
        workspace_id,
        run_id,
        source_workspace_lease_id,
        workspace_mount_id,
        base_workspace_version_id,
        state,
        runtime_backend,
        runtime_id,
        runtime_arch,
        runtime_abi,
        kernel_digest,
        initramfs_digest,
        rootfs_digest,
        runtime_config_digest,
        owner_runtime_instance_id,
        owner_runtime_epoch,
        owner_run_id,
        owner_run_wait_id,
        owner_run_lease_id,
        owner_worker_instance_id,
        source_worker_instance_id,
        cni_profile,
        manifest,
        creation_expires_at
    )
    SELECT $8,
           scope.org_id,
           scope.worker_group_id,
           scope.project_id,
           scope.environment_id,
           scope.workspace_id,
           scope.run_id,
           scope.workspace_lease_id,
           scope.workspace_mount_id,
           COALESCE(scope.workspace_version_id, scope.current_workspace_version_id),
           'creating',
           'firecracker',
           scope.runtime_id,
           scope.runtime_arch,
           scope.runtime_abi,
           scope.kernel_digest,
           scope.initramfs_digest,
           scope.rootfs_digest,
           scope.runtime_key_hash,
           scope.owner_runtime_instance_id,
           scope.owner_runtime_epoch,
           scope.run_id,
           scope.id,
           scope.owner_run_lease_id,
           scope.owner_worker_instance_id,
           scope.owner_worker_instance_id,
           scope.cni_profile,
           '{}'::jsonb,
           scope.runtime_checkpoint_due_at + interval '5 minutes'
      FROM scope
     WHERE scope.state = 'live_waiting'
       AND COALESCE(scope.workspace_version_id, scope.current_workspace_version_id) IS NOT NULL
    ON CONFLICT (id) DO NOTHING
    RETURNING id, org_id, worker_group_id, project_id, environment_id, workspace_id, run_id, source_workspace_lease_id, workspace_mount_id, base_workspace_version_id, state, runtime_backend, runtime_id, runtime_arch, runtime_abi, kernel_digest, initramfs_digest, rootfs_digest, runtime_config_digest, owner_runtime_instance_id, owner_runtime_epoch, owner_run_id, owner_run_wait_id, owner_run_lease_id, owner_worker_instance_id, source_worker_instance_id, substrate_digest, runtime_substrate_artifact_id, runtime_vcpus, runtime_memory_mib, runtime_scratch_disk_mib, cni_profile, image_key, manifest, error_message, expires_at, creation_started_at, creation_expires_at, created_at, ready_at, invalidated_at
),
claimed_wait AS (
    UPDATE run_waits
       SET state = 'checkpointing',
           runtime_checkpoint_started_at = COALESCE(run_waits.runtime_checkpoint_started_at, now()),
           runtime_checkpoint_id = $8,
           updated_at = now()
      FROM scope
     WHERE run_waits.org_id = scope.org_id
       AND run_waits.id = scope.id
       AND scope.state = 'live_waiting'
       AND EXISTS (SELECT 1 FROM claimed_checkpoint)
    RETURNING run_waits.id, run_waits.public_id, run_waits.org_id, run_waits.worker_group_id, run_waits.project_id, run_waits.environment_id, run_waits.run_id, run_waits.kind, run_waits.correlation_id, run_waits.state, run_waits.timeout_at, run_waits.runtime_checkpoint_due_at, run_waits.runtime_checkpoint_started_at, run_waits.live_wait_started_at, run_waits.owner_runtime_instance_id, run_waits.owner_runtime_epoch, run_waits.owner_run_id, run_waits.owner_run_lease_id, run_waits.owner_run_state_version, run_waits.owner_worker_instance_id, run_waits.runtime_checkpoint_id, run_waits.workspace_version_id, run_waits.active_elapsed_ms_at_park, run_waits.parked_at, run_waits.resolved_at, run_waits.resuming_at, run_waits.resumed_at, run_waits.cancelled_at, run_waits.created_at, run_waits.updated_at
),
selected_wait AS (
    SELECT claimed_wait.id, claimed_wait.public_id, claimed_wait.org_id, claimed_wait.worker_group_id, claimed_wait.project_id, claimed_wait.environment_id, claimed_wait.run_id, claimed_wait.kind, claimed_wait.correlation_id, claimed_wait.state, claimed_wait.timeout_at, claimed_wait.runtime_checkpoint_due_at, claimed_wait.runtime_checkpoint_started_at, claimed_wait.live_wait_started_at, claimed_wait.owner_runtime_instance_id, claimed_wait.owner_runtime_epoch, claimed_wait.owner_run_id, claimed_wait.owner_run_lease_id, claimed_wait.owner_run_state_version, claimed_wait.owner_worker_instance_id, claimed_wait.runtime_checkpoint_id, claimed_wait.workspace_version_id, claimed_wait.active_elapsed_ms_at_park, claimed_wait.parked_at, claimed_wait.resolved_at, claimed_wait.resuming_at, claimed_wait.resumed_at, claimed_wait.cancelled_at, claimed_wait.created_at, claimed_wait.updated_at
      FROM claimed_wait
    UNION ALL
    SELECT run_waits.id, run_waits.public_id, run_waits.org_id, run_waits.worker_group_id, run_waits.project_id, run_waits.environment_id, run_waits.run_id, run_waits.kind, run_waits.correlation_id, run_waits.state, run_waits.timeout_at, run_waits.runtime_checkpoint_due_at, run_waits.runtime_checkpoint_started_at, run_waits.live_wait_started_at, run_waits.owner_runtime_instance_id, run_waits.owner_runtime_epoch, run_waits.owner_run_id, run_waits.owner_run_lease_id, run_waits.owner_run_state_version, run_waits.owner_worker_instance_id, run_waits.runtime_checkpoint_id, run_waits.workspace_version_id, run_waits.active_elapsed_ms_at_park, run_waits.parked_at, run_waits.resolved_at, run_waits.resuming_at, run_waits.resumed_at, run_waits.cancelled_at, run_waits.created_at, run_waits.updated_at
      FROM run_waits
      JOIN scope ON scope.org_id = run_waits.org_id
                AND scope.id = run_waits.id
     WHERE scope.state = 'checkpointing'
       AND run_waits.runtime_checkpoint_id IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM claimed_wait)
),
selected_checkpoint AS (
    SELECT claimed_checkpoint.id
      FROM claimed_checkpoint
    UNION ALL
    SELECT runtime_checkpoints.id
      FROM runtime_checkpoints
      JOIN scope ON scope.org_id = runtime_checkpoints.org_id
                AND scope.project_id = runtime_checkpoints.project_id
                AND scope.environment_id = runtime_checkpoints.environment_id
                AND scope.run_id = runtime_checkpoints.run_id
      JOIN selected_wait ON selected_wait.org_id = scope.org_id
                        AND selected_wait.id = scope.id
                        AND selected_wait.runtime_checkpoint_id = runtime_checkpoints.id
     WHERE scope.state = 'checkpointing'
       AND runtime_checkpoints.state = 'creating'
       AND runtime_checkpoints.owner_runtime_instance_id = scope.owner_runtime_instance_id
       AND runtime_checkpoints.owner_runtime_epoch = scope.owner_runtime_epoch
       AND runtime_checkpoints.owner_run_id = scope.run_id
       AND runtime_checkpoints.owner_run_wait_id = scope.id
       AND runtime_checkpoints.owner_run_lease_id = scope.owner_run_lease_id
       AND runtime_checkpoints.owner_worker_instance_id = scope.owner_worker_instance_id
       AND runtime_checkpoints.source_worker_instance_id = scope.owner_worker_instance_id
       AND NOT EXISTS (SELECT 1 FROM claimed_checkpoint)
),
checkpointing_runtime_instance AS (
    UPDATE runtime_instances
       SET state = 'checkpointing',
           owner_run_id = selected_wait.run_id,
           owner_run_lease_id = selected_wait.owner_run_lease_id,
           owner_run_wait_id = selected_wait.id,
           owner_run_state_version = selected_wait.owner_run_state_version,
           checkpointing_at = COALESCE(runtime_instances.checkpointing_at, now()),
           updated_at = now()
      FROM scope, selected_wait
     WHERE runtime_instances.org_id = scope.org_id
       AND runtime_instances.id = scope.runtime_instance_id
       AND runtime_instances.id = scope.owner_runtime_instance_id
       AND runtime_instances.runtime_epoch = scope.owner_runtime_epoch
       AND runtime_instances.owner_run_id = scope.run_id
       AND runtime_instances.owner_run_lease_id = scope.owner_run_lease_id
       AND runtime_instances.owner_run_wait_id = scope.id
       AND runtime_instances.owner_run_state_version = scope.owner_run_state_version
       AND runtime_instances.state IN ('waiting_hot', 'checkpointing')
    RETURNING runtime_instances.id
)
SELECT selected_checkpoint.id AS runtime_checkpoint_id,
       scope.org_id,
       scope.project_id,
       scope.environment_id,
       scope.run_id,
       scope.id AS run_wait_id,
       scope.owner_run_lease_id AS run_lease_id,
       scope.owner_worker_instance_id AS worker_instance_id,
       scope.owner_run_state_version AS run_state_version,
       scope.owner_runtime_instance_id AS runtime_instance_id,
       scope.owner_runtime_epoch AS runtime_epoch,
       scope.workspace_version_id,
       scope.dirty_generation
  FROM scope
  JOIN selected_wait ON selected_wait.org_id = scope.org_id
                    AND selected_wait.id = scope.id
  JOIN selected_checkpoint ON true
  JOIN checkpointing_runtime_instance ON true
 LIMIT 1
`

type ClaimRuntimeCheckpointWaitParams struct {
	OrgID               pgtype.UUID `json:"org_id"`
	ProjectID           pgtype.UUID `json:"project_id"`
	EnvironmentID       pgtype.UUID `json:"environment_id"`
	RunID               pgtype.UUID `json:"run_id"`
	RunWaitID           pgtype.UUID `json:"run_wait_id"`
	RunLeaseID          pgtype.UUID `json:"run_lease_id"`
	WorkerInstanceID    pgtype.UUID `json:"worker_instance_id"`
	RuntimeCheckpointID pgtype.UUID `json:"runtime_checkpoint_id"`
}

type ClaimRuntimeCheckpointWaitRow struct {
	RuntimeCheckpointID pgtype.UUID `json:"runtime_checkpoint_id"`
	OrgID               pgtype.UUID `json:"org_id"`
	ProjectID           pgtype.UUID `json:"project_id"`
	EnvironmentID       pgtype.UUID `json:"environment_id"`
	RunID               pgtype.UUID `json:"run_id"`
	RunWaitID           pgtype.UUID `json:"run_wait_id"`
	RunLeaseID          pgtype.UUID `json:"run_lease_id"`
	WorkerInstanceID    pgtype.UUID `json:"worker_instance_id"`
	RunStateVersion     pgtype.Int8 `json:"run_state_version"`
	RuntimeInstanceID   pgtype.UUID `json:"runtime_instance_id"`
	RuntimeEpoch        pgtype.Int8 `json:"runtime_epoch"`
	WorkspaceVersionID  pgtype.UUID `json:"workspace_version_id"`
	DirtyGeneration     int64       `json:"dirty_generation"`
}

func (q *Queries) ClaimRuntimeCheckpointWait(ctx context.Context, arg ClaimRuntimeCheckpointWaitParams) (ClaimRuntimeCheckpointWaitRow, error) {
	row := q.db.QueryRow(ctx, claimRuntimeCheckpointWait,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.RunID,
		arg.RunWaitID,
		arg.RunLeaseID,
		arg.WorkerInstanceID,
		arg.RuntimeCheckpointID,
	)
	var i ClaimRuntimeCheckpointWaitRow
	err := row.Scan(
		&i.RuntimeCheckpointID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.RunID,
		&i.RunWaitID,
		&i.RunLeaseID,
		&i.WorkerInstanceID,
		&i.RunStateVersion,
		&i.RuntimeInstanceID,
		&i.RuntimeEpoch,
		&i.WorkspaceVersionID,
		&i.DirtyGeneration,
	)
	return i, err
}

const createHotRunWait = `-- name: CreateHotRunWait :one
WITH scope AS MATERIALIZED (
    SELECT runs.org_id,
           runs.worker_group_id,
           runs.project_id,
           runs.environment_id,
           runs.id AS run_id,
           runs.state_version,
           run_leases.id AS run_lease_id,
           run_leases.worker_instance_id,
           workspace_mounts.runtime_instance_id,
           runtime_instances.runtime_epoch
      FROM runs
      JOIN run_leases ON run_leases.org_id = runs.org_id
                     AND run_leases.run_id = runs.id
                     AND run_leases.id = runs.current_run_lease_id
      JOIN workspace_mounts
        ON workspace_mounts.org_id = runs.org_id
       AND workspace_mounts.project_id = runs.project_id
       AND workspace_mounts.environment_id = runs.environment_id
       AND workspace_mounts.id = runs.workspace_mount_id
      JOIN runtime_instances
        ON runtime_instances.org_id = workspace_mounts.org_id
       AND runtime_instances.id = workspace_mounts.runtime_instance_id
       AND runtime_instances.worker_instance_id = run_leases.worker_instance_id
       AND runtime_instances.workspace_mount_id = workspace_mounts.id
       AND runtime_instances.state IN ('running', 'waiting_hot')
     WHERE runs.org_id = $1
       AND runs.project_id = $2
       AND runs.environment_id = $3
       AND runs.id = $4
       AND runs.current_run_lease_id = $5
       AND run_leases.worker_instance_id = $6
       AND runs.status = 'running'
       AND runs.execution_status = 'executing'
       AND run_leases.status IN ('leased', 'running')
       AND run_leases.lease_expires_at > now()
     FOR UPDATE OF runtime_instances
),
inserted_wait AS (
    INSERT INTO run_waits (
        id,
        public_id,
        org_id,
        worker_group_id,
        project_id,
        environment_id,
        run_id,
        kind,
        correlation_id,
        state,
        timeout_at,
        runtime_checkpoint_due_at,
        live_wait_started_at,
        owner_runtime_instance_id,
        owner_runtime_epoch,
        owner_run_id,
        owner_run_lease_id,
        owner_worker_instance_id,
        owner_run_state_version
    )
    SELECT $7,
           $8,
           scope.org_id,
           scope.worker_group_id,
           scope.project_id,
           scope.environment_id,
           scope.run_id,
           $9::run_wait_kind,
           COALESCE($10::text, ''),
           'live_waiting'::run_wait_state,
           $11::timestamptz,
           CASE
             WHEN $12::interval <= interval '0 seconds' THEN now()
             ELSE now() + $12::interval
           END,
           now(),
           scope.runtime_instance_id,
           scope.runtime_epoch,
           scope.run_id,
           scope.run_lease_id,
           scope.worker_instance_id,
           scope.state_version
      FROM scope
    RETURNING id, public_id, org_id, worker_group_id, project_id, environment_id, run_id, kind, correlation_id, state, timeout_at, runtime_checkpoint_due_at, runtime_checkpoint_started_at, live_wait_started_at, owner_runtime_instance_id, owner_runtime_epoch, owner_run_id, owner_run_lease_id, owner_run_state_version, owner_worker_instance_id, runtime_checkpoint_id, workspace_version_id, active_elapsed_ms_at_park, parked_at, resolved_at, resuming_at, resumed_at, cancelled_at, created_at, updated_at
),
waiting_runtime_instance AS (
    UPDATE runtime_instances
       SET state = 'waiting_hot',
           owner_run_id = inserted_wait.run_id,
           owner_run_lease_id = inserted_wait.owner_run_lease_id,
           owner_run_wait_id = inserted_wait.id,
           owner_run_state_version = inserted_wait.owner_run_state_version,
           waiting_at = now(),
           updated_at = now()
      FROM scope, inserted_wait
     WHERE runtime_instances.org_id = scope.org_id
       AND runtime_instances.id = scope.runtime_instance_id
       AND runtime_instances.state IN ('running', 'waiting_hot')
    RETURNING runtime_instances.id
)
SELECT inserted_wait.id, inserted_wait.public_id, inserted_wait.org_id, inserted_wait.worker_group_id, inserted_wait.project_id, inserted_wait.environment_id, inserted_wait.run_id, inserted_wait.kind, inserted_wait.correlation_id, inserted_wait.state, inserted_wait.timeout_at, inserted_wait.runtime_checkpoint_due_at, inserted_wait.runtime_checkpoint_started_at, inserted_wait.live_wait_started_at, inserted_wait.owner_runtime_instance_id, inserted_wait.owner_runtime_epoch, inserted_wait.owner_run_id, inserted_wait.owner_run_lease_id, inserted_wait.owner_run_state_version, inserted_wait.owner_worker_instance_id, inserted_wait.runtime_checkpoint_id, inserted_wait.workspace_version_id, inserted_wait.active_elapsed_ms_at_park, inserted_wait.parked_at, inserted_wait.resolved_at, inserted_wait.resuming_at, inserted_wait.resumed_at, inserted_wait.cancelled_at, inserted_wait.created_at, inserted_wait.updated_at
  FROM inserted_wait
 WHERE EXISTS (SELECT 1 FROM waiting_runtime_instance)
`

type CreateHotRunWaitParams struct {
	OrgID            pgtype.UUID        `json:"org_id"`
	ProjectID        pgtype.UUID        `json:"project_id"`
	EnvironmentID    pgtype.UUID        `json:"environment_id"`
	RunID            pgtype.UUID        `json:"run_id"`
	RunLeaseID       pgtype.UUID        `json:"run_lease_id"`
	WorkerInstanceID pgtype.UUID        `json:"worker_instance_id"`
	ID               pgtype.UUID        `json:"id"`
	PublicID         string             `json:"public_id"`
	Kind             RunWaitKind        `json:"kind"`
	CorrelationID    string             `json:"correlation_id"`
	TimeoutAt        pgtype.Timestamptz `json:"timeout_at"`
	CheckpointDelay  pgtype.Interval    `json:"checkpoint_delay"`
}

type CreateHotRunWaitRow struct {
	ID                         pgtype.UUID        `json:"id"`
	PublicID                   string             `json:"public_id"`
	OrgID                      pgtype.UUID        `json:"org_id"`
	WorkerGroupID              string             `json:"worker_group_id"`
	ProjectID                  pgtype.UUID        `json:"project_id"`
	EnvironmentID              pgtype.UUID        `json:"environment_id"`
	RunID                      pgtype.UUID        `json:"run_id"`
	Kind                       RunWaitKind        `json:"kind"`
	CorrelationID              string             `json:"correlation_id"`
	State                      RunWaitState       `json:"state"`
	TimeoutAt                  pgtype.Timestamptz `json:"timeout_at"`
	RuntimeCheckpointDueAt     pgtype.Timestamptz `json:"runtime_checkpoint_due_at"`
	RuntimeCheckpointStartedAt pgtype.Timestamptz `json:"runtime_checkpoint_started_at"`
	LiveWaitStartedAt          pgtype.Timestamptz `json:"live_wait_started_at"`
	OwnerRuntimeInstanceID     pgtype.UUID        `json:"owner_runtime_instance_id"`
	OwnerRuntimeEpoch          pgtype.Int8        `json:"owner_runtime_epoch"`
	OwnerRunID                 pgtype.UUID        `json:"owner_run_id"`
	OwnerRunLeaseID            pgtype.UUID        `json:"owner_run_lease_id"`
	OwnerRunStateVersion       pgtype.Int8        `json:"owner_run_state_version"`
	OwnerWorkerInstanceID      pgtype.UUID        `json:"owner_worker_instance_id"`
	RuntimeCheckpointID        pgtype.UUID        `json:"runtime_checkpoint_id"`
	WorkspaceVersionID         pgtype.UUID        `json:"workspace_version_id"`
	ActiveElapsedMsAtPark      pgtype.Int8        `json:"active_elapsed_ms_at_park"`
	ParkedAt                   pgtype.Timestamptz `json:"parked_at"`
	ResolvedAt                 pgtype.Timestamptz `json:"resolved_at"`
	ResumingAt                 pgtype.Timestamptz `json:"resuming_at"`
	ResumedAt                  pgtype.Timestamptz `json:"resumed_at"`
	CancelledAt                pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateHotRunWait(ctx context.Context, arg CreateHotRunWaitParams) (CreateHotRunWaitRow, error) {
	row := q.db.QueryRow(ctx, createHotRunWait,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.RunID,
		arg.RunLeaseID,
		arg.WorkerInstanceID,
		arg.ID,
		arg.PublicID,
		arg.Kind,
		arg.CorrelationID,
		arg.TimeoutAt,
		arg.CheckpointDelay,
	)
	var i CreateHotRunWaitRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.WorkerGroupID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.RunID,
		&i.Kind,
		&i.CorrelationID,
		&i.State,
		&i.TimeoutAt,
		&i.RuntimeCheckpointDueAt,
		&i.RuntimeCheckpointStartedAt,
		&i.LiveWaitStartedAt,
		&i.OwnerRuntimeInstanceID,
		&i.OwnerRuntimeEpoch,
		&i.OwnerRunID,
		&i.OwnerRunLeaseID,
		&i.OwnerRunStateVersion,
		&i.OwnerWorkerInstanceID,
		&i.RuntimeCheckpointID,
		&i.WorkspaceVersionID,
		&i.ActiveElapsedMsAtPark,
		&i.ParkedAt,
		&i.ResolvedAt,
		&i.ResumingAt,
		&i.ResumedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireDueRunWaits = `-- name: ExpireDueRunWaits :many
UPDATE run_waits
   SET state = CASE
         WHEN state = 'live_waiting' THEN 'resolved_live'::run_wait_state
         ELSE 'expired'::run_wait_state
       END,
       resolved_at = COALESCE(run_waits.resolved_at, now()),
       updated_at = now()
 WHERE org_id = $1
   AND worker_group_id = $2
   AND state IN ('live_waiting', 'checkpointed_waiting')
   AND timeout_at IS NOT NULL
   AND timeout_at <= now()
RETURNING id, public_id, org_id, worker_group_id, project_id, environment_id, run_id, kind, correlation_id, state, timeout_at, runtime_checkpoint_due_at, runtime_checkpoint_started_at, live_wait_started_at, owner_runtime_instance_id, owner_runtime_epoch, owner_run_id, owner_run_lease_id, owner_run_state_version, owner_worker_instance_id, runtime_checkpoint_id, workspace_version_id, active_elapsed_ms_at_park, parked_at, resolved_at, resuming_at, resumed_at, cancelled_at, created_at, updated_at
`

type ExpireDueRunWaitsParams struct {
	OrgID         pgtype.UUID `json:"org_id"`
	WorkerGroupID string      `json:"worker_group_id"`
}

func (q *Queries) ExpireDueRunWaits(ctx context.Context, arg ExpireDueRunWaitsParams) ([]RunWait, error) {
	rows, err := q.db.Query(ctx, expireDueRunWaits, arg.OrgID, arg.WorkerGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunWait
	for rows.Next() {
		var i RunWait
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrgID,
			&i.WorkerGroupID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.RunID,
			&i.Kind,
			&i.CorrelationID,
			&i.State,
			&i.TimeoutAt,
			&i.RuntimeCheckpointDueAt,
			&i.RuntimeCheckpointStartedAt,
			&i.LiveWaitStartedAt,
			&i.OwnerRuntimeInstanceID,
			&i.OwnerRuntimeEpoch,
			&i.OwnerRunID,
			&i.OwnerRunLeaseID,
			&i.OwnerRunStateVersion,
			&i.OwnerWorkerInstanceID,
			&i.RuntimeCheckpointID,
			&i.WorkspaceVersionID,
			&i.ActiveElapsedMsAtPark,
			&i.ParkedAt,
			&i.ResolvedAt,
			&i.ResumingAt,
			&i.ResumedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failStaleResolvedRunWaits = `-- name: FailStaleResolvedRunWaits :many
WITH stale_waits AS MATERIALIZED (
    SELECT run_waits.id AS run_wait_id,
           run_waits.org_id,
           run_waits.worker_group_id,
           run_waits.project_id,
           run_waits.environment_id,
           run_waits.run_id,
           runs.session_id,
           runs.current_attempt_id,
           runs.current_attempt_number,
           runs.trace_id,
           runs.root_span_id,
           runs.state_version + 1 AS next_state_version,
           runtime_checkpoints.id AS runtime_checkpoint_id,
           runtime_checkpoints.base_workspace_version_id,
           runtime_checkpoints.expires_at AS runtime_checkpoint_expires_at,
           workspaces.current_version_id,
           run_waits.state AS run_wait_state,
           runs.status AS run_status,
           CASE
             WHEN runtime_checkpoints.expires_at <= now()
             THEN 'runtime_checkpoint_expired'
             ELSE 'workspace_version_mismatch'
           END AS failure_reason,
           CASE
             WHEN runtime_checkpoints.expires_at <= now()
             THEN 'runtime checkpoint expired while run was parked'
             ELSE 'workspace advanced while run was parked'
           END AS failure_message
      FROM run_waits
      JOIN runs ON runs.org_id = run_waits.org_id
               AND runs.project_id = run_waits.project_id
               AND runs.environment_id = run_waits.environment_id
               AND runs.id = run_waits.run_id
      JOIN sessions ON sessions.org_id = runs.org_id
                        AND sessions.project_id = runs.project_id
                        AND sessions.environment_id = runs.environment_id
                        AND sessions.id = runs.session_id
      JOIN runtime_checkpoints ON runtime_checkpoints.org_id = run_waits.org_id
                              AND runtime_checkpoints.project_id = run_waits.project_id
                              AND runtime_checkpoints.environment_id = run_waits.environment_id
                              AND runtime_checkpoints.run_id = run_waits.run_id
                              AND runtime_checkpoints.id = run_waits.runtime_checkpoint_id
      JOIN workspaces ON workspaces.org_id = runs.org_id
                     AND workspaces.project_id = runs.project_id
                     AND workspaces.environment_id = runs.environment_id
                     AND workspaces.id = runs.workspace_id
     WHERE run_waits.org_id = $1
       AND run_waits.worker_group_id = $2
       AND (
           (run_waits.state IN ('resolved_live', 'resolved_checkpointed', 'expired') AND runs.status = 'waiting')
           OR (run_waits.state = 'resuming' AND runs.status = 'queued')
       )
       AND run_waits.runtime_checkpoint_id IS NOT NULL
       AND runs.current_run_lease_id IS NULL
       AND runtime_checkpoints.state = 'ready'
       AND runs.latest_runtime_checkpoint_id = runtime_checkpoints.id
       AND (
           workspaces.current_version_id IS DISTINCT FROM runtime_checkpoints.base_workspace_version_id
           OR runtime_checkpoints.expires_at <= now()
       )
     ORDER BY COALESCE(run_waits.resolved_at, run_waits.timeout_at, run_waits.updated_at), run_waits.id
     LIMIT $3
     FOR UPDATE OF run_waits, runs, sessions
),
failed_waits AS (
    UPDATE run_waits
       SET state = 'failed',
           updated_at = now()
      FROM stale_waits
     WHERE run_waits.org_id = stale_waits.org_id
       AND run_waits.id = stale_waits.run_wait_id
       AND run_waits.state = stale_waits.run_wait_state
    RETURNING run_waits.id, run_waits.public_id, run_waits.org_id, run_waits.worker_group_id, run_waits.project_id, run_waits.environment_id, run_waits.run_id, run_waits.kind, run_waits.correlation_id, run_waits.state, run_waits.timeout_at, run_waits.runtime_checkpoint_due_at, run_waits.runtime_checkpoint_started_at, run_waits.live_wait_started_at, run_waits.owner_runtime_instance_id, run_waits.owner_runtime_epoch, run_waits.owner_run_id, run_waits.owner_run_lease_id, run_waits.owner_run_state_version, run_waits.owner_worker_instance_id, run_waits.runtime_checkpoint_id, run_waits.workspace_version_id, run_waits.active_elapsed_ms_at_park, run_waits.parked_at, run_waits.resolved_at, run_waits.resuming_at, run_waits.resumed_at, run_waits.cancelled_at, run_waits.created_at, run_waits.updated_at
),
failed_runs AS (
    UPDATE runs
       SET status = 'failed',
           execution_status = 'finished',
           terminal_outcome = 'failed',
           error_message = stale_waits.failure_message,
           state_version = stale_waits.next_state_version,
           finished_at = now(),
           updated_at = now()
      FROM stale_waits
      JOIN failed_waits ON failed_waits.org_id = stale_waits.org_id
                       AND failed_waits.id = stale_waits.run_wait_id
     WHERE runs.org_id = stale_waits.org_id
       AND runs.id = stale_waits.run_id
       AND runs.status = stale_waits.run_status
       AND runs.current_run_lease_id IS NULL
    RETURNING runs.id, runs.org_id, runs.worker_group_id, runs.project_id, runs.environment_id, runs.session_id,
              runs.current_attempt_id, runs.current_attempt_number, runs.trace_id, runs.root_span_id,
              runs.state_version, runs.error_message, stale_waits.runtime_checkpoint_id,
              stale_waits.base_workspace_version_id, stale_waits.current_version_id,
              stale_waits.runtime_checkpoint_expires_at, stale_waits.failure_reason
),
invalidated_checkpoints AS (
    UPDATE runtime_checkpoints
       SET state = 'invalid',
           error_message = failed_runs.error_message,
           invalidated_at = now()
      FROM failed_runs
     WHERE runtime_checkpoints.org_id = failed_runs.org_id
       AND runtime_checkpoints.project_id = failed_runs.project_id
       AND runtime_checkpoints.environment_id = failed_runs.environment_id
       AND runtime_checkpoints.run_id = failed_runs.id
       AND runtime_checkpoints.id = failed_runs.runtime_checkpoint_id
       AND runtime_checkpoints.state = 'ready'
    RETURNING runtime_checkpoints.id
),
ended_session_runs AS (
    UPDATE session_runs
       SET ended_at = now()
      FROM failed_runs
     WHERE session_runs.org_id = failed_runs.org_id
       AND session_runs.project_id = failed_runs.project_id
       AND session_runs.environment_id = failed_runs.environment_id
       AND session_runs.session_id = failed_runs.session_id
       AND session_runs.run_id = failed_runs.id
    RETURNING session_runs.id
),
failed_sessions AS (
    SELECT failed_runs.session_id AS id
      FROM failed_runs
),
failed_attempts AS (
    UPDATE run_attempts
       SET status = 'failed',
           error_message = failed_runs.error_message,
           finished_at = now(),
           updated_at = now()
      FROM failed_runs
     WHERE run_attempts.org_id = failed_runs.org_id
       AND run_attempts.run_id = failed_runs.id
       AND run_attempts.id = failed_runs.current_attempt_id
    RETURNING run_attempts.id, run_attempts.run_id
),
completed_queue_entries AS (
    UPDATE run_queue_items
       SET status = 'completed',
           dispatch_generation = dispatch_generation + 1,
           updated_at = now(),
           finished_at = now()
     FROM failed_runs
     WHERE run_queue_items.org_id = failed_runs.org_id
       AND run_queue_items.run_id = failed_runs.id
       AND run_queue_items.status IN ('parked', 'queued', 'published', 'reserved')
    RETURNING run_queue_items.run_id
),
failed_snapshots AS (
    INSERT INTO run_snapshots (org_id, worker_group_id, run_id, version, status, execution_status, terminal_outcome, attempt_id, transition, reason)
    SELECT failed_runs.org_id,
           failed_runs.worker_group_id,
           failed_runs.id,
           failed_runs.state_version,
           'failed',
           'finished',
           'failed',
           failed_runs.current_attempt_id,
           'run.failed',
           jsonb_build_object(
               'origin', 'runtime_resume_wait',
               'reason', failed_runs.failure_reason,
               'message', failed_runs.error_message,
               'runtime_checkpoint_id', failed_runs.runtime_checkpoint_id,
               'base_workspace_version_id', failed_runs.base_workspace_version_id,
               'current_workspace_version_id', failed_runs.current_version_id,
               'runtime_checkpoint_expires_at', failed_runs.runtime_checkpoint_expires_at
           )
      FROM failed_runs
      JOIN failed_attempts ON failed_attempts.run_id = failed_runs.id
    RETURNING run_snapshots.run_id
),
failed_event_seq AS (
    INSERT INTO event_cursors (org_id, worker_group_id, subject_kind, subject_id, seq)
    SELECT failed_runs.org_id, failed_runs.worker_group_id, 'run', failed_runs.id, 1
      FROM failed_runs
      JOIN failed_snapshots ON failed_snapshots.run_id = failed_runs.id
    ON CONFLICT (org_id, worker_group_id, subject_kind, subject_id)
    DO UPDATE SET seq = event_cursors.seq + 1,
                  observed_at = now()
    RETURNING org_id, subject_kind, subject_id, seq
),
failed_events AS (
    INSERT INTO event_hot_payloads (org_id, worker_group_id, project_id, environment_id, run_id, seq, attempt_id, attempt_number, trace_id, span_id, traceparent, category, severity, source, kind, message, payload, redaction_class, snapshot_version)
    SELECT failed_runs.org_id,
           failed_runs.worker_group_id,
           failed_runs.project_id,
           failed_runs.environment_id,
           failed_runs.id,
           failed_event_seq.seq,
           failed_runs.current_attempt_id,
           failed_runs.current_attempt_number,
           failed_runs.trace_id,
           failed_runs.root_span_id,
           '00-' || failed_runs.trace_id || '-' || failed_runs.root_span_id || '-01',
           'lifecycle',
           'error',
           'control',
           'run.failed',
           'run.failed',
           jsonb_build_object(
               'origin', 'runtime_resume_wait',
               'reason', failed_runs.failure_reason,
               'message', failed_runs.error_message,
               'runtime_checkpoint_id', failed_runs.runtime_checkpoint_id,
               'base_workspace_version_id', failed_runs.base_workspace_version_id,
               'current_workspace_version_id', failed_runs.current_version_id,
               'runtime_checkpoint_expires_at', failed_runs.runtime_checkpoint_expires_at
           ),
           'internal',
           failed_runs.state_version
      FROM failed_runs
      JOIN failed_snapshots ON failed_snapshots.run_id = failed_runs.id
      JOIN failed_event_seq ON failed_event_seq.org_id = failed_runs.org_id
                           AND failed_event_seq.subject_kind = 'run'
                           AND failed_event_seq.subject_id = failed_runs.id
    RETURNING id, subject_type, subject_id, seq, org_id, worker_group_id, project_id, environment_id, run_id, deployment_id, attempt_id, run_lease_id, attempt_number, trace_id, span_id, parent_span_id, traceparent, category, severity, source, kind, message, payload, redaction_class, snapshot_version, expires_at, occurred_at, created_at
),
failed_telemetry_outbox AS (
    INSERT INTO telemetry_outbox (org_id, worker_group_id, stream_kind, source_kind, source_id, seq, idempotency_key)
    SELECT failed_events.org_id,
                  failed_events.worker_group_id,
                  'event',
                  failed_events.subject_type,
                  failed_events.subject_id,
                  failed_events.seq,
                  'event:' || failed_events.subject_type::text || ':' || failed_events.subject_id::text || ':' || failed_events.seq::text
      FROM failed_events
    RETURNING id
),
cleanup AS (
    SELECT
        (SELECT count(*) FROM invalidated_checkpoints) AS invalidated_checkpoints,
        (SELECT count(*) FROM failed_telemetry_outbox) AS failed_telemetry_outboxes
)
SELECT failed_waits.id, failed_waits.public_id, failed_waits.org_id, failed_waits.worker_group_id, failed_waits.project_id, failed_waits.environment_id, failed_waits.run_id, failed_waits.kind, failed_waits.correlation_id, failed_waits.state, failed_waits.timeout_at, failed_waits.runtime_checkpoint_due_at, failed_waits.runtime_checkpoint_started_at, failed_waits.live_wait_started_at, failed_waits.owner_runtime_instance_id, failed_waits.owner_runtime_epoch, failed_waits.owner_run_id, failed_waits.owner_run_lease_id, failed_waits.owner_run_state_version, failed_waits.owner_worker_instance_id, failed_waits.runtime_checkpoint_id, failed_waits.workspace_version_id, failed_waits.active_elapsed_ms_at_park, failed_waits.parked_at, failed_waits.resolved_at, failed_waits.resuming_at, failed_waits.resumed_at, failed_waits.cancelled_at, failed_waits.created_at, failed_waits.updated_at
  FROM failed_waits
  JOIN failed_runs ON failed_runs.org_id = failed_waits.org_id
                  AND failed_runs.id = failed_waits.run_id
 WHERE (SELECT invalidated_checkpoints + failed_telemetry_outboxes FROM cleanup) >= 0
`

type FailStaleResolvedRunWaitsParams struct {
	OrgID         pgtype.UUID `json:"org_id"`
	WorkerGroupID string      `json:"worker_group_id"`
	LimitCount    int32       `json:"limit_count"`
}

type FailStaleResolvedRunWaitsRow struct {
	ID                         pgtype.UUID        `json:"id"`
	PublicID                   string             `json:"public_id"`
	OrgID                      pgtype.UUID        `json:"org_id"`
	WorkerGroupID              string             `json:"worker_group_id"`
	ProjectID                  pgtype.UUID        `json:"project_id"`
	EnvironmentID              pgtype.UUID        `json:"environment_id"`
	RunID                      pgtype.UUID        `json:"run_id"`
	Kind                       RunWaitKind        `json:"kind"`
	CorrelationID              string             `json:"correlation_id"`
	State                      RunWaitState       `json:"state"`
	TimeoutAt                  pgtype.Timestamptz `json:"timeout_at"`
	RuntimeCheckpointDueAt     pgtype.Timestamptz `json:"runtime_checkpoint_due_at"`
	RuntimeCheckpointStartedAt pgtype.Timestamptz `json:"runtime_checkpoint_started_at"`
	LiveWaitStartedAt          pgtype.Timestamptz `json:"live_wait_started_at"`
	OwnerRuntimeInstanceID     pgtype.UUID        `json:"owner_runtime_instance_id"`
	OwnerRuntimeEpoch          pgtype.Int8        `json:"owner_runtime_epoch"`
	OwnerRunID                 pgtype.UUID        `json:"owner_run_id"`
	OwnerRunLeaseID            pgtype.UUID        `json:"owner_run_lease_id"`
	OwnerRunStateVersion       pgtype.Int8        `json:"owner_run_state_version"`
	OwnerWorkerInstanceID      pgtype.UUID        `json:"owner_worker_instance_id"`
	RuntimeCheckpointID        pgtype.UUID        `json:"runtime_checkpoint_id"`
	WorkspaceVersionID         pgtype.UUID        `json:"workspace_version_id"`
	ActiveElapsedMsAtPark      pgtype.Int8        `json:"active_elapsed_ms_at_park"`
	ParkedAt                   pgtype.Timestamptz `json:"parked_at"`
	ResolvedAt                 pgtype.Timestamptz `json:"resolved_at"`
	ResumingAt                 pgtype.Timestamptz `json:"resuming_at"`
	ResumedAt                  pgtype.Timestamptz `json:"resumed_at"`
	CancelledAt                pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FailStaleResolvedRunWaits(ctx context.Context, arg FailStaleResolvedRunWaitsParams) ([]FailStaleResolvedRunWaitsRow, error) {
	rows, err := q.db.Query(ctx, failStaleResolvedRunWaits, arg.OrgID, arg.WorkerGroupID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FailStaleResolvedRunWaitsRow
	for rows.Next() {
		var i FailStaleResolvedRunWaitsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrgID,
			&i.WorkerGroupID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.RunID,
			&i.Kind,
			&i.CorrelationID,
			&i.State,
			&i.TimeoutAt,
			&i.RuntimeCheckpointDueAt,
			&i.RuntimeCheckpointStartedAt,
			&i.LiveWaitStartedAt,
			&i.OwnerRuntimeInstanceID,
			&i.OwnerRuntimeEpoch,
			&i.OwnerRunID,
			&i.OwnerRunLeaseID,
			&i.OwnerRunStateVersion,
			&i.OwnerWorkerInstanceID,
			&i.RuntimeCheckpointID,
			&i.WorkspaceVersionID,
			&i.ActiveElapsedMsAtPark,
			&i.ParkedAt,
			&i.ResolvedAt,
			&i.ResumingAt,
			&i.ResumedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRunWait = `-- name: GetRunWait :one
SELECT id, public_id, org_id, worker_group_id, project_id, environment_id, run_id, kind, correlation_id, state, timeout_at, runtime_checkpoint_due_at, runtime_checkpoint_started_at, live_wait_started_at, owner_runtime_instance_id, owner_runtime_epoch, owner_run_id, owner_run_lease_id, owner_run_state_version, owner_worker_instance_id, runtime_checkpoint_id, workspace_version_id, active_elapsed_ms_at_park, parked_at, resolved_at, resuming_at, resumed_at, cancelled_at, created_at, updated_at
     FROM run_waits
 WHERE org_id = $1
   AND project_id = $2
   AND environment_id = $3
   AND id = $4
`

type GetRunWaitParams struct {
	OrgID         pgtype.UUID `json:"org_id"`
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) GetRunWait(ctx context.Context, arg GetRunWaitParams) (RunWait, error) {
	row := q.db.QueryRow(ctx, getRunWait,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ID,
	)
	var i RunWait
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.WorkerGroupID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.RunID,
		&i.Kind,
		&i.CorrelationID,
		&i.State,
		&i.TimeoutAt,
		&i.RuntimeCheckpointDueAt,
		&i.RuntimeCheckpointStartedAt,
		&i.LiveWaitStartedAt,
		&i.OwnerRuntimeInstanceID,
		&i.OwnerRuntimeEpoch,
		&i.OwnerRunID,
		&i.OwnerRunLeaseID,
		&i.OwnerRunStateVersion,
		&i.OwnerWorkerInstanceID,
		&i.RuntimeCheckpointID,
		&i.WorkspaceVersionID,
		&i.ActiveElapsedMsAtPark,
		&i.ParkedAt,
		&i.ResolvedAt,
		&i.ResumingAt,
		&i.ResumedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunWaitByRun = `-- name: GetRunWaitByRun :one
SELECT id, public_id, org_id, worker_group_id, project_id, environment_id, run_id, kind, correlation_id, state, timeout_at, runtime_checkpoint_due_at, runtime_checkpoint_started_at, live_wait_started_at, owner_runtime_instance_id, owner_runtime_epoch, owner_run_id, owner_run_lease_id, owner_run_state_version, owner_worker_instance_id, runtime_checkpoint_id, workspace_version_id, active_elapsed_ms_at_park, parked_at, resolved_at, resuming_at, resumed_at, cancelled_at, created_at, updated_at
  FROM run_waits
 WHERE org_id = $1
   AND run_id = $2
   AND id = $3
`

type GetRunWaitByRunParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	RunID pgtype.UUID `json:"run_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) GetRunWaitByRun(ctx context.Context, arg GetRunWaitByRunParams) (RunWait, error) {
	row := q.db.QueryRow(ctx, getRunWaitByRun, arg.OrgID, arg.RunID, arg.ID)
	var i RunWait
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.WorkerGroupID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.RunID,
		&i.Kind,
		&i.CorrelationID,
		&i.State,
		&i.TimeoutAt,
		&i.RuntimeCheckpointDueAt,
		&i.RuntimeCheckpointStartedAt,
		&i.LiveWaitStartedAt,
		&i.OwnerRuntimeInstanceID,
		&i.OwnerRuntimeEpoch,
		&i.OwnerRunID,
		&i.OwnerRunLeaseID,
		&i.OwnerRunStateVersion,
		&i.OwnerWorkerInstanceID,
		&i.RuntimeCheckpointID,
		&i.WorkspaceVersionID,
		&i.ActiveElapsedMsAtPark,
		&i.ParkedAt,
		&i.ResolvedAt,
		&i.ResumingAt,
		&i.ResumedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkerRunWaitScope = `-- name: GetWorkerRunWaitScope :one
SELECT runs.org_id,
       runs.worker_group_id,
       runs.project_id,
       runs.environment_id,
       runs.deployment_id,
       runs.task_id,
       runs.id AS run_id,
       runs.session_id,
       runs.workspace_id,
       runs.current_run_lease_id,
       run_leases.worker_instance_id,
       workspace_leases.id AS workspace_lease_id,
       workspace_leases.fencing_token AS workspace_fencing_token,
       workspace_leases.workspace_mount_id,
       workspace_leases.base_version_id AS workspace_base_version_id,
       workspaces.current_version_id AS workspace_current_version_id,
       workspace_mounts.dirty_generation,
       worker_instances.cni_profile AS worker_cni_profile
  FROM runs
  JOIN run_leases ON run_leases.org_id = runs.org_id
                 AND run_leases.worker_group_id = runs.worker_group_id
                 AND run_leases.run_id = runs.id
                 AND run_leases.id = runs.current_run_lease_id
  JOIN (
    SELECT placement_project.org_id,
           placement_project.id AS project_id,
           target_environment.id AS environment_id,
           placement_worker_group.region_id AS region_id,
           placement_worker_group.id AS worker_group_id,
           placement_worker_group.state AS worker_group_state
      FROM projects AS placement_project
      JOIN environments AS target_environment
        ON target_environment.org_id = placement_project.org_id
       AND target_environment.project_id = placement_project.id
      JOIN worker_groups AS placement_worker_group
        ON true
) AS project_worker_group_placement
    ON project_worker_group_placement.org_id = runs.org_id
   AND project_worker_group_placement.project_id = runs.project_id
   AND project_worker_group_placement.environment_id = runs.environment_id
   AND project_worker_group_placement.worker_group_id = runs.worker_group_id
   AND project_worker_group_placement.worker_group_state IN ('active', 'draining')
  JOIN worker_groups ON worker_groups.id = project_worker_group_placement.worker_group_id
            AND worker_groups.state IN ('active', 'draining')
  JOIN worker_instances ON worker_instances.id = run_leases.worker_instance_id
                       AND worker_instances.worker_group_id = run_leases.worker_group_id
                       AND worker_instances.worker_group_id = runs.worker_group_id
  JOIN workspaces ON workspaces.org_id = runs.org_id
                 AND workspaces.worker_group_id = runs.worker_group_id
                 AND workspaces.project_id = runs.project_id
                 AND workspaces.environment_id = runs.environment_id
                 AND workspaces.id = runs.workspace_id
  JOIN workspace_leases ON workspace_leases.org_id = runs.org_id
                       AND workspace_leases.worker_group_id = runs.worker_group_id
                       AND workspace_leases.project_id = runs.project_id
                       AND workspace_leases.environment_id = runs.environment_id
                       AND workspace_leases.workspace_id = runs.workspace_id
                       AND workspace_leases.owner_run_id = runs.id
                       AND workspace_leases.lease_kind = 'write'
                       AND workspace_leases.state = 'active'
                       AND workspace_leases.released_at IS NULL
                       AND workspace_leases.expires_at > now()
  JOIN workspace_mounts ON workspace_mounts.org_id = workspace_leases.org_id
                       AND workspace_mounts.worker_group_id = workspace_leases.worker_group_id
                       AND workspace_mounts.project_id = workspace_leases.project_id
                       AND workspace_mounts.environment_id = workspace_leases.environment_id
                       AND workspace_mounts.workspace_id = workspace_leases.workspace_id
                       AND workspace_mounts.id = workspace_leases.workspace_mount_id
 WHERE runs.org_id = $1
   AND runs.id = $2
   AND runs.current_run_lease_id = $3
   AND runs.worker_group_id = worker_instances.worker_group_id
   AND runs.status = 'running'
   AND run_leases.worker_instance_id = $4
   AND run_leases.status IN ('leased', 'running')
   AND run_leases.lease_expires_at > now()
`

type GetWorkerRunWaitScopeParams struct {
	OrgID            pgtype.UUID `json:"org_id"`
	RunID            pgtype.UUID `json:"run_id"`
	RunLeaseID       pgtype.UUID `json:"run_lease_id"`
	WorkerInstanceID pgtype.UUID `json:"worker_instance_id"`
}

type GetWorkerRunWaitScopeRow struct {
	OrgID                     pgtype.UUID `json:"org_id"`
	WorkerGroupID             string      `json:"worker_group_id"`
	ProjectID                 pgtype.UUID `json:"project_id"`
	EnvironmentID             pgtype.UUID `json:"environment_id"`
	DeploymentID              pgtype.UUID `json:"deployment_id"`
	TaskID                    string      `json:"task_id"`
	RunID                     pgtype.UUID `json:"run_id"`
	SessionID                 pgtype.UUID `json:"session_id"`
	WorkspaceID               pgtype.UUID `json:"workspace_id"`
	CurrentRunLeaseID         pgtype.UUID `json:"current_run_lease_id"`
	WorkerInstanceID          pgtype.UUID `json:"worker_instance_id"`
	WorkspaceLeaseID          pgtype.UUID `json:"workspace_lease_id"`
	WorkspaceFencingToken     string      `json:"workspace_fencing_token"`
	WorkspaceMountID          pgtype.UUID `json:"workspace_mount_id"`
	WorkspaceBaseVersionID    pgtype.UUID `json:"workspace_base_version_id"`
	WorkspaceCurrentVersionID pgtype.UUID `json:"workspace_current_version_id"`
	DirtyGeneration           int64       `json:"dirty_generation"`
	WorkerCniProfile          string      `json:"worker_cni_profile"`
}

func (q *Queries) GetWorkerRunWaitScope(ctx context.Context, arg GetWorkerRunWaitScopeParams) (GetWorkerRunWaitScopeRow, error) {
	row := q.db.QueryRow(ctx, getWorkerRunWaitScope,
		arg.OrgID,
		arg.RunID,
		arg.RunLeaseID,
		arg.WorkerInstanceID,
	)
	var i GetWorkerRunWaitScopeRow
	err := row.Scan(
		&i.OrgID,
		&i.WorkerGroupID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.DeploymentID,
		&i.TaskID,
		&i.RunID,
		&i.SessionID,
		&i.WorkspaceID,
		&i.CurrentRunLeaseID,
		&i.WorkerInstanceID,
		&i.WorkspaceLeaseID,
		&i.WorkspaceFencingToken,
		&i.WorkspaceMountID,
		&i.WorkspaceBaseVersionID,
		&i.WorkspaceCurrentVersionID,
		&i.DirtyGeneration,
		&i.WorkerCniProfile,
	)
	return i, err
}

const listRunWaits = `-- name: ListRunWaits :many
WITH cursor_wait AS (
    SELECT parked_at, id
      FROM run_waits
     WHERE org_id = $1
       AND run_id = $2
       AND id = $4::uuid
)
SELECT id, public_id, org_id, worker_group_id, project_id, environment_id, run_id, kind, correlation_id, state, timeout_at, runtime_checkpoint_due_at, runtime_checkpoint_started_at, live_wait_started_at, owner_runtime_instance_id, owner_runtime_epoch, owner_run_id, owner_run_lease_id, owner_run_state_version, owner_worker_instance_id, runtime_checkpoint_id, workspace_version_id, active_elapsed_ms_at_park, parked_at, resolved_at, resuming_at, resumed_at, cancelled_at, created_at, updated_at
  FROM run_waits
 WHERE run_waits.org_id = $1
   AND run_waits.run_id = $2
   AND (
       $3::text IS NULL
       OR run_waits.state = $3::run_wait_state
   )
   AND (
       $4::uuid IS NULL
       OR (run_waits.parked_at, run_waits.id) > (SELECT cursor_wait.parked_at, cursor_wait.id FROM cursor_wait)
   )
 ORDER BY run_waits.parked_at ASC, run_waits.id ASC
 LIMIT $5
`

type ListRunWaitsParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	RunID      pgtype.UUID `json:"run_id"`
	State      pgtype.Text `json:"state"`
	AfterID    pgtype.UUID `json:"after_id"`
	LimitCount int32       `json:"limit_count"`
}

func (q *Queries) ListRunWaits(ctx context.Context, arg ListRunWaitsParams) ([]RunWait, error) {
	rows, err := q.db.Query(ctx, listRunWaits,
		arg.OrgID,
		arg.RunID,
		arg.State,
		arg.AfterID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunWait
	for rows.Next() {
		var i RunWait
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrgID,
			&i.WorkerGroupID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.RunID,
			&i.Kind,
			&i.CorrelationID,
			&i.State,
			&i.TimeoutAt,
			&i.RuntimeCheckpointDueAt,
			&i.RuntimeCheckpointStartedAt,
			&i.LiveWaitStartedAt,
			&i.OwnerRuntimeInstanceID,
			&i.OwnerRuntimeEpoch,
			&i.OwnerRunID,
			&i.OwnerRunLeaseID,
			&i.OwnerRunStateVersion,
			&i.OwnerWorkerInstanceID,
			&i.RuntimeCheckpointID,
			&i.WorkspaceVersionID,
			&i.ActiveElapsedMsAtPark,
			&i.ParkedAt,
			&i.ResolvedAt,
			&i.ResumingAt,
			&i.ResumedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRuntimeResumeWaitResumed = `-- name: MarkRuntimeResumeWaitResumed :one
WITH current_wait AS (
    SELECT run_waits.id, run_waits.public_id, run_waits.org_id, run_waits.worker_group_id, run_waits.project_id, run_waits.environment_id, run_waits.run_id, run_waits.kind, run_waits.correlation_id, run_waits.state, run_waits.timeout_at, run_waits.runtime_checkpoint_due_at, run_waits.runtime_checkpoint_started_at, run_waits.live_wait_started_at, run_waits.owner_runtime_instance_id, run_waits.owner_runtime_epoch, run_waits.owner_run_id, run_waits.owner_run_lease_id, run_waits.owner_run_state_version, run_waits.owner_worker_instance_id, run_waits.runtime_checkpoint_id, run_waits.workspace_version_id, run_waits.active_elapsed_ms_at_park, run_waits.parked_at, run_waits.resolved_at, run_waits.resuming_at, run_waits.resumed_at, run_waits.cancelled_at, run_waits.created_at, run_waits.updated_at
      FROM run_waits
      JOIN runs ON runs.org_id = run_waits.org_id
               AND runs.project_id = run_waits.project_id
               AND runs.environment_id = run_waits.environment_id
               AND runs.id = run_waits.run_id
     WHERE run_waits.org_id = $1
       AND run_waits.id = $2
       AND run_waits.run_id = $3
       AND run_waits.runtime_checkpoint_id = $4
       AND run_waits.state = 'resuming'
       AND runs.current_run_lease_id = $5
       AND runs.status = 'running'
       AND runs.execution_status = 'executing'
     FOR UPDATE OF run_waits
),
restore_phase_payload AS (
    SELECT CASE
             WHEN jsonb_typeof(COALESCE($6::jsonb, '[]'::jsonb)) = 'array'
             THEN COALESCE($6::jsonb, '[]'::jsonb)
             ELSE '[]'::jsonb
           END AS phases
),
updated_restore AS (
    UPDATE runtime_checkpoint_restores
       SET status = 'restored',
           phases = restore_phase_payload.phases,
           error_message = NULL,
           acknowledged_at = COALESCE(runtime_checkpoint_restores.acknowledged_at, now()),
           finished_at = COALESCE(runtime_checkpoint_restores.finished_at, now()),
           updated_at = now()
      FROM current_wait
      JOIN restore_phase_payload ON true
     WHERE runtime_checkpoint_restores.org_id = $1
       AND runtime_checkpoint_restores.project_id = current_wait.project_id
       AND runtime_checkpoint_restores.environment_id = current_wait.environment_id
       AND runtime_checkpoint_restores.run_id = $3
       AND runtime_checkpoint_restores.runtime_checkpoint_id = $4
       AND runtime_checkpoint_restores.run_wait_id = current_wait.id
       AND runtime_checkpoint_restores.run_lease_id = $5
       AND runtime_checkpoint_restores.status = 'restoring'
    RETURNING runtime_checkpoint_restores.id,
              runtime_checkpoint_restores.org_id,
              runtime_checkpoint_restores.project_id,
              runtime_checkpoint_restores.environment_id,
              runtime_checkpoint_restores.run_id
),
updated_wait AS (
    UPDATE run_waits
       SET resumed_at = COALESCE(run_waits.resumed_at, now()),
           state = 'resumed',
           updated_at = now()
      FROM current_wait
      JOIN updated_restore ON true
     WHERE run_waits.org_id = current_wait.org_id
       AND run_waits.id = current_wait.id
    RETURNING run_waits.id, run_waits.public_id, run_waits.org_id, run_waits.worker_group_id, run_waits.project_id, run_waits.environment_id, run_waits.run_id, run_waits.kind, run_waits.correlation_id, run_waits.state, run_waits.timeout_at, run_waits.runtime_checkpoint_due_at, run_waits.runtime_checkpoint_started_at, run_waits.live_wait_started_at, run_waits.owner_runtime_instance_id, run_waits.owner_runtime_epoch, run_waits.owner_run_id, run_waits.owner_run_lease_id, run_waits.owner_run_state_version, run_waits.owner_worker_instance_id, run_waits.runtime_checkpoint_id, run_waits.workspace_version_id, run_waits.active_elapsed_ms_at_park, run_waits.parked_at, run_waits.resolved_at, run_waits.resuming_at, run_waits.resumed_at, run_waits.cancelled_at, run_waits.created_at, run_waits.updated_at
)
SELECT updated_wait.id, updated_wait.public_id, updated_wait.org_id, updated_wait.worker_group_id, updated_wait.project_id, updated_wait.environment_id, updated_wait.run_id, updated_wait.kind, updated_wait.correlation_id, updated_wait.state, updated_wait.timeout_at, updated_wait.runtime_checkpoint_due_at, updated_wait.runtime_checkpoint_started_at, updated_wait.live_wait_started_at, updated_wait.owner_runtime_instance_id, updated_wait.owner_runtime_epoch, updated_wait.owner_run_id, updated_wait.owner_run_lease_id, updated_wait.owner_run_state_version, updated_wait.owner_worker_instance_id, updated_wait.runtime_checkpoint_id, updated_wait.workspace_version_id, updated_wait.active_elapsed_ms_at_park, updated_wait.parked_at, updated_wait.resolved_at, updated_wait.resuming_at, updated_wait.resumed_at, updated_wait.cancelled_at, updated_wait.created_at, updated_wait.updated_at
  FROM updated_wait
`

type MarkRuntimeResumeWaitResumedParams struct {
	OrgID               pgtype.UUID `json:"org_id"`
	ID                  pgtype.UUID `json:"id"`
	RunID               pgtype.UUID `json:"run_id"`
	RuntimeCheckpointID pgtype.UUID `json:"runtime_checkpoint_id"`
	RunLeaseID          pgtype.UUID `json:"run_lease_id"`
	RestorePhases       []byte      `json:"restore_phases"`
}

type MarkRuntimeResumeWaitResumedRow struct {
	ID                         pgtype.UUID        `json:"id"`
	PublicID                   string             `json:"public_id"`
	OrgID                      pgtype.UUID        `json:"org_id"`
	WorkerGroupID              string             `json:"worker_group_id"`
	ProjectID                  pgtype.UUID        `json:"project_id"`
	EnvironmentID              pgtype.UUID        `json:"environment_id"`
	RunID                      pgtype.UUID        `json:"run_id"`
	Kind                       RunWaitKind        `json:"kind"`
	CorrelationID              string             `json:"correlation_id"`
	State                      RunWaitState       `json:"state"`
	TimeoutAt                  pgtype.Timestamptz `json:"timeout_at"`
	RuntimeCheckpointDueAt     pgtype.Timestamptz `json:"runtime_checkpoint_due_at"`
	RuntimeCheckpointStartedAt pgtype.Timestamptz `json:"runtime_checkpoint_started_at"`
	LiveWaitStartedAt          pgtype.Timestamptz `json:"live_wait_started_at"`
	OwnerRuntimeInstanceID     pgtype.UUID        `json:"owner_runtime_instance_id"`
	OwnerRuntimeEpoch          pgtype.Int8        `json:"owner_runtime_epoch"`
	OwnerRunID                 pgtype.UUID        `json:"owner_run_id"`
	OwnerRunLeaseID            pgtype.UUID        `json:"owner_run_lease_id"`
	OwnerRunStateVersion       pgtype.Int8        `json:"owner_run_state_version"`
	OwnerWorkerInstanceID      pgtype.UUID        `json:"owner_worker_instance_id"`
	RuntimeCheckpointID        pgtype.UUID        `json:"runtime_checkpoint_id"`
	WorkspaceVersionID         pgtype.UUID        `json:"workspace_version_id"`
	ActiveElapsedMsAtPark      pgtype.Int8        `json:"active_elapsed_ms_at_park"`
	ParkedAt                   pgtype.Timestamptz `json:"parked_at"`
	ResolvedAt                 pgtype.Timestamptz `json:"resolved_at"`
	ResumingAt                 pgtype.Timestamptz `json:"resuming_at"`
	ResumedAt                  pgtype.Timestamptz `json:"resumed_at"`
	CancelledAt                pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MarkRuntimeResumeWaitResumed(ctx context.Context, arg MarkRuntimeResumeWaitResumedParams) (MarkRuntimeResumeWaitResumedRow, error) {
	row := q.db.QueryRow(ctx, markRuntimeResumeWaitResumed,
		arg.OrgID,
		arg.ID,
		arg.RunID,
		arg.RuntimeCheckpointID,
		arg.RunLeaseID,
		arg.RestorePhases,
	)
	var i MarkRuntimeResumeWaitResumedRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.WorkerGroupID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.RunID,
		&i.Kind,
		&i.CorrelationID,
		&i.State,
		&i.TimeoutAt,
		&i.RuntimeCheckpointDueAt,
		&i.RuntimeCheckpointStartedAt,
		&i.LiveWaitStartedAt,
		&i.OwnerRuntimeInstanceID,
		&i.OwnerRuntimeEpoch,
		&i.OwnerRunID,
		&i.OwnerRunLeaseID,
		&i.OwnerRunStateVersion,
		&i.OwnerWorkerInstanceID,
		&i.RuntimeCheckpointID,
		&i.WorkspaceVersionID,
		&i.ActiveElapsedMsAtPark,
		&i.ParkedAt,
		&i.ResolvedAt,
		&i.ResumingAt,
		&i.ResumedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requeueResolvedRunWaits = `-- name: RequeueResolvedRunWaits :many
WITH eligible_waits AS (
    SELECT run_waits.id, run_waits.public_id, run_waits.org_id, run_waits.worker_group_id, run_waits.project_id, run_waits.environment_id, run_waits.run_id, run_waits.kind, run_waits.correlation_id, run_waits.state, run_waits.timeout_at, run_waits.runtime_checkpoint_due_at, run_waits.runtime_checkpoint_started_at, run_waits.live_wait_started_at, run_waits.owner_runtime_instance_id, run_waits.owner_runtime_epoch, run_waits.owner_run_id, run_waits.owner_run_lease_id, run_waits.owner_run_state_version, run_waits.owner_worker_instance_id, run_waits.runtime_checkpoint_id, run_waits.workspace_version_id, run_waits.active_elapsed_ms_at_park, run_waits.parked_at, run_waits.resolved_at, run_waits.resuming_at, run_waits.resumed_at, run_waits.cancelled_at, run_waits.created_at, run_waits.updated_at,
           runs.current_attempt_id,
           runs.queued_expires_at,
           runs.workspace_id,
           runs.priority
      FROM run_waits
      JOIN runs ON runs.org_id = run_waits.org_id
               AND runs.project_id = run_waits.project_id
               AND runs.environment_id = run_waits.environment_id
               AND runs.id = run_waits.run_id
      JOIN runtime_checkpoints ON runtime_checkpoints.org_id = run_waits.org_id
                              AND runtime_checkpoints.project_id = run_waits.project_id
                              AND runtime_checkpoints.environment_id = run_waits.environment_id
                              AND runtime_checkpoints.run_id = run_waits.run_id
                              AND runtime_checkpoints.id = run_waits.runtime_checkpoint_id
      JOIN workspaces ON workspaces.org_id = runs.org_id
                     AND workspaces.project_id = runs.project_id
                     AND workspaces.environment_id = runs.environment_id
                     AND workspaces.id = runs.workspace_id
                     AND workspaces.current_version_id = runtime_checkpoints.base_workspace_version_id
     WHERE run_waits.org_id = $1
       AND run_waits.worker_group_id = $2
       AND run_waits.state IN ('resolved_live', 'resolved_checkpointed', 'expired')
       AND run_waits.runtime_checkpoint_id IS NOT NULL
       AND runs.status = 'waiting'
       AND runs.current_run_lease_id IS NULL
       AND runtime_checkpoints.state = 'ready'
       AND (runtime_checkpoints.expires_at IS NULL OR runtime_checkpoints.expires_at > now())
     ORDER BY COALESCE(run_waits.resolved_at, run_waits.timeout_at, run_waits.updated_at), run_waits.id
     LIMIT $3
     FOR UPDATE OF run_waits, runs
),
updated_waits AS (
    UPDATE run_waits
       SET state = 'resuming',
           resuming_at = COALESCE(run_waits.resuming_at, now()),
           updated_at = now()
      FROM eligible_waits
     WHERE run_waits.org_id = eligible_waits.org_id
       AND run_waits.id = eligible_waits.id
       AND run_waits.state IN ('resolved_live', 'resolved_checkpointed', 'expired')
    RETURNING run_waits.id, run_waits.public_id, run_waits.org_id, run_waits.worker_group_id, run_waits.project_id, run_waits.environment_id, run_waits.run_id, run_waits.kind, run_waits.correlation_id, run_waits.state, run_waits.timeout_at, run_waits.runtime_checkpoint_due_at, run_waits.runtime_checkpoint_started_at, run_waits.live_wait_started_at, run_waits.owner_runtime_instance_id, run_waits.owner_runtime_epoch, run_waits.owner_run_id, run_waits.owner_run_lease_id, run_waits.owner_run_state_version, run_waits.owner_worker_instance_id, run_waits.runtime_checkpoint_id, run_waits.workspace_version_id, run_waits.active_elapsed_ms_at_park, run_waits.parked_at, run_waits.resolved_at, run_waits.resuming_at, run_waits.resumed_at, run_waits.cancelled_at, run_waits.created_at, run_waits.updated_at
),
updated_runs AS (
    UPDATE runs
       SET status = 'queued',
           execution_status = 'queued',
           state_version = runs.state_version + 1,
           updated_at = now()
      FROM eligible_waits
      JOIN updated_waits ON updated_waits.org_id = eligible_waits.org_id
                        AND updated_waits.id = eligible_waits.id
     WHERE runs.org_id = eligible_waits.org_id
       AND runs.id = eligible_waits.run_id
       AND runs.status = 'waiting'
       AND runs.current_run_lease_id IS NULL
    RETURNING runs.id, runs.org_id, runs.current_attempt_id, runs.queued_expires_at
),
updated_attempts AS (
    UPDATE run_attempts
       SET status = 'queued',
           updated_at = now()
      FROM updated_runs
     WHERE run_attempts.org_id = updated_runs.org_id
       AND run_attempts.run_id = updated_runs.id
       AND run_attempts.id = updated_runs.current_attempt_id
       AND run_attempts.status = 'waiting'
    RETURNING run_attempts.run_id
),
updated_queue AS (
    UPDATE run_queue_items
       SET status = 'queued',
           dispatch_message_id = NULL,
           reserved_by_worker_instance_id = NULL,
           reservation_expires_at = NULL,
           queued_expires_at = updated_runs.queued_expires_at,
           dispatch_generation = run_queue_items.dispatch_generation + 1,
           last_error = '',
           enqueued_at = now(),
           updated_at = now(),
           finished_at = NULL
      FROM updated_runs
      JOIN eligible_waits ON eligible_waits.org_id = updated_runs.org_id
                         AND eligible_waits.run_id = updated_runs.id
    WHERE run_queue_items.org_id = updated_runs.org_id
       AND run_queue_items.run_id = updated_runs.id
       AND run_queue_items.status = 'parked'
    RETURNING run_queue_items.run_id
)
SELECT updated_waits.id, updated_waits.public_id, updated_waits.org_id, updated_waits.worker_group_id, updated_waits.project_id, updated_waits.environment_id, updated_waits.run_id, updated_waits.kind, updated_waits.correlation_id, updated_waits.state, updated_waits.timeout_at, updated_waits.runtime_checkpoint_due_at, updated_waits.runtime_checkpoint_started_at, updated_waits.live_wait_started_at, updated_waits.owner_runtime_instance_id, updated_waits.owner_runtime_epoch, updated_waits.owner_run_id, updated_waits.owner_run_lease_id, updated_waits.owner_run_state_version, updated_waits.owner_worker_instance_id, updated_waits.runtime_checkpoint_id, updated_waits.workspace_version_id, updated_waits.active_elapsed_ms_at_park, updated_waits.parked_at, updated_waits.resolved_at, updated_waits.resuming_at, updated_waits.resumed_at, updated_waits.cancelled_at, updated_waits.created_at, updated_waits.updated_at,
       eligible_waits.workspace_id,
       eligible_waits.priority
  FROM updated_waits
  JOIN eligible_waits ON eligible_waits.org_id = updated_waits.org_id
                     AND eligible_waits.id = updated_waits.id
  JOIN updated_runs ON updated_runs.org_id = updated_waits.org_id
                   AND updated_runs.id = updated_waits.run_id
  JOIN updated_attempts ON updated_attempts.run_id = updated_waits.run_id
  JOIN updated_queue ON updated_queue.run_id = updated_waits.run_id
`

type RequeueResolvedRunWaitsParams struct {
	OrgID         pgtype.UUID `json:"org_id"`
	WorkerGroupID string      `json:"worker_group_id"`
	LimitCount    int32       `json:"limit_count"`
}

type RequeueResolvedRunWaitsRow struct {
	ID                         pgtype.UUID        `json:"id"`
	PublicID                   string             `json:"public_id"`
	OrgID                      pgtype.UUID        `json:"org_id"`
	WorkerGroupID              string             `json:"worker_group_id"`
	ProjectID                  pgtype.UUID        `json:"project_id"`
	EnvironmentID              pgtype.UUID        `json:"environment_id"`
	RunID                      pgtype.UUID        `json:"run_id"`
	Kind                       RunWaitKind        `json:"kind"`
	CorrelationID              string             `json:"correlation_id"`
	State                      RunWaitState       `json:"state"`
	TimeoutAt                  pgtype.Timestamptz `json:"timeout_at"`
	RuntimeCheckpointDueAt     pgtype.Timestamptz `json:"runtime_checkpoint_due_at"`
	RuntimeCheckpointStartedAt pgtype.Timestamptz `json:"runtime_checkpoint_started_at"`
	LiveWaitStartedAt          pgtype.Timestamptz `json:"live_wait_started_at"`
	OwnerRuntimeInstanceID     pgtype.UUID        `json:"owner_runtime_instance_id"`
	OwnerRuntimeEpoch          pgtype.Int8        `json:"owner_runtime_epoch"`
	OwnerRunID                 pgtype.UUID        `json:"owner_run_id"`
	OwnerRunLeaseID            pgtype.UUID        `json:"owner_run_lease_id"`
	OwnerRunStateVersion       pgtype.Int8        `json:"owner_run_state_version"`
	OwnerWorkerInstanceID      pgtype.UUID        `json:"owner_worker_instance_id"`
	RuntimeCheckpointID        pgtype.UUID        `json:"runtime_checkpoint_id"`
	WorkspaceVersionID         pgtype.UUID        `json:"workspace_version_id"`
	ActiveElapsedMsAtPark      pgtype.Int8        `json:"active_elapsed_ms_at_park"`
	ParkedAt                   pgtype.Timestamptz `json:"parked_at"`
	ResolvedAt                 pgtype.Timestamptz `json:"resolved_at"`
	ResumingAt                 pgtype.Timestamptz `json:"resuming_at"`
	ResumedAt                  pgtype.Timestamptz `json:"resumed_at"`
	CancelledAt                pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	WorkspaceID                pgtype.UUID        `json:"workspace_id"`
	Priority                   int32              `json:"priority"`
}

func (q *Queries) RequeueResolvedRunWaits(ctx context.Context, arg RequeueResolvedRunWaitsParams) ([]RequeueResolvedRunWaitsRow, error) {
	rows, err := q.db.Query(ctx, requeueResolvedRunWaits, arg.OrgID, arg.WorkerGroupID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequeueResolvedRunWaitsRow
	for rows.Next() {
		var i RequeueResolvedRunWaitsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrgID,
			&i.WorkerGroupID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.RunID,
			&i.Kind,
			&i.CorrelationID,
			&i.State,
			&i.TimeoutAt,
			&i.RuntimeCheckpointDueAt,
			&i.RuntimeCheckpointStartedAt,
			&i.LiveWaitStartedAt,
			&i.OwnerRuntimeInstanceID,
			&i.OwnerRuntimeEpoch,
			&i.OwnerRunID,
			&i.OwnerRunLeaseID,
			&i.OwnerRunStateVersion,
			&i.OwnerWorkerInstanceID,
			&i.RuntimeCheckpointID,
			&i.WorkspaceVersionID,
			&i.ActiveElapsedMsAtPark,
			&i.ParkedAt,
			&i.ResolvedAt,
			&i.ResumingAt,
			&i.ResumedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceID,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveRunWait = `-- name: ResolveRunWait :one
UPDATE run_waits
   SET state = CASE
         WHEN state = 'live_waiting' THEN 'resolved_live'::run_wait_state
         WHEN state = 'checkpointed_waiting' THEN 'resolved_checkpointed'::run_wait_state
         ELSE state
       END,
       resolved_at = COALESCE(run_waits.resolved_at, now()),
       updated_at = now()
 WHERE org_id = $1
   AND id = $2
   AND state IN ('live_waiting', 'checkpointed_waiting')
RETURNING id, public_id, org_id, worker_group_id, project_id, environment_id, run_id, kind, correlation_id, state, timeout_at, runtime_checkpoint_due_at, runtime_checkpoint_started_at, live_wait_started_at, owner_runtime_instance_id, owner_runtime_epoch, owner_run_id, owner_run_lease_id, owner_run_state_version, owner_worker_instance_id, runtime_checkpoint_id, workspace_version_id, active_elapsed_ms_at_park, parked_at, resolved_at, resuming_at, resumed_at, cancelled_at, created_at, updated_at
`

type ResolveRunWaitParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) ResolveRunWait(ctx context.Context, arg ResolveRunWaitParams) (RunWait, error) {
	row := q.db.QueryRow(ctx, resolveRunWait, arg.OrgID, arg.ID)
	var i RunWait
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.WorkerGroupID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.RunID,
		&i.Kind,
		&i.CorrelationID,
		&i.State,
		&i.TimeoutAt,
		&i.RuntimeCheckpointDueAt,
		&i.RuntimeCheckpointStartedAt,
		&i.LiveWaitStartedAt,
		&i.OwnerRuntimeInstanceID,
		&i.OwnerRuntimeEpoch,
		&i.OwnerRunID,
		&i.OwnerRunLeaseID,
		&i.OwnerRunStateVersion,
		&i.OwnerWorkerInstanceID,
		&i.RuntimeCheckpointID,
		&i.WorkspaceVersionID,
		&i.ActiveElapsedMsAtPark,
		&i.ParkedAt,
		&i.ResolvedAt,
		&i.ResumingAt,
		&i.ResumedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setRunWaitWorkspaceVersion = `-- name: SetRunWaitWorkspaceVersion :one
UPDATE run_waits
   SET workspace_version_id = workspace_versions.id,
       updated_at = now()
  FROM runs
  JOIN workspace_versions
    ON workspace_versions.org_id = runs.org_id
   AND workspace_versions.project_id = runs.project_id
   AND workspace_versions.environment_id = runs.environment_id
   AND workspace_versions.workspace_id = runs.workspace_id
   AND workspace_versions.id = $6
   AND workspace_versions.state = 'ready'
 WHERE run_waits.org_id = $1
   AND run_waits.project_id = $2
   AND run_waits.environment_id = $3
   AND run_waits.id = $4
   AND run_waits.run_id = $5
   AND run_waits.state IN ('live_waiting', 'checkpointing')
   AND run_waits.workspace_version_id IS NULL
   AND runs.org_id = run_waits.org_id
   AND runs.project_id = run_waits.project_id
   AND runs.environment_id = run_waits.environment_id
   AND runs.id = run_waits.run_id
RETURNING run_waits.id, run_waits.public_id, run_waits.org_id, run_waits.worker_group_id, run_waits.project_id, run_waits.environment_id, run_waits.run_id, run_waits.kind, run_waits.correlation_id, run_waits.state, run_waits.timeout_at, run_waits.runtime_checkpoint_due_at, run_waits.runtime_checkpoint_started_at, run_waits.live_wait_started_at, run_waits.owner_runtime_instance_id, run_waits.owner_runtime_epoch, run_waits.owner_run_id, run_waits.owner_run_lease_id, run_waits.owner_run_state_version, run_waits.owner_worker_instance_id, run_waits.runtime_checkpoint_id, run_waits.workspace_version_id, run_waits.active_elapsed_ms_at_park, run_waits.parked_at, run_waits.resolved_at, run_waits.resuming_at, run_waits.resumed_at, run_waits.cancelled_at, run_waits.created_at, run_waits.updated_at
`

type SetRunWaitWorkspaceVersionParams struct {
	OrgID              pgtype.UUID `json:"org_id"`
	ProjectID          pgtype.UUID `json:"project_id"`
	EnvironmentID      pgtype.UUID `json:"environment_id"`
	ID                 pgtype.UUID `json:"id"`
	RunID              pgtype.UUID `json:"run_id"`
	WorkspaceVersionID pgtype.UUID `json:"workspace_version_id"`
}

func (q *Queries) SetRunWaitWorkspaceVersion(ctx context.Context, arg SetRunWaitWorkspaceVersionParams) (RunWait, error) {
	row := q.db.QueryRow(ctx, setRunWaitWorkspaceVersion,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ID,
		arg.RunID,
		arg.WorkspaceVersionID,
	)
	var i RunWait
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.WorkerGroupID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.RunID,
		&i.Kind,
		&i.CorrelationID,
		&i.State,
		&i.TimeoutAt,
		&i.RuntimeCheckpointDueAt,
		&i.RuntimeCheckpointStartedAt,
		&i.LiveWaitStartedAt,
		&i.OwnerRuntimeInstanceID,
		&i.OwnerRuntimeEpoch,
		&i.OwnerRunID,
		&i.OwnerRunLeaseID,
		&i.OwnerRunStateVersion,
		&i.OwnerWorkerInstanceID,
		&i.RuntimeCheckpointID,
		&i.WorkspaceVersionID,
		&i.ActiveElapsedMsAtPark,
		&i.ParkedAt,
		&i.ResolvedAt,
		&i.ResumingAt,
		&i.ResumedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
