// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: run_lease_grants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceRunWorkspaceMountFence = `-- name: AdvanceRunWorkspaceMountFence :one
UPDATE workspace_mounts
   SET fencing_generation = $1,
       updated_at = transaction_timestamp()
 WHERE id = $2
   AND org_id = $3
   AND project_id = $4
   AND environment_id = $5
   AND region_id = $6
   AND worker_group_id = $7
   AND worker_instance_id = $8
   AND worker_epoch = $9
   AND runtime_instance_id = $10
   AND workspace_id = $11
   AND materialized_version_id = $12
   AND fencing_generation = $13
   AND state = 'mounted'
RETURNING id, org_id, worker_group_id, project_id, environment_id, region_id, worker_instance_id, worker_epoch, workspace_id, materialized_version_id, runtime_instance_id, claim_attempt, guest_channel_token_hash, guest_channel_token_expires_at, state, request, dirty_generation, fencing_generation, requested_at, mounted_at, unmounted_at, stopped_at, lost_at, failed_at, terminal_at, terminal_reason_code, terminal_error, created_at, updated_at
`

type AdvanceRunWorkspaceMountFenceParams struct {
	FencingGeneration         int64       `json:"fencing_generation"`
	ID                        pgtype.UUID `json:"id"`
	OrgID                     pgtype.UUID `json:"org_id"`
	ProjectID                 pgtype.UUID `json:"project_id"`
	EnvironmentID             pgtype.UUID `json:"environment_id"`
	RegionID                  string      `json:"region_id"`
	WorkerGroupID             string      `json:"worker_group_id"`
	WorkerInstanceID          pgtype.UUID `json:"worker_instance_id"`
	WorkerEpoch               int64       `json:"worker_epoch"`
	RuntimeInstanceID         pgtype.UUID `json:"runtime_instance_id"`
	WorkspaceID               pgtype.UUID `json:"workspace_id"`
	BaseWorkspaceVersionID    pgtype.UUID `json:"base_workspace_version_id"`
	ExpectedFencingGeneration int64       `json:"expected_fencing_generation"`
}

func (q *Queries) AdvanceRunWorkspaceMountFence(ctx context.Context, arg AdvanceRunWorkspaceMountFenceParams) (WorkspaceMount, error) {
	row := q.db.QueryRow(ctx, advanceRunWorkspaceMountFence,
		arg.FencingGeneration,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.RegionID,
		arg.WorkerGroupID,
		arg.WorkerInstanceID,
		arg.WorkerEpoch,
		arg.RuntimeInstanceID,
		arg.WorkspaceID,
		arg.BaseWorkspaceVersionID,
		arg.ExpectedFencingGeneration,
	)
	var i WorkspaceMount
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkerGroupID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.RegionID,
		&i.WorkerInstanceID,
		&i.WorkerEpoch,
		&i.WorkspaceID,
		&i.MaterializedVersionID,
		&i.RuntimeInstanceID,
		&i.ClaimAttempt,
		&i.GuestChannelTokenHash,
		&i.GuestChannelTokenExpiresAt,
		&i.State,
		&i.Request,
		&i.DirtyGeneration,
		&i.FencingGeneration,
		&i.RequestedAt,
		&i.MountedAt,
		&i.UnmountedAt,
		&i.StoppedAt,
		&i.LostAt,
		&i.FailedAt,
		&i.TerminalAt,
		&i.TerminalReasonCode,
		&i.TerminalError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const advanceRunWorkspaceWriter = `-- name: AdvanceRunWorkspaceWriter :one
UPDATE workspaces
   SET writer_generation = $1,
       last_activity_at = transaction_timestamp(),
       updated_at = transaction_timestamp()
 WHERE org_id = $2
   AND project_id = $3
   AND environment_id = $4
   AND id = $5
   AND ownership_generation = $6
   AND writer_generation = $7
   AND state = 'active'
   AND desired_state = 'active'
RETURNING id, public_id, org_id, project_id, environment_id, region_id, declaration_kind, workspace_declared_id, deployment_definition_id, key, create_idempotency_key, create_idempotency_expires_at, create_request_fingerprint, state_version, stop_generation, owner_actor_id, owner_run_id, ownership_generation, writer_generation, head_version_id, state, desired_state, dirty_state, metadata, tags, retention_policy, last_activity_at, created_at, updated_at, deleted_at
`

type AdvanceRunWorkspaceWriterParams struct {
	WriterGeneration         int64       `json:"writer_generation"`
	OrgID                    pgtype.UUID `json:"org_id"`
	ProjectID                pgtype.UUID `json:"project_id"`
	EnvironmentID            pgtype.UUID `json:"environment_id"`
	WorkspaceID              pgtype.UUID `json:"workspace_id"`
	OwnershipGeneration      int64       `json:"ownership_generation"`
	ExpectedWriterGeneration int64       `json:"expected_writer_generation"`
}

func (q *Queries) AdvanceRunWorkspaceWriter(ctx context.Context, arg AdvanceRunWorkspaceWriterParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, advanceRunWorkspaceWriter,
		arg.WriterGeneration,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.WorkspaceID,
		arg.OwnershipGeneration,
		arg.ExpectedWriterGeneration,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.RegionID,
		&i.DeclarationKind,
		&i.WorkspaceDeclaredID,
		&i.DeploymentDefinitionID,
		&i.Key,
		&i.CreateIdempotencyKey,
		&i.CreateIdempotencyExpiresAt,
		&i.CreateRequestFingerprint,
		&i.StateVersion,
		&i.StopGeneration,
		&i.OwnerActorID,
		&i.OwnerRunID,
		&i.OwnershipGeneration,
		&i.WriterGeneration,
		&i.HeadVersionID,
		&i.State,
		&i.DesiredState,
		&i.DirtyState,
		&i.Metadata,
		&i.Tags,
		&i.RetentionPolicy,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const consumeRunRuntimeReservation = `-- name: ConsumeRunRuntimeReservation :execrows
UPDATE runtime_instances
   SET reserved_run_id = NULL,
       reserved_attempt_number = NULL,
       reserved_workspace_version_id = NULL,
       reservation_expires_at = NULL,
       updated_at = transaction_timestamp()
 WHERE id = $1
   AND workspace_id = $2
   AND reserved_run_id = $3
   AND reserved_attempt_number = $4
   AND reserved_workspace_version_id = $5
   AND reservation_expires_at > transaction_timestamp()
`

type ConsumeRunRuntimeReservationParams struct {
	ID                     pgtype.UUID `json:"id"`
	WorkspaceID            pgtype.UUID `json:"workspace_id"`
	RunID                  pgtype.UUID `json:"run_id"`
	AttemptNumber          pgtype.Int4 `json:"attempt_number"`
	BaseWorkspaceVersionID pgtype.UUID `json:"base_workspace_version_id"`
}

func (q *Queries) ConsumeRunRuntimeReservation(ctx context.Context, arg ConsumeRunRuntimeReservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeRunRuntimeReservation,
		arg.ID,
		arg.WorkspaceID,
		arg.RunID,
		arg.AttemptNumber,
		arg.BaseWorkspaceVersionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createRunRuntimeReservation = `-- name: CreateRunRuntimeReservation :one
WITH created_runtime AS (
    INSERT INTO runtime_instances (
        id,
        org_id,
        worker_group_id,
        project_id,
        environment_id,
        region_id,
        worker_instance_id,
        runtime_identity_id,
        deployment_definition_id,
        worker_epoch,
        network_policy,
        reserved_cpu_millis,
        reserved_memory_bytes,
        reserved_workload_disk_bytes,
        reserved_scratch_bytes,
        reserved_execution_slots,
        workspace_id,
        program_deployment_id,
        reserved_run_id,
        reserved_attempt_number,
        reserved_workspace_version_id,
        reservation_expires_at,
        desired_reason
    ) VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19,
        $20,
        $21,
        $22,
        'run_reservation'
    )
    RETURNING id, org_id, worker_group_id, project_id, environment_id, region_id, worker_instance_id, runtime_identity_id, deployment_definition_id, runtime_substrate_id, worker_epoch, network_policy, reserved_cpu_millis, reserved_memory_bytes, reserved_workload_disk_bytes, reserved_scratch_bytes, reserved_execution_slots, workspace_id, program_deployment_id, reserved_run_id, reserved_attempt_number, reserved_process_id, reserved_workspace_version_id, reservation_expires_at, desired_state, desired_version, desired_at, desired_reason, observed_state, observed_version, observed_desired_version, observed_at, allocated_at, preparing_at, ready_at, closing_at, closed_at, lost_at, failed_at, reclaimed_at, terminal_at, terminal_reason_code, terminal_error, created_at, updated_at
), assigned_slot AS (
    UPDATE worker_network_slots
       SET state = 'assigned',
           runtime_instance_id = created_runtime.id,
           assigned_at = transaction_timestamp(),
           updated_at = transaction_timestamp()
      FROM created_runtime
     WHERE worker_network_slots.id = $23
       AND worker_network_slots.worker_group_id = created_runtime.worker_group_id
       AND worker_network_slots.worker_instance_id = created_runtime.worker_instance_id
       AND worker_network_slots.worker_epoch = created_runtime.worker_epoch
       AND worker_network_slots.generation = $24
       AND worker_network_slots.state = 'available'
       AND worker_network_slots.runtime_instance_id IS NULL
    RETURNING worker_network_slots.id
)
SELECT created_runtime.id, created_runtime.org_id, created_runtime.worker_group_id, created_runtime.project_id, created_runtime.environment_id, created_runtime.region_id, created_runtime.worker_instance_id, created_runtime.runtime_identity_id, created_runtime.deployment_definition_id, created_runtime.runtime_substrate_id, created_runtime.worker_epoch, created_runtime.network_policy, created_runtime.reserved_cpu_millis, created_runtime.reserved_memory_bytes, created_runtime.reserved_workload_disk_bytes, created_runtime.reserved_scratch_bytes, created_runtime.reserved_execution_slots, created_runtime.workspace_id, created_runtime.program_deployment_id, created_runtime.reserved_run_id, created_runtime.reserved_attempt_number, created_runtime.reserved_process_id, created_runtime.reserved_workspace_version_id, created_runtime.reservation_expires_at, created_runtime.desired_state, created_runtime.desired_version, created_runtime.desired_at, created_runtime.desired_reason, created_runtime.observed_state, created_runtime.observed_version, created_runtime.observed_desired_version, created_runtime.observed_at, created_runtime.allocated_at, created_runtime.preparing_at, created_runtime.ready_at, created_runtime.closing_at, created_runtime.closed_at, created_runtime.lost_at, created_runtime.failed_at, created_runtime.reclaimed_at, created_runtime.terminal_at, created_runtime.terminal_reason_code, created_runtime.terminal_error, created_runtime.created_at, created_runtime.updated_at
  FROM created_runtime
  JOIN assigned_slot ON true
`

type CreateRunRuntimeReservationParams struct {
	ID                        pgtype.UUID        `json:"id"`
	OrgID                     pgtype.UUID        `json:"org_id"`
	WorkerGroupID             string             `json:"worker_group_id"`
	ProjectID                 pgtype.UUID        `json:"project_id"`
	EnvironmentID             pgtype.UUID        `json:"environment_id"`
	RegionID                  string             `json:"region_id"`
	WorkerInstanceID          pgtype.UUID        `json:"worker_instance_id"`
	RuntimeIdentityID         string             `json:"runtime_identity_id"`
	DeploymentDefinitionID    pgtype.UUID        `json:"deployment_definition_id"`
	WorkerEpoch               int64              `json:"worker_epoch"`
	NetworkPolicy             []byte             `json:"network_policy"`
	ReservedCpuMillis         int64              `json:"reserved_cpu_millis"`
	ReservedMemoryBytes       int64              `json:"reserved_memory_bytes"`
	ReservedWorkloadDiskBytes int64              `json:"reserved_workload_disk_bytes"`
	ReservedScratchBytes      int64              `json:"reserved_scratch_bytes"`
	ReservedExecutionSlots    int32              `json:"reserved_execution_slots"`
	WorkspaceID               pgtype.UUID        `json:"workspace_id"`
	ProgramDeploymentID       pgtype.UUID        `json:"program_deployment_id"`
	RunID                     pgtype.UUID        `json:"run_id"`
	AttemptNumber             pgtype.Int4        `json:"attempt_number"`
	BaseWorkspaceVersionID    pgtype.UUID        `json:"base_workspace_version_id"`
	ReservationExpiresAt      pgtype.Timestamptz `json:"reservation_expires_at"`
	NetworkSlotID             pgtype.UUID        `json:"network_slot_id"`
	NetworkSlotGeneration     int64              `json:"network_slot_generation"`
}

type CreateRunRuntimeReservationRow struct {
	ID                         pgtype.UUID          `json:"id"`
	OrgID                      pgtype.UUID          `json:"org_id"`
	WorkerGroupID              string               `json:"worker_group_id"`
	ProjectID                  pgtype.UUID          `json:"project_id"`
	EnvironmentID              pgtype.UUID          `json:"environment_id"`
	RegionID                   string               `json:"region_id"`
	WorkerInstanceID           pgtype.UUID          `json:"worker_instance_id"`
	RuntimeIdentityID          string               `json:"runtime_identity_id"`
	DeploymentDefinitionID     pgtype.UUID          `json:"deployment_definition_id"`
	RuntimeSubstrateID         pgtype.UUID          `json:"runtime_substrate_id"`
	WorkerEpoch                int64                `json:"worker_epoch"`
	NetworkPolicy              []byte               `json:"network_policy"`
	ReservedCpuMillis          int64                `json:"reserved_cpu_millis"`
	ReservedMemoryBytes        int64                `json:"reserved_memory_bytes"`
	ReservedWorkloadDiskBytes  int64                `json:"reserved_workload_disk_bytes"`
	ReservedScratchBytes       int64                `json:"reserved_scratch_bytes"`
	ReservedExecutionSlots     int32                `json:"reserved_execution_slots"`
	WorkspaceID                pgtype.UUID          `json:"workspace_id"`
	ProgramDeploymentID        pgtype.UUID          `json:"program_deployment_id"`
	ReservedRunID              pgtype.UUID          `json:"reserved_run_id"`
	ReservedAttemptNumber      pgtype.Int4          `json:"reserved_attempt_number"`
	ReservedProcessID          pgtype.UUID          `json:"reserved_process_id"`
	ReservedWorkspaceVersionID pgtype.UUID          `json:"reserved_workspace_version_id"`
	ReservationExpiresAt       pgtype.Timestamptz   `json:"reservation_expires_at"`
	DesiredState               RuntimeDesiredState  `json:"desired_state"`
	DesiredVersion             int64                `json:"desired_version"`
	DesiredAt                  pgtype.Timestamptz   `json:"desired_at"`
	DesiredReason              string               `json:"desired_reason"`
	ObservedState              RuntimeObservedState `json:"observed_state"`
	ObservedVersion            int64                `json:"observed_version"`
	ObservedDesiredVersion     int64                `json:"observed_desired_version"`
	ObservedAt                 pgtype.Timestamptz   `json:"observed_at"`
	AllocatedAt                pgtype.Timestamptz   `json:"allocated_at"`
	PreparingAt                pgtype.Timestamptz   `json:"preparing_at"`
	ReadyAt                    pgtype.Timestamptz   `json:"ready_at"`
	ClosingAt                  pgtype.Timestamptz   `json:"closing_at"`
	ClosedAt                   pgtype.Timestamptz   `json:"closed_at"`
	LostAt                     pgtype.Timestamptz   `json:"lost_at"`
	FailedAt                   pgtype.Timestamptz   `json:"failed_at"`
	ReclaimedAt                pgtype.Timestamptz   `json:"reclaimed_at"`
	TerminalAt                 pgtype.Timestamptz   `json:"terminal_at"`
	TerminalReasonCode         pgtype.Text          `json:"terminal_reason_code"`
	TerminalError              []byte               `json:"terminal_error"`
	CreatedAt                  pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz   `json:"updated_at"`
}

func (q *Queries) CreateRunRuntimeReservation(ctx context.Context, arg CreateRunRuntimeReservationParams) (CreateRunRuntimeReservationRow, error) {
	row := q.db.QueryRow(ctx, createRunRuntimeReservation,
		arg.ID,
		arg.OrgID,
		arg.WorkerGroupID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.RegionID,
		arg.WorkerInstanceID,
		arg.RuntimeIdentityID,
		arg.DeploymentDefinitionID,
		arg.WorkerEpoch,
		arg.NetworkPolicy,
		arg.ReservedCpuMillis,
		arg.ReservedMemoryBytes,
		arg.ReservedWorkloadDiskBytes,
		arg.ReservedScratchBytes,
		arg.ReservedExecutionSlots,
		arg.WorkspaceID,
		arg.ProgramDeploymentID,
		arg.RunID,
		arg.AttemptNumber,
		arg.BaseWorkspaceVersionID,
		arg.ReservationExpiresAt,
		arg.NetworkSlotID,
		arg.NetworkSlotGeneration,
	)
	var i CreateRunRuntimeReservationRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkerGroupID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.RegionID,
		&i.WorkerInstanceID,
		&i.RuntimeIdentityID,
		&i.DeploymentDefinitionID,
		&i.RuntimeSubstrateID,
		&i.WorkerEpoch,
		&i.NetworkPolicy,
		&i.ReservedCpuMillis,
		&i.ReservedMemoryBytes,
		&i.ReservedWorkloadDiskBytes,
		&i.ReservedScratchBytes,
		&i.ReservedExecutionSlots,
		&i.WorkspaceID,
		&i.ProgramDeploymentID,
		&i.ReservedRunID,
		&i.ReservedAttemptNumber,
		&i.ReservedProcessID,
		&i.ReservedWorkspaceVersionID,
		&i.ReservationExpiresAt,
		&i.DesiredState,
		&i.DesiredVersion,
		&i.DesiredAt,
		&i.DesiredReason,
		&i.ObservedState,
		&i.ObservedVersion,
		&i.ObservedDesiredVersion,
		&i.ObservedAt,
		&i.AllocatedAt,
		&i.PreparingAt,
		&i.ReadyAt,
		&i.ClosingAt,
		&i.ClosedAt,
		&i.LostAt,
		&i.FailedAt,
		&i.ReclaimedAt,
		&i.TerminalAt,
		&i.TerminalReasonCode,
		&i.TerminalError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAssignedRunLease = `-- name: InsertAssignedRunLease :one
INSERT INTO run_leases (
    id,
    org_id,
    project_id,
    environment_id,
    run_id,
    workspace_id,
    region_id,
    lease_sequence,
    attempt_number,
    worker_group_id,
    worker_instance_id,
    worker_epoch,
    runtime_instance_id,
    network_slot_id,
    network_slot_generation,
    runtime_identity_id,
    worker_protocol_version,
    requested_cpu_millis,
    requested_memory_bytes,
    requested_workload_disk_bytes,
    requested_scratch_bytes,
    requested_execution_slots,
    trace_id,
    span_id,
    parent_span_id,
    traceparent,
    start_deadline_at,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,
    $25,
    $26,
    $27,
    $28
)
RETURNING id, org_id, project_id, environment_id, run_id, workspace_id, region_id, lease_sequence, attempt_number, worker_group_id, worker_instance_id, worker_epoch, runtime_instance_id, network_slot_id, network_slot_generation, runtime_identity_id, worker_protocol_version, requested_cpu_millis, requested_memory_bytes, requested_workload_disk_bytes, requested_scratch_bytes, requested_execution_slots, trace_id, span_id, parent_span_id, traceparent, state, assigned_at, start_deadline_at, claimed_at, started_at, renewed_at, expires_at, previous_expires_at, checkpointed_at, terminal_at, terminal_reason_code, terminal_error, terminal_request_fingerprint, created_at, updated_at
`

type InsertAssignedRunLeaseParams struct {
	ID                         pgtype.UUID        `json:"id"`
	OrgID                      pgtype.UUID        `json:"org_id"`
	ProjectID                  pgtype.UUID        `json:"project_id"`
	EnvironmentID              pgtype.UUID        `json:"environment_id"`
	RunID                      pgtype.UUID        `json:"run_id"`
	WorkspaceID                pgtype.UUID        `json:"workspace_id"`
	RegionID                   string             `json:"region_id"`
	LeaseSequence              int64              `json:"lease_sequence"`
	AttemptNumber              int32              `json:"attempt_number"`
	WorkerGroupID              string             `json:"worker_group_id"`
	WorkerInstanceID           pgtype.UUID        `json:"worker_instance_id"`
	WorkerEpoch                int64              `json:"worker_epoch"`
	RuntimeInstanceID          pgtype.UUID        `json:"runtime_instance_id"`
	NetworkSlotID              pgtype.UUID        `json:"network_slot_id"`
	NetworkSlotGeneration      int64              `json:"network_slot_generation"`
	RuntimeIdentityID          string             `json:"runtime_identity_id"`
	WorkerProtocolVersion      string             `json:"worker_protocol_version"`
	RequestedCpuMillis         int64              `json:"requested_cpu_millis"`
	RequestedMemoryBytes       int64              `json:"requested_memory_bytes"`
	RequestedWorkloadDiskBytes int64              `json:"requested_workload_disk_bytes"`
	RequestedScratchBytes      int64              `json:"requested_scratch_bytes"`
	RequestedExecutionSlots    int32              `json:"requested_execution_slots"`
	TraceID                    pgtype.Text        `json:"trace_id"`
	SpanID                     pgtype.Text        `json:"span_id"`
	ParentSpanID               pgtype.Text        `json:"parent_span_id"`
	Traceparent                pgtype.Text        `json:"traceparent"`
	StartDeadlineAt            pgtype.Timestamptz `json:"start_deadline_at"`
	ExpiresAt                  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertAssignedRunLease(ctx context.Context, arg InsertAssignedRunLeaseParams) (RunLease, error) {
	row := q.db.QueryRow(ctx, insertAssignedRunLease,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.RunID,
		arg.WorkspaceID,
		arg.RegionID,
		arg.LeaseSequence,
		arg.AttemptNumber,
		arg.WorkerGroupID,
		arg.WorkerInstanceID,
		arg.WorkerEpoch,
		arg.RuntimeInstanceID,
		arg.NetworkSlotID,
		arg.NetworkSlotGeneration,
		arg.RuntimeIdentityID,
		arg.WorkerProtocolVersion,
		arg.RequestedCpuMillis,
		arg.RequestedMemoryBytes,
		arg.RequestedWorkloadDiskBytes,
		arg.RequestedScratchBytes,
		arg.RequestedExecutionSlots,
		arg.TraceID,
		arg.SpanID,
		arg.ParentSpanID,
		arg.Traceparent,
		arg.StartDeadlineAt,
		arg.ExpiresAt,
	)
	var i RunLease
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.RunID,
		&i.WorkspaceID,
		&i.RegionID,
		&i.LeaseSequence,
		&i.AttemptNumber,
		&i.WorkerGroupID,
		&i.WorkerInstanceID,
		&i.WorkerEpoch,
		&i.RuntimeInstanceID,
		&i.NetworkSlotID,
		&i.NetworkSlotGeneration,
		&i.RuntimeIdentityID,
		&i.WorkerProtocolVersion,
		&i.RequestedCpuMillis,
		&i.RequestedMemoryBytes,
		&i.RequestedWorkloadDiskBytes,
		&i.RequestedScratchBytes,
		&i.RequestedExecutionSlots,
		&i.TraceID,
		&i.SpanID,
		&i.ParentSpanID,
		&i.Traceparent,
		&i.State,
		&i.AssignedAt,
		&i.StartDeadlineAt,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.RenewedAt,
		&i.ExpiresAt,
		&i.PreviousExpiresAt,
		&i.CheckpointedAt,
		&i.TerminalAt,
		&i.TerminalReasonCode,
		&i.TerminalError,
		&i.TerminalRequestFingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRunWorkspaceLease = `-- name: InsertRunWorkspaceLease :one
INSERT INTO workspace_leases (
    id,
    org_id,
    worker_group_id,
    project_id,
    environment_id,
    region_id,
    worker_instance_id,
    worker_epoch,
    runtime_instance_id,
    workspace_id,
    workspace_mount_id,
    owner_run_lease_id,
    base_version_id,
    ownership_generation,
    writer_generation,
    mount_fencing_generation,
    fencing_key_fingerprint,
    fencing_token_hash,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19
)
RETURNING id, org_id, worker_group_id, project_id, environment_id, region_id, worker_instance_id, worker_epoch, runtime_instance_id, workspace_id, workspace_mount_id, state, owner_run_lease_id, owner_process_id, base_version_id, ownership_generation, writer_generation, mount_fencing_generation, fencing_key_fingerprint, fencing_token_hash, acquired_at, renewed_at, expires_at, released_at, lost_at, updated_at, terminal_at, terminal_reason_code, terminal_error
`

type InsertRunWorkspaceLeaseParams struct {
	ID                     pgtype.UUID        `json:"id"`
	OrgID                  pgtype.UUID        `json:"org_id"`
	WorkerGroupID          string             `json:"worker_group_id"`
	ProjectID              pgtype.UUID        `json:"project_id"`
	EnvironmentID          pgtype.UUID        `json:"environment_id"`
	RegionID               string             `json:"region_id"`
	WorkerInstanceID       pgtype.UUID        `json:"worker_instance_id"`
	WorkerEpoch            int64              `json:"worker_epoch"`
	RuntimeInstanceID      pgtype.UUID        `json:"runtime_instance_id"`
	WorkspaceID            pgtype.UUID        `json:"workspace_id"`
	WorkspaceMountID       pgtype.UUID        `json:"workspace_mount_id"`
	OwnerRunLeaseID        pgtype.UUID        `json:"owner_run_lease_id"`
	BaseVersionID          pgtype.UUID        `json:"base_version_id"`
	OwnershipGeneration    int64              `json:"ownership_generation"`
	WriterGeneration       int64              `json:"writer_generation"`
	MountFencingGeneration int64              `json:"mount_fencing_generation"`
	FencingKeyFingerprint  []byte             `json:"fencing_key_fingerprint"`
	FencingTokenHash       string             `json:"fencing_token_hash"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertRunWorkspaceLease(ctx context.Context, arg InsertRunWorkspaceLeaseParams) (WorkspaceLease, error) {
	row := q.db.QueryRow(ctx, insertRunWorkspaceLease,
		arg.ID,
		arg.OrgID,
		arg.WorkerGroupID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.RegionID,
		arg.WorkerInstanceID,
		arg.WorkerEpoch,
		arg.RuntimeInstanceID,
		arg.WorkspaceID,
		arg.WorkspaceMountID,
		arg.OwnerRunLeaseID,
		arg.BaseVersionID,
		arg.OwnershipGeneration,
		arg.WriterGeneration,
		arg.MountFencingGeneration,
		arg.FencingKeyFingerprint,
		arg.FencingTokenHash,
		arg.ExpiresAt,
	)
	var i WorkspaceLease
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkerGroupID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.RegionID,
		&i.WorkerInstanceID,
		&i.WorkerEpoch,
		&i.RuntimeInstanceID,
		&i.WorkspaceID,
		&i.WorkspaceMountID,
		&i.State,
		&i.OwnerRunLeaseID,
		&i.OwnerProcessID,
		&i.BaseVersionID,
		&i.OwnershipGeneration,
		&i.WriterGeneration,
		&i.MountFencingGeneration,
		&i.FencingKeyFingerprint,
		&i.FencingTokenHash,
		&i.AcquiredAt,
		&i.RenewedAt,
		&i.ExpiresAt,
		&i.ReleasedAt,
		&i.LostAt,
		&i.UpdatedAt,
		&i.TerminalAt,
		&i.TerminalReasonCode,
		&i.TerminalError,
	)
	return i, err
}

const setRunCurrentLease = `-- name: SetRunCurrentLease :one
UPDATE runs
   SET current_run_lease_id = $1,
       first_lease_at = coalesce(first_lease_at, transaction_timestamp()),
       state_version = state_version + 1,
       updated_at = transaction_timestamp()
 WHERE id = $2
   AND org_id = $3
   AND state_version = $4
   AND status = 'queued'
   AND current_attempt_number = $5
   AND current_run_lease_id IS NULL
   AND (first_lease_at IS NOT NULL OR queued_expires_at IS NULL OR queued_expires_at > transaction_timestamp())
RETURNING id, public_id, org_id, project_id, environment_id, deployment_id, deployment_definition_id, entrypoint_kind, entrypoint_declared_id, actor_id, cause_kind, schedule_id, schedule_generation, scheduled_at, previous_scheduled_at, schedule_timezone, parent_run_id, parent_owns_lifecycle, workspace_id, base_workspace_version_id, actor_start_input_sequence, actor_start_input_high_watermark, payload, output, terminal_reason_code, error, status, state_version, current_attempt_number, current_run_lease_id, metadata, tags, queue_name, concurrency_key, queue_concurrency_limit, priority, queue_origin_at, queue_score_at, queued_expires_at, max_active_duration_ms, retry_policy, active_elapsed_ms, active_started_at, trace_id, root_span_id, claim_id, created_at, updated_at, first_lease_at, started_at, retry_at, terminal_at
`

type SetRunCurrentLeaseParams struct {
	RunLeaseID           pgtype.UUID `json:"run_lease_id"`
	ID                   pgtype.UUID `json:"id"`
	OrgID                pgtype.UUID `json:"org_id"`
	ExpectedStateVersion int64       `json:"expected_state_version"`
	AttemptNumber        int32       `json:"attempt_number"`
}

func (q *Queries) SetRunCurrentLease(ctx context.Context, arg SetRunCurrentLeaseParams) (Run, error) {
	row := q.db.QueryRow(ctx, setRunCurrentLease,
		arg.RunLeaseID,
		arg.ID,
		arg.OrgID,
		arg.ExpectedStateVersion,
		arg.AttemptNumber,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.DeploymentID,
		&i.DeploymentDefinitionID,
		&i.EntrypointKind,
		&i.EntrypointDeclaredID,
		&i.ActorID,
		&i.CauseKind,
		&i.ScheduleID,
		&i.ScheduleGeneration,
		&i.ScheduledAt,
		&i.PreviousScheduledAt,
		&i.ScheduleTimezone,
		&i.ParentRunID,
		&i.ParentOwnsLifecycle,
		&i.WorkspaceID,
		&i.BaseWorkspaceVersionID,
		&i.ActorStartInputSequence,
		&i.ActorStartInputHighWatermark,
		&i.Payload,
		&i.Output,
		&i.TerminalReasonCode,
		&i.Error,
		&i.Status,
		&i.StateVersion,
		&i.CurrentAttemptNumber,
		&i.CurrentRunLeaseID,
		&i.Metadata,
		&i.Tags,
		&i.QueueName,
		&i.ConcurrencyKey,
		&i.QueueConcurrencyLimit,
		&i.Priority,
		&i.QueueOriginAt,
		&i.QueueScoreAt,
		&i.QueuedExpiresAt,
		&i.MaxActiveDurationMs,
		&i.RetryPolicy,
		&i.ActiveElapsedMs,
		&i.ActiveStartedAt,
		&i.TraceID,
		&i.RootSpanID,
		&i.ClaimID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstLeaseAt,
		&i.StartedAt,
		&i.RetryAt,
		&i.TerminalAt,
	)
	return i, err
}
