// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, org_id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, user_id, token_hash, created_at, last_seen_at, expires_at, revoked_at
`

type CreateSessionParams struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT
    sessions.id,
    sessions.user_id,
    users.display_name,
    users.profile_image_url,
    selected_member.org_id,
    COALESCE(selected_member.role::text, '')::text AS role,
    COALESCE(selected_member.display_name, users.display_name) AS member_display_name,
    sessions.expires_at
  FROM sessions
  JOIN users ON users.id = sessions.user_id
  LEFT JOIN LATERAL (
      SELECT org_members.org_id,
             org_members.role,
             org_members.display_name
        FROM org_members
       WHERE org_members.user_id = sessions.user_id
         AND (sessions.org_id IS NULL OR org_members.org_id = sessions.org_id)
         AND org_members.disabled_at IS NULL
       ORDER BY (org_members.org_id = sessions.org_id) DESC, org_members.created_at ASC
       LIMIT 1
  ) AS selected_member ON true
 WHERE sessions.token_hash = $1
   AND sessions.revoked_at IS NULL
   AND sessions.expires_at > now()
   AND users.disabled_at IS NULL
`

type GetSessionByTokenHashRow struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	DisplayName       string             `json:"display_name"`
	ProfileImageUrl   pgtype.Text        `json:"profile_image_url"`
	OrgID             pgtype.UUID        `json:"org_id"`
	Role              string             `json:"role"`
	MemberDisplayName string             `json:"member_display_name"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.ProfileImageUrl,
		&i.OrgID,
		&i.Role,
		&i.MemberDisplayName,
		&i.ExpiresAt,
	)
	return i, err
}

const refreshSession = `-- name: RefreshSession :exec
UPDATE sessions
   SET last_seen_at = now(),
       expires_at = $1
 WHERE id = $2
   AND revoked_at IS NULL
`

type RefreshSessionParams struct {
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) RefreshSession(ctx context.Context, arg RefreshSessionParams) error {
	_, err := q.db.Exec(ctx, refreshSession, arg.ExpiresAt, arg.ID)
	return err
}

const revokeOrgSessionsForUser = `-- name: RevokeOrgSessionsForUser :execrows
UPDATE sessions
   SET revoked_at = now()
 WHERE org_id = $1
   AND user_id = $2
   AND revoked_at IS NULL
`

type RevokeOrgSessionsForUserParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RevokeOrgSessionsForUser(ctx context.Context, arg RevokeOrgSessionsForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOrgSessionsForUser, arg.OrgID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionByTokenHash = `-- name: RevokeSessionByTokenHash :execrows
UPDATE sessions
   SET revoked_at = now()
 WHERE token_hash = $1
   AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByTokenHash(ctx context.Context, tokenHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionByTokenHash, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionsForUser = `-- name: RevokeSessionsForUser :execrows
UPDATE sessions
   SET revoked_at = now()
 WHERE user_id = $1
   AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionsForUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionsForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
