// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelTaskSession = `-- name: CancelTaskSession :one
WITH target_session AS (
    SELECT id, org_id, project_id, environment_id, task_id, initial_deployment_id, active_deployment_id, external_id, start_fingerprint, status, current_run_id, current_run_version, workspace_id, metadata, tags, completed_at, failed_at, closed_at, closed_reason, cancelled_at, terminal_reason, result, expires_at, created_at, updated_at
      FROM task_sessions
     WHERE task_sessions.org_id = $1
       AND task_sessions.project_id = $2
       AND task_sessions.environment_id = $3
       AND task_sessions.id = $4
     FOR UPDATE
),
cancelled_session AS (
    UPDATE task_sessions
       SET status = 'cancelled',
           cancelled_at = now(),
           result = jsonb_build_object(
               'ok', false,
               'error', jsonb_build_object(
                   'name', 'TaskCancelled',
                   'message', $5::text,
                   'details', jsonb_build_object('origin', 'api')
               )
           ),
           terminal_reason = jsonb_build_object('reason', $5::text, 'origin', 'api'),
           current_run_id = NULL,
           current_run_version = task_sessions.current_run_version + 1,
           updated_at = now()
      FROM target_session
     WHERE task_sessions.org_id = target_session.org_id
       AND task_sessions.id = target_session.id
       AND task_sessions.status = 'open'
    RETURNING task_sessions.id, task_sessions.org_id, task_sessions.project_id, task_sessions.environment_id, task_sessions.task_id, task_sessions.initial_deployment_id, task_sessions.active_deployment_id, task_sessions.external_id, task_sessions.start_fingerprint, task_sessions.status, task_sessions.current_run_id, task_sessions.current_run_version, task_sessions.workspace_id, task_sessions.metadata, task_sessions.tags, task_sessions.completed_at, task_sessions.failed_at, task_sessions.closed_at, task_sessions.closed_reason, task_sessions.cancelled_at, task_sessions.terminal_reason, task_sessions.result, task_sessions.expires_at, task_sessions.created_at, task_sessions.updated_at
),
ended_session_run AS (
    UPDATE task_session_runs
       SET ended_at = now()
      FROM target_session
      JOIN cancelled_session ON true
     WHERE target_session.current_run_id IS NOT NULL
       AND task_session_runs.org_id = target_session.org_id
       AND task_session_runs.project_id = target_session.project_id
       AND task_session_runs.environment_id = target_session.environment_id
       AND task_session_runs.task_session_id = target_session.id
       AND task_session_runs.run_id = target_session.current_run_id
    RETURNING task_session_runs.id
)
SELECT task_sessions.id, task_sessions.org_id, task_sessions.project_id, task_sessions.environment_id, task_sessions.task_id, task_sessions.initial_deployment_id, task_sessions.active_deployment_id, task_sessions.external_id, task_sessions.start_fingerprint, task_sessions.status, task_sessions.current_run_id, task_sessions.current_run_version, task_sessions.workspace_id, task_sessions.metadata, task_sessions.tags, task_sessions.completed_at, task_sessions.failed_at, task_sessions.closed_at, task_sessions.closed_reason, task_sessions.cancelled_at, task_sessions.terminal_reason, task_sessions.result, task_sessions.expires_at, task_sessions.created_at, task_sessions.updated_at
  FROM task_sessions
  JOIN cancelled_session ON cancelled_session.org_id = task_sessions.org_id
                        AND cancelled_session.id = task_sessions.id
`

type CancelTaskSessionParams struct {
	OrgID         pgtype.UUID `json:"org_id"`
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	ID            pgtype.UUID `json:"id"`
	Reason        string      `json:"reason"`
}

func (q *Queries) CancelTaskSession(ctx context.Context, arg CancelTaskSessionParams) (TaskSession, error) {
	row := q.db.QueryRow(ctx, cancelTaskSession,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ID,
		arg.Reason,
	)
	var i TaskSession
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.TaskID,
		&i.InitialDeploymentID,
		&i.ActiveDeploymentID,
		&i.ExternalID,
		&i.StartFingerprint,
		&i.Status,
		&i.CurrentRunID,
		&i.CurrentRunVersion,
		&i.WorkspaceID,
		&i.Metadata,
		&i.Tags,
		&i.CompletedAt,
		&i.FailedAt,
		&i.ClosedAt,
		&i.ClosedReason,
		&i.CancelledAt,
		&i.TerminalReason,
		&i.Result,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const closeTaskSession = `-- name: CloseTaskSession :one
UPDATE task_sessions
   SET status = 'closed',
       closed_at = now(),
       closed_reason = $1,
       terminal_reason = jsonb_build_object('reason', $1, 'origin', 'api'),
       current_run_id = NULL,
       current_run_version = current_run_version + 1,
       updated_at = now()
 WHERE org_id = $2
   AND project_id = $3
   AND environment_id = $4
   AND id = $5
   AND status = 'open'
   AND current_run_id IS NULL
RETURNING id, org_id, project_id, environment_id, task_id, initial_deployment_id, active_deployment_id, external_id, start_fingerprint, status, current_run_id, current_run_version, workspace_id, metadata, tags, completed_at, failed_at, closed_at, closed_reason, cancelled_at, terminal_reason, result, expires_at, created_at, updated_at
`

type CloseTaskSessionParams struct {
	Reason        string      `json:"reason"`
	OrgID         pgtype.UUID `json:"org_id"`
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) CloseTaskSession(ctx context.Context, arg CloseTaskSessionParams) (TaskSession, error) {
	row := q.db.QueryRow(ctx, closeTaskSession,
		arg.Reason,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ID,
	)
	var i TaskSession
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.TaskID,
		&i.InitialDeploymentID,
		&i.ActiveDeploymentID,
		&i.ExternalID,
		&i.StartFingerprint,
		&i.Status,
		&i.CurrentRunID,
		&i.CurrentRunVersion,
		&i.WorkspaceID,
		&i.Metadata,
		&i.Tags,
		&i.CompletedAt,
		&i.FailedAt,
		&i.ClosedAt,
		&i.ClosedReason,
		&i.CancelledAt,
		&i.TerminalReason,
		&i.Result,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTaskSession = `-- name: CreateTaskSession :one
INSERT INTO task_sessions (
    id,
    org_id,
    project_id,
    environment_id,
    task_id,
    initial_deployment_id,
    active_deployment_id,
    external_id,
    start_fingerprint,
    metadata,
    tags,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    coalesce($10::jsonb, '{}'::jsonb),
    coalesce($11::text[], '{}'::text[]),
    $12
)
RETURNING id, org_id, project_id, environment_id, task_id, initial_deployment_id, active_deployment_id, external_id, start_fingerprint, status, current_run_id, current_run_version, workspace_id, metadata, tags, completed_at, failed_at, closed_at, closed_reason, cancelled_at, terminal_reason, result, expires_at, created_at, updated_at
`

type CreateTaskSessionParams struct {
	ID                  pgtype.UUID        `json:"id"`
	OrgID               pgtype.UUID        `json:"org_id"`
	ProjectID           pgtype.UUID        `json:"project_id"`
	EnvironmentID       pgtype.UUID        `json:"environment_id"`
	TaskID              string             `json:"task_id"`
	InitialDeploymentID pgtype.UUID        `json:"initial_deployment_id"`
	ActiveDeploymentID  pgtype.UUID        `json:"active_deployment_id"`
	ExternalID          string             `json:"external_id"`
	StartFingerprint    string             `json:"start_fingerprint"`
	Metadata            []byte             `json:"metadata"`
	Tags                []string           `json:"tags"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateTaskSession(ctx context.Context, arg CreateTaskSessionParams) (TaskSession, error) {
	row := q.db.QueryRow(ctx, createTaskSession,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.TaskID,
		arg.InitialDeploymentID,
		arg.ActiveDeploymentID,
		arg.ExternalID,
		arg.StartFingerprint,
		arg.Metadata,
		arg.Tags,
		arg.ExpiresAt,
	)
	var i TaskSession
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.TaskID,
		&i.InitialDeploymentID,
		&i.ActiveDeploymentID,
		&i.ExternalID,
		&i.StartFingerprint,
		&i.Status,
		&i.CurrentRunID,
		&i.CurrentRunVersion,
		&i.WorkspaceID,
		&i.Metadata,
		&i.Tags,
		&i.CompletedAt,
		&i.FailedAt,
		&i.ClosedAt,
		&i.ClosedReason,
		&i.CancelledAt,
		&i.TerminalReason,
		&i.Result,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTaskSessionRun = `-- name: CreateTaskSessionRun :one
INSERT INTO task_session_runs (
    id,
    org_id,
    project_id,
    environment_id,
    task_session_id,
    run_id,
    deployment_id,
    previous_run_id,
    turn_index
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, org_id, project_id, environment_id, task_session_id, run_id, deployment_id, previous_run_id, turn_index, created_at, ended_at
`

type CreateTaskSessionRunParams struct {
	ID            pgtype.UUID `json:"id"`
	OrgID         pgtype.UUID `json:"org_id"`
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	TaskSessionID pgtype.UUID `json:"task_session_id"`
	RunID         pgtype.UUID `json:"run_id"`
	DeploymentID  pgtype.UUID `json:"deployment_id"`
	PreviousRunID pgtype.UUID `json:"previous_run_id"`
	TurnIndex     int32       `json:"turn_index"`
}

func (q *Queries) CreateTaskSessionRun(ctx context.Context, arg CreateTaskSessionRunParams) (TaskSessionRun, error) {
	row := q.db.QueryRow(ctx, createTaskSessionRun,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.TaskSessionID,
		arg.RunID,
		arg.DeploymentID,
		arg.PreviousRunID,
		arg.TurnIndex,
	)
	var i TaskSessionRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.TaskSessionID,
		&i.RunID,
		&i.DeploymentID,
		&i.PreviousRunID,
		&i.TurnIndex,
		&i.CreatedAt,
		&i.EndedAt,
	)
	return i, err
}

const createTaskSessionWorkspace = `-- name: CreateTaskSessionWorkspace :one
WITH created_workspace AS (
    INSERT INTO workspaces (
        id,
        org_id,
        project_id,
        environment_id,
        task_session_id,
        retention_policy
    ) VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        coalesce($6::jsonb, '{}'::jsonb)
    )
    RETURNING id, org_id, project_id, environment_id, task_session_id, current_version_id, mount_path, state, retention_policy, created_at, updated_at
),
attached_session AS (
    UPDATE task_sessions
       SET workspace_id = created_workspace.id,
           updated_at = now()
      FROM created_workspace
     WHERE task_sessions.org_id = created_workspace.org_id
       AND task_sessions.project_id = created_workspace.project_id
       AND task_sessions.environment_id = created_workspace.environment_id
       AND task_sessions.id = created_workspace.task_session_id
    RETURNING task_sessions.id
)
SELECT created_workspace.id, created_workspace.org_id, created_workspace.project_id, created_workspace.environment_id, created_workspace.task_session_id, created_workspace.current_version_id, created_workspace.mount_path, created_workspace.state, created_workspace.retention_policy, created_workspace.created_at, created_workspace.updated_at
  FROM created_workspace
  JOIN attached_session ON true
`

type CreateTaskSessionWorkspaceParams struct {
	ID              pgtype.UUID `json:"id"`
	OrgID           pgtype.UUID `json:"org_id"`
	ProjectID       pgtype.UUID `json:"project_id"`
	EnvironmentID   pgtype.UUID `json:"environment_id"`
	TaskSessionID   pgtype.UUID `json:"task_session_id"`
	RetentionPolicy []byte      `json:"retention_policy"`
}

type CreateTaskSessionWorkspaceRow struct {
	ID               pgtype.UUID        `json:"id"`
	OrgID            pgtype.UUID        `json:"org_id"`
	ProjectID        pgtype.UUID        `json:"project_id"`
	EnvironmentID    pgtype.UUID        `json:"environment_id"`
	TaskSessionID    pgtype.UUID        `json:"task_session_id"`
	CurrentVersionID pgtype.UUID        `json:"current_version_id"`
	MountPath        string             `json:"mount_path"`
	State            WorkspaceState     `json:"state"`
	RetentionPolicy  []byte             `json:"retention_policy"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateTaskSessionWorkspace(ctx context.Context, arg CreateTaskSessionWorkspaceParams) (CreateTaskSessionWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, createTaskSessionWorkspace,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.TaskSessionID,
		arg.RetentionPolicy,
	)
	var i CreateTaskSessionWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.TaskSessionID,
		&i.CurrentVersionID,
		&i.MountPath,
		&i.State,
		&i.RetentionPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTaskStartIdempotency = `-- name: CreateTaskStartIdempotency :one
INSERT INTO task_start_idempotencies (
    id,
    org_id,
    project_id,
    environment_id,
    task_id,
    idempotency_key,
    request_fingerprint,
    task_session_id,
    first_run_id,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
ON CONFLICT (org_id, project_id, environment_id, task_id, idempotency_key) DO NOTHING
RETURNING id, org_id, project_id, environment_id, task_id, idempotency_key, request_fingerprint, task_session_id, first_run_id, expires_at, created_at, last_used_at
`

type CreateTaskStartIdempotencyParams struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	ProjectID          pgtype.UUID        `json:"project_id"`
	EnvironmentID      pgtype.UUID        `json:"environment_id"`
	TaskID             string             `json:"task_id"`
	IdempotencyKey     string             `json:"idempotency_key"`
	RequestFingerprint string             `json:"request_fingerprint"`
	TaskSessionID      pgtype.UUID        `json:"task_session_id"`
	FirstRunID         pgtype.UUID        `json:"first_run_id"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateTaskStartIdempotency(ctx context.Context, arg CreateTaskStartIdempotencyParams) (TaskStartIdempotency, error) {
	row := q.db.QueryRow(ctx, createTaskStartIdempotency,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.TaskID,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
		arg.TaskSessionID,
		arg.FirstRunID,
		arg.ExpiresAt,
	)
	var i TaskStartIdempotency
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.TaskID,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.TaskSessionID,
		&i.FirstRunID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteExpiredTaskStartIdempotency = `-- name: DeleteExpiredTaskStartIdempotency :exec
DELETE FROM task_start_idempotencies
 WHERE org_id = $1
   AND project_id = $2
   AND environment_id = $3
   AND task_id = $4
   AND idempotency_key = $5
   AND expires_at <= now()
`

type DeleteExpiredTaskStartIdempotencyParams struct {
	OrgID          pgtype.UUID `json:"org_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	EnvironmentID  pgtype.UUID `json:"environment_id"`
	TaskID         string      `json:"task_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) DeleteExpiredTaskStartIdempotency(ctx context.Context, arg DeleteExpiredTaskStartIdempotencyParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredTaskStartIdempotency,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.TaskID,
		arg.IdempotencyKey,
	)
	return err
}

const getTaskForStart = `-- name: GetTaskForStart :one
SELECT id, org_id, project_id, environment_id, task_id, metadata, created_at, updated_at, archived_at
  FROM tasks
 WHERE org_id = $1
   AND project_id = $2
   AND environment_id = $3
   AND task_id = $4
`

type GetTaskForStartParams struct {
	OrgID         pgtype.UUID `json:"org_id"`
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	TaskID        string      `json:"task_id"`
}

func (q *Queries) GetTaskForStart(ctx context.Context, arg GetTaskForStartParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskForStart,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.TaskID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.TaskID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getTaskSession = `-- name: GetTaskSession :one
SELECT id, org_id, project_id, environment_id, task_id, initial_deployment_id, active_deployment_id, external_id, start_fingerprint, status, current_run_id, current_run_version, workspace_id, metadata, tags, completed_at, failed_at, closed_at, closed_reason, cancelled_at, terminal_reason, result, expires_at, created_at, updated_at
  FROM task_sessions
 WHERE org_id = $1
   AND project_id = $2
   AND environment_id = $3
   AND id = $4
`

type GetTaskSessionParams struct {
	OrgID         pgtype.UUID `json:"org_id"`
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) GetTaskSession(ctx context.Context, arg GetTaskSessionParams) (TaskSession, error) {
	row := q.db.QueryRow(ctx, getTaskSession,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ID,
	)
	var i TaskSession
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.TaskID,
		&i.InitialDeploymentID,
		&i.ActiveDeploymentID,
		&i.ExternalID,
		&i.StartFingerprint,
		&i.Status,
		&i.CurrentRunID,
		&i.CurrentRunVersion,
		&i.WorkspaceID,
		&i.Metadata,
		&i.Tags,
		&i.CompletedAt,
		&i.FailedAt,
		&i.ClosedAt,
		&i.ClosedReason,
		&i.CancelledAt,
		&i.TerminalReason,
		&i.Result,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskSessionByExternalID = `-- name: GetTaskSessionByExternalID :one
SELECT id, org_id, project_id, environment_id, task_id, initial_deployment_id, active_deployment_id, external_id, start_fingerprint, status, current_run_id, current_run_version, workspace_id, metadata, tags, completed_at, failed_at, closed_at, closed_reason, cancelled_at, terminal_reason, result, expires_at, created_at, updated_at
  FROM task_sessions
 WHERE org_id = $1
   AND project_id = $2
   AND environment_id = $3
   AND task_id = $4
   AND external_id = $5
   AND external_id <> ''
`

type GetTaskSessionByExternalIDParams struct {
	OrgID         pgtype.UUID `json:"org_id"`
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	TaskID        string      `json:"task_id"`
	ExternalID    string      `json:"external_id"`
}

func (q *Queries) GetTaskSessionByExternalID(ctx context.Context, arg GetTaskSessionByExternalIDParams) (TaskSession, error) {
	row := q.db.QueryRow(ctx, getTaskSessionByExternalID,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.TaskID,
		arg.ExternalID,
	)
	var i TaskSession
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.TaskID,
		&i.InitialDeploymentID,
		&i.ActiveDeploymentID,
		&i.ExternalID,
		&i.StartFingerprint,
		&i.Status,
		&i.CurrentRunID,
		&i.CurrentRunVersion,
		&i.WorkspaceID,
		&i.Metadata,
		&i.Tags,
		&i.CompletedAt,
		&i.FailedAt,
		&i.ClosedAt,
		&i.ClosedReason,
		&i.CancelledAt,
		&i.TerminalReason,
		&i.Result,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskSessionByOrgID = `-- name: GetTaskSessionByOrgID :one
SELECT id, org_id, project_id, environment_id, task_id, initial_deployment_id, active_deployment_id, external_id, start_fingerprint, status, current_run_id, current_run_version, workspace_id, metadata, tags, completed_at, failed_at, closed_at, closed_reason, cancelled_at, terminal_reason, result, expires_at, created_at, updated_at
  FROM task_sessions
 WHERE org_id = $1
   AND id = $2
`

type GetTaskSessionByOrgIDParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) GetTaskSessionByOrgID(ctx context.Context, arg GetTaskSessionByOrgIDParams) (TaskSession, error) {
	row := q.db.QueryRow(ctx, getTaskSessionByOrgID, arg.OrgID, arg.ID)
	var i TaskSession
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.TaskID,
		&i.InitialDeploymentID,
		&i.ActiveDeploymentID,
		&i.ExternalID,
		&i.StartFingerprint,
		&i.Status,
		&i.CurrentRunID,
		&i.CurrentRunVersion,
		&i.WorkspaceID,
		&i.Metadata,
		&i.Tags,
		&i.CompletedAt,
		&i.FailedAt,
		&i.ClosedAt,
		&i.ClosedReason,
		&i.CancelledAt,
		&i.TerminalReason,
		&i.Result,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskSessionChannelByName = `-- name: GetTaskSessionChannelByName :one
SELECT id, org_id, project_id, environment_id, task_session_id, definition_id, name, direction, backend, next_sequence, created_at
  FROM channels
 WHERE org_id = $1
   AND project_id = $2
   AND environment_id = $3
   AND task_session_id = $4
   AND name = $5
   AND direction = $6::channel_direction
`

type GetTaskSessionChannelByNameParams struct {
	OrgID         pgtype.UUID      `json:"org_id"`
	ProjectID     pgtype.UUID      `json:"project_id"`
	EnvironmentID pgtype.UUID      `json:"environment_id"`
	TaskSessionID pgtype.UUID      `json:"task_session_id"`
	Name          string           `json:"name"`
	Direction     ChannelDirection `json:"direction"`
}

func (q *Queries) GetTaskSessionChannelByName(ctx context.Context, arg GetTaskSessionChannelByNameParams) (Channel, error) {
	row := q.db.QueryRow(ctx, getTaskSessionChannelByName,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.TaskSessionID,
		arg.Name,
		arg.Direction,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.TaskSessionID,
		&i.DefinitionID,
		&i.Name,
		&i.Direction,
		&i.Backend,
		&i.NextSequence,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskSessionWorkspace = `-- name: GetTaskSessionWorkspace :one
SELECT workspaces.id, workspaces.org_id, workspaces.project_id, workspaces.environment_id, workspaces.task_session_id, workspaces.current_version_id, workspaces.mount_path, workspaces.state, workspaces.retention_policy, workspaces.created_at, workspaces.updated_at
  FROM task_sessions
  JOIN workspaces ON workspaces.org_id = task_sessions.org_id
                 AND workspaces.project_id = task_sessions.project_id
                 AND workspaces.environment_id = task_sessions.environment_id
                 AND workspaces.id = task_sessions.workspace_id
 WHERE task_sessions.org_id = $1
   AND task_sessions.project_id = $2
   AND task_sessions.environment_id = $3
   AND task_sessions.id = $4
`

type GetTaskSessionWorkspaceParams struct {
	OrgID         pgtype.UUID `json:"org_id"`
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	TaskSessionID pgtype.UUID `json:"task_session_id"`
}

func (q *Queries) GetTaskSessionWorkspace(ctx context.Context, arg GetTaskSessionWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, getTaskSessionWorkspace,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.TaskSessionID,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.TaskSessionID,
		&i.CurrentVersionID,
		&i.MountPath,
		&i.State,
		&i.RetentionPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskStartIdempotency = `-- name: GetTaskStartIdempotency :one
SELECT task_start_idempotencies.id, task_start_idempotencies.org_id, task_start_idempotencies.project_id, task_start_idempotencies.environment_id, task_start_idempotencies.task_id, task_start_idempotencies.idempotency_key, task_start_idempotencies.request_fingerprint, task_start_idempotencies.task_session_id, task_start_idempotencies.first_run_id, task_start_idempotencies.expires_at, task_start_idempotencies.created_at, task_start_idempotencies.last_used_at,
       task_sessions.id AS session_id,
       task_sessions.org_id AS session_org_id,
       task_sessions.project_id AS session_project_id,
       task_sessions.environment_id AS session_environment_id,
       task_sessions.task_id AS session_task_id,
       task_sessions.initial_deployment_id AS session_initial_deployment_id,
       task_sessions.active_deployment_id AS session_active_deployment_id,
       task_sessions.external_id AS session_external_id,
       task_sessions.start_fingerprint AS session_start_fingerprint,
       task_sessions.status AS session_status,
       task_sessions.current_run_id AS session_current_run_id,
       task_sessions.current_run_version AS session_current_run_version,
       task_sessions.workspace_id AS session_workspace_id,
       task_sessions.metadata AS session_metadata,
       task_sessions.tags AS session_tags,
       task_sessions.result AS session_result,
       task_sessions.terminal_reason AS session_terminal_reason,
       task_sessions.expires_at AS session_expires_at,
       task_sessions.completed_at AS session_completed_at,
       task_sessions.failed_at AS session_failed_at,
       task_sessions.cancelled_at AS session_cancelled_at,
       task_sessions.created_at AS session_created_at,
       task_sessions.updated_at AS session_updated_at,
       runs.id AS run_id,
       runs.org_id AS run_org_id,
       runs.project_id AS run_project_id,
       runs.environment_id AS run_environment_id,
       runs.deployment_id AS run_deployment_id,
       runs.deployment_task_id AS run_deployment_task_id,
       runs.deployment_version AS run_deployment_version,
       runs.api_version AS run_api_version,
       runs.sdk_version AS run_sdk_version,
       runs.cli_version AS run_cli_version,
       runs.task_id AS run_task_id,
       runs.current_attempt_number AS run_attempt_number,
       runs.status AS run_status,
       runs.execution_status AS run_execution_status,
       runs.terminal_outcome AS run_terminal_outcome,
       runs.payload AS run_payload,
       runs.output AS run_output,
       runs.metadata AS run_metadata,
       runs.tags AS run_tags,
       runs.error_message AS run_error_message,
       runs.exit_code AS run_exit_code,
       runs.created_at AS run_created_at,
       runs.updated_at AS run_updated_at
  FROM task_start_idempotencies
  JOIN task_sessions ON task_sessions.org_id = task_start_idempotencies.org_id
                    AND task_sessions.project_id = task_start_idempotencies.project_id
                    AND task_sessions.environment_id = task_start_idempotencies.environment_id
                    AND task_sessions.id = task_start_idempotencies.task_session_id
  JOIN runs ON runs.org_id = task_start_idempotencies.org_id
           AND runs.project_id = task_start_idempotencies.project_id
           AND runs.environment_id = task_start_idempotencies.environment_id
           AND runs.id = task_start_idempotencies.first_run_id
 WHERE task_start_idempotencies.org_id = $1
   AND task_start_idempotencies.project_id = $2
   AND task_start_idempotencies.environment_id = $3
   AND task_start_idempotencies.task_id = $4
   AND task_start_idempotencies.idempotency_key = $5
   AND task_start_idempotencies.expires_at > now()
`

type GetTaskStartIdempotencyParams struct {
	OrgID          pgtype.UUID `json:"org_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	EnvironmentID  pgtype.UUID `json:"environment_id"`
	TaskID         string      `json:"task_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

type GetTaskStartIdempotencyRow struct {
	ID                         pgtype.UUID            `json:"id"`
	OrgID                      pgtype.UUID            `json:"org_id"`
	ProjectID                  pgtype.UUID            `json:"project_id"`
	EnvironmentID              pgtype.UUID            `json:"environment_id"`
	TaskID                     string                 `json:"task_id"`
	IdempotencyKey             string                 `json:"idempotency_key"`
	RequestFingerprint         string                 `json:"request_fingerprint"`
	TaskSessionID              pgtype.UUID            `json:"task_session_id"`
	FirstRunID                 pgtype.UUID            `json:"first_run_id"`
	ExpiresAt                  pgtype.Timestamptz     `json:"expires_at"`
	CreatedAt                  pgtype.Timestamptz     `json:"created_at"`
	LastUsedAt                 pgtype.Timestamptz     `json:"last_used_at"`
	SessionID                  pgtype.UUID            `json:"session_id"`
	SessionOrgID               pgtype.UUID            `json:"session_org_id"`
	SessionProjectID           pgtype.UUID            `json:"session_project_id"`
	SessionEnvironmentID       pgtype.UUID            `json:"session_environment_id"`
	SessionTaskID              string                 `json:"session_task_id"`
	SessionInitialDeploymentID pgtype.UUID            `json:"session_initial_deployment_id"`
	SessionActiveDeploymentID  pgtype.UUID            `json:"session_active_deployment_id"`
	SessionExternalID          string                 `json:"session_external_id"`
	SessionStartFingerprint    string                 `json:"session_start_fingerprint"`
	SessionStatus              TaskSessionStatus      `json:"session_status"`
	SessionCurrentRunID        pgtype.UUID            `json:"session_current_run_id"`
	SessionCurrentRunVersion   int64                  `json:"session_current_run_version"`
	SessionWorkspaceID         pgtype.UUID            `json:"session_workspace_id"`
	SessionMetadata            []byte                 `json:"session_metadata"`
	SessionTags                []string               `json:"session_tags"`
	SessionResult              []byte                 `json:"session_result"`
	SessionTerminalReason      []byte                 `json:"session_terminal_reason"`
	SessionExpiresAt           pgtype.Timestamptz     `json:"session_expires_at"`
	SessionCompletedAt         pgtype.Timestamptz     `json:"session_completed_at"`
	SessionFailedAt            pgtype.Timestamptz     `json:"session_failed_at"`
	SessionCancelledAt         pgtype.Timestamptz     `json:"session_cancelled_at"`
	SessionCreatedAt           pgtype.Timestamptz     `json:"session_created_at"`
	SessionUpdatedAt           pgtype.Timestamptz     `json:"session_updated_at"`
	RunID                      pgtype.UUID            `json:"run_id"`
	RunOrgID                   pgtype.UUID            `json:"run_org_id"`
	RunProjectID               pgtype.UUID            `json:"run_project_id"`
	RunEnvironmentID           pgtype.UUID            `json:"run_environment_id"`
	RunDeploymentID            pgtype.UUID            `json:"run_deployment_id"`
	RunDeploymentTaskID        pgtype.UUID            `json:"run_deployment_task_id"`
	RunDeploymentVersion       string                 `json:"run_deployment_version"`
	RunApiVersion              string                 `json:"run_api_version"`
	RunSdkVersion              string                 `json:"run_sdk_version"`
	RunCliVersion              string                 `json:"run_cli_version"`
	RunTaskID                  string                 `json:"run_task_id"`
	RunAttemptNumber           pgtype.Int4            `json:"run_attempt_number"`
	RunStatus                  RunStatus              `json:"run_status"`
	RunExecutionStatus         RunExecutionStatus     `json:"run_execution_status"`
	RunTerminalOutcome         NullRunTerminalOutcome `json:"run_terminal_outcome"`
	RunPayload                 []byte                 `json:"run_payload"`
	RunOutput                  []byte                 `json:"run_output"`
	RunMetadata                []byte                 `json:"run_metadata"`
	RunTags                    []string               `json:"run_tags"`
	RunErrorMessage            pgtype.Text            `json:"run_error_message"`
	RunExitCode                pgtype.Int4            `json:"run_exit_code"`
	RunCreatedAt               pgtype.Timestamptz     `json:"run_created_at"`
	RunUpdatedAt               pgtype.Timestamptz     `json:"run_updated_at"`
}

func (q *Queries) GetTaskStartIdempotency(ctx context.Context, arg GetTaskStartIdempotencyParams) (GetTaskStartIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getTaskStartIdempotency,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.TaskID,
		arg.IdempotencyKey,
	)
	var i GetTaskStartIdempotencyRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.TaskID,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.TaskSessionID,
		&i.FirstRunID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.SessionID,
		&i.SessionOrgID,
		&i.SessionProjectID,
		&i.SessionEnvironmentID,
		&i.SessionTaskID,
		&i.SessionInitialDeploymentID,
		&i.SessionActiveDeploymentID,
		&i.SessionExternalID,
		&i.SessionStartFingerprint,
		&i.SessionStatus,
		&i.SessionCurrentRunID,
		&i.SessionCurrentRunVersion,
		&i.SessionWorkspaceID,
		&i.SessionMetadata,
		&i.SessionTags,
		&i.SessionResult,
		&i.SessionTerminalReason,
		&i.SessionExpiresAt,
		&i.SessionCompletedAt,
		&i.SessionFailedAt,
		&i.SessionCancelledAt,
		&i.SessionCreatedAt,
		&i.SessionUpdatedAt,
		&i.RunID,
		&i.RunOrgID,
		&i.RunProjectID,
		&i.RunEnvironmentID,
		&i.RunDeploymentID,
		&i.RunDeploymentTaskID,
		&i.RunDeploymentVersion,
		&i.RunApiVersion,
		&i.RunSdkVersion,
		&i.RunCliVersion,
		&i.RunTaskID,
		&i.RunAttemptNumber,
		&i.RunStatus,
		&i.RunExecutionStatus,
		&i.RunTerminalOutcome,
		&i.RunPayload,
		&i.RunOutput,
		&i.RunMetadata,
		&i.RunTags,
		&i.RunErrorMessage,
		&i.RunExitCode,
		&i.RunCreatedAt,
		&i.RunUpdatedAt,
	)
	return i, err
}

const listTaskSessionChannels = `-- name: ListTaskSessionChannels :many
SELECT id, org_id, project_id, environment_id, task_session_id, definition_id, name, direction, backend, next_sequence, created_at
  FROM channels
 WHERE org_id = $1
   AND project_id = $2
   AND environment_id = $3
   AND task_session_id = $4
 ORDER BY name ASC, direction ASC
`

type ListTaskSessionChannelsParams struct {
	OrgID         pgtype.UUID `json:"org_id"`
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	TaskSessionID pgtype.UUID `json:"task_session_id"`
}

func (q *Queries) ListTaskSessionChannels(ctx context.Context, arg ListTaskSessionChannelsParams) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listTaskSessionChannels,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.TaskSessionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.TaskSessionID,
			&i.DefinitionID,
			&i.Name,
			&i.Direction,
			&i.Backend,
			&i.NextSequence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskSessionRuns = `-- name: ListTaskSessionRuns :many
SELECT task_session_runs.id, task_session_runs.org_id, task_session_runs.project_id, task_session_runs.environment_id, task_session_runs.task_session_id, task_session_runs.run_id, task_session_runs.deployment_id, task_session_runs.previous_run_id, task_session_runs.turn_index, task_session_runs.created_at, task_session_runs.ended_at,
       runs.status,
       runs.execution_status,
       runs.terminal_outcome,
       runs.created_at AS run_created_at,
       runs.updated_at AS run_updated_at
  FROM task_session_runs
  JOIN runs ON runs.org_id = task_session_runs.org_id
           AND runs.project_id = task_session_runs.project_id
           AND runs.environment_id = task_session_runs.environment_id
           AND runs.id = task_session_runs.run_id
 WHERE task_session_runs.org_id = $1
   AND task_session_runs.project_id = $2
   AND task_session_runs.environment_id = $3
   AND task_session_runs.task_session_id = $4
 ORDER BY task_session_runs.turn_index ASC, task_session_runs.created_at ASC
`

type ListTaskSessionRunsParams struct {
	OrgID         pgtype.UUID `json:"org_id"`
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	TaskSessionID pgtype.UUID `json:"task_session_id"`
}

type ListTaskSessionRunsRow struct {
	ID              pgtype.UUID            `json:"id"`
	OrgID           pgtype.UUID            `json:"org_id"`
	ProjectID       pgtype.UUID            `json:"project_id"`
	EnvironmentID   pgtype.UUID            `json:"environment_id"`
	TaskSessionID   pgtype.UUID            `json:"task_session_id"`
	RunID           pgtype.UUID            `json:"run_id"`
	DeploymentID    pgtype.UUID            `json:"deployment_id"`
	PreviousRunID   pgtype.UUID            `json:"previous_run_id"`
	TurnIndex       int32                  `json:"turn_index"`
	CreatedAt       pgtype.Timestamptz     `json:"created_at"`
	EndedAt         pgtype.Timestamptz     `json:"ended_at"`
	Status          RunStatus              `json:"status"`
	ExecutionStatus RunExecutionStatus     `json:"execution_status"`
	TerminalOutcome NullRunTerminalOutcome `json:"terminal_outcome"`
	RunCreatedAt    pgtype.Timestamptz     `json:"run_created_at"`
	RunUpdatedAt    pgtype.Timestamptz     `json:"run_updated_at"`
}

func (q *Queries) ListTaskSessionRuns(ctx context.Context, arg ListTaskSessionRunsParams) ([]ListTaskSessionRunsRow, error) {
	rows, err := q.db.Query(ctx, listTaskSessionRuns,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.TaskSessionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskSessionRunsRow
	for rows.Next() {
		var i ListTaskSessionRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.TaskSessionID,
			&i.RunID,
			&i.DeploymentID,
			&i.PreviousRunID,
			&i.TurnIndex,
			&i.CreatedAt,
			&i.EndedAt,
			&i.Status,
			&i.ExecutionStatus,
			&i.TerminalOutcome,
			&i.RunCreatedAt,
			&i.RunUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskSessions = `-- name: ListTaskSessions :many
SELECT id, org_id, project_id, environment_id, task_id, initial_deployment_id, active_deployment_id, external_id, start_fingerprint, status, current_run_id, current_run_version, workspace_id, metadata, tags, completed_at, failed_at, closed_at, closed_reason, cancelled_at, terminal_reason, result, expires_at, created_at, updated_at
  FROM task_sessions
 WHERE org_id = $1
   AND project_id = $2
   AND environment_id = $3
   AND (
       $4::text = ''
       OR status::text = $4::text
   )
   AND (
       $5::text = ''
       OR task_id = $5
   )
 ORDER BY updated_at DESC, id DESC
 LIMIT $6
`

type ListTaskSessionsParams struct {
	OrgID         pgtype.UUID `json:"org_id"`
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	StatusFilter  string      `json:"status_filter"`
	TaskIDFilter  string      `json:"task_id_filter"`
	RowLimit      int32       `json:"row_limit"`
}

func (q *Queries) ListTaskSessions(ctx context.Context, arg ListTaskSessionsParams) ([]TaskSession, error) {
	rows, err := q.db.Query(ctx, listTaskSessions,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.StatusFilter,
		arg.TaskIDFilter,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskSession
	for rows.Next() {
		var i TaskSession
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.TaskID,
			&i.InitialDeploymentID,
			&i.ActiveDeploymentID,
			&i.ExternalID,
			&i.StartFingerprint,
			&i.Status,
			&i.CurrentRunID,
			&i.CurrentRunVersion,
			&i.WorkspaceID,
			&i.Metadata,
			&i.Tags,
			&i.CompletedAt,
			&i.FailedAt,
			&i.ClosedAt,
			&i.ClosedReason,
			&i.CancelledAt,
			&i.TerminalReason,
			&i.Result,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTaskSession = `-- name: LockTaskSession :one
SELECT id, org_id, project_id, environment_id, task_id, initial_deployment_id, active_deployment_id, external_id, start_fingerprint, status, current_run_id, current_run_version, workspace_id, metadata, tags, completed_at, failed_at, closed_at, closed_reason, cancelled_at, terminal_reason, result, expires_at, created_at, updated_at
  FROM task_sessions
 WHERE org_id = $1
   AND project_id = $2
   AND environment_id = $3
   AND id = $4
 FOR UPDATE
`

type LockTaskSessionParams struct {
	OrgID         pgtype.UUID `json:"org_id"`
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) LockTaskSession(ctx context.Context, arg LockTaskSessionParams) (TaskSession, error) {
	row := q.db.QueryRow(ctx, lockTaskSession,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ID,
	)
	var i TaskSession
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.TaskID,
		&i.InitialDeploymentID,
		&i.ActiveDeploymentID,
		&i.ExternalID,
		&i.StartFingerprint,
		&i.Status,
		&i.CurrentRunID,
		&i.CurrentRunVersion,
		&i.WorkspaceID,
		&i.Metadata,
		&i.Tags,
		&i.CompletedAt,
		&i.FailedAt,
		&i.ClosedAt,
		&i.ClosedReason,
		&i.CancelledAt,
		&i.TerminalReason,
		&i.Result,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const patchTaskSession = `-- name: PatchTaskSession :one
UPDATE task_sessions
   SET metadata = coalesce($1::jsonb, task_sessions.metadata),
       tags = coalesce($2::text[], task_sessions.tags),
       expires_at = CASE
           WHEN $3::timestamptz IS NULL THEN task_sessions.expires_at
           ELSE $3::timestamptz
       END,
       updated_at = now()
 WHERE org_id = $4
   AND project_id = $5
   AND environment_id = $6
   AND id = $7
   AND status = 'open'
   AND (
       $3::timestamptz IS NULL
       OR (
           task_sessions.expires_at IS NOT NULL
           AND task_sessions.expires_at > now()
           AND $3::timestamptz > task_sessions.expires_at
       )
   )
RETURNING id, org_id, project_id, environment_id, task_id, initial_deployment_id, active_deployment_id, external_id, start_fingerprint, status, current_run_id, current_run_version, workspace_id, metadata, tags, completed_at, failed_at, closed_at, closed_reason, cancelled_at, terminal_reason, result, expires_at, created_at, updated_at
`

type PatchTaskSessionParams struct {
	Metadata      []byte             `json:"metadata"`
	Tags          []string           `json:"tags"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	OrgID         pgtype.UUID        `json:"org_id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	EnvironmentID pgtype.UUID        `json:"environment_id"`
	ID            pgtype.UUID        `json:"id"`
}

func (q *Queries) PatchTaskSession(ctx context.Context, arg PatchTaskSessionParams) (TaskSession, error) {
	row := q.db.QueryRow(ctx, patchTaskSession,
		arg.Metadata,
		arg.Tags,
		arg.ExpiresAt,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ID,
	)
	var i TaskSession
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.TaskID,
		&i.InitialDeploymentID,
		&i.ActiveDeploymentID,
		&i.ExternalID,
		&i.StartFingerprint,
		&i.Status,
		&i.CurrentRunID,
		&i.CurrentRunVersion,
		&i.WorkspaceID,
		&i.Metadata,
		&i.Tags,
		&i.CompletedAt,
		&i.FailedAt,
		&i.ClosedAt,
		&i.ClosedReason,
		&i.CancelledAt,
		&i.TerminalReason,
		&i.Result,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTaskSessionCurrentRun = `-- name: SetTaskSessionCurrentRun :one
UPDATE task_sessions
   SET current_run_id = $1,
       current_run_version = current_run_version + 1,
       updated_at = now()
 WHERE org_id = $2
   AND project_id = $3
   AND environment_id = $4
   AND id = $5
   AND status = 'open'
   AND current_run_id IS NULL
RETURNING id, org_id, project_id, environment_id, task_id, initial_deployment_id, active_deployment_id, external_id, start_fingerprint, status, current_run_id, current_run_version, workspace_id, metadata, tags, completed_at, failed_at, closed_at, closed_reason, cancelled_at, terminal_reason, result, expires_at, created_at, updated_at
`

type SetTaskSessionCurrentRunParams struct {
	RunID         pgtype.UUID `json:"run_id"`
	OrgID         pgtype.UUID `json:"org_id"`
	ProjectID     pgtype.UUID `json:"project_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	TaskSessionID pgtype.UUID `json:"task_session_id"`
}

func (q *Queries) SetTaskSessionCurrentRun(ctx context.Context, arg SetTaskSessionCurrentRunParams) (TaskSession, error) {
	row := q.db.QueryRow(ctx, setTaskSessionCurrentRun,
		arg.RunID,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.TaskSessionID,
	)
	var i TaskSession
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.TaskID,
		&i.InitialDeploymentID,
		&i.ActiveDeploymentID,
		&i.ExternalID,
		&i.StartFingerprint,
		&i.Status,
		&i.CurrentRunID,
		&i.CurrentRunVersion,
		&i.WorkspaceID,
		&i.Metadata,
		&i.Tags,
		&i.CompletedAt,
		&i.FailedAt,
		&i.ClosedAt,
		&i.ClosedReason,
		&i.CancelledAt,
		&i.TerminalReason,
		&i.Result,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchTaskStartIdempotency = `-- name: TouchTaskStartIdempotency :exec
UPDATE task_start_idempotencies
   SET last_used_at = now()
 WHERE org_id = $1
   AND id = $2
`

type TouchTaskStartIdempotencyParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) TouchTaskStartIdempotency(ctx context.Context, arg TouchTaskStartIdempotencyParams) error {
	_, err := q.db.Exec(ctx, touchTaskStartIdempotency, arg.OrgID, arg.ID)
	return err
}
