// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telemetry_outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimEventIngestBatch = `-- name: ClaimEventIngestBatch :many
WITH claimed AS (
    SELECT telemetry_outbox.id
      FROM telemetry_outbox
     WHERE telemetry_outbox.stream_kind = 'event'
       AND telemetry_outbox.written_at IS NULL
       AND telemetry_outbox.state IN ('pending', 'claimed', 'failed')
       AND (telemetry_outbox.next_retry_at IS NULL OR telemetry_outbox.next_retry_at <= now())
     ORDER BY telemetry_outbox.id ASC
     LIMIT $1
     FOR UPDATE SKIP LOCKED
),
updated AS (
    UPDATE telemetry_outbox
       SET state = 'claimed',
           retry_count = telemetry_outbox.retry_count + 1,
           next_retry_at = now() + $2::interval,
           updated_at = now(),
           last_error = ''
      FROM claimed
     WHERE telemetry_outbox.id = claimed.id
    RETURNING telemetry_outbox.id, telemetry_outbox.org_id, telemetry_outbox.cell_id, telemetry_outbox.stream_kind, telemetry_outbox.source_kind, telemetry_outbox.source_id, telemetry_outbox.stream_name, telemetry_outbox.seq, telemetry_outbox.idempotency_key, telemetry_outbox.object_key, telemetry_outbox.cas_digest, telemetry_outbox.state, telemetry_outbox.retry_count, telemetry_outbox.next_retry_at, telemetry_outbox.written_at, telemetry_outbox.published_at, telemetry_outbox.publish_attempts, telemetry_outbox.publish_locked_until, telemetry_outbox.last_error, telemetry_outbox.created_at, telemetry_outbox.updated_at
)
SELECT updated.id AS outbox_id,
       updated.retry_count,
       updated.idempotency_key,
       events.id, events.subject_type, events.subject_id, events.seq, events.org_id, events.cell_id, events.project_id, events.environment_id, events.run_id, events.deployment_id, events.attempt_id, events.run_lease_id, events.attempt_number, events.trace_id, events.span_id, events.parent_span_id, events.traceparent, events.category, events.severity, events.source, events.kind, events.message, events.payload, events.redaction_class, events.snapshot_version, events.expires_at, events.occurred_at, events.created_at
  FROM updated
  JOIN event_hot_payloads AS events ON events.org_id = updated.org_id
                                   AND events.cell_id = updated.cell_id
                                   AND events.subject_type = updated.source_kind::event_subject_type
                                   AND events.subject_id = updated.source_id
                                   AND events.seq = updated.seq
 ORDER BY updated.id ASC
`

type ClaimEventIngestBatchParams struct {
	RowLimit      int32           `json:"row_limit"`
	LeaseDuration pgtype.Interval `json:"lease_duration"`
}

type ClaimEventIngestBatchRow struct {
	OutboxID        int64              `json:"outbox_id"`
	RetryCount      int32              `json:"retry_count"`
	IdempotencyKey  string             `json:"idempotency_key"`
	ID              pgtype.Int8        `json:"id"`
	SubjectType     EventSubjectType   `json:"subject_type"`
	SubjectID       pgtype.UUID        `json:"subject_id"`
	Seq             int64              `json:"seq"`
	OrgID           pgtype.UUID        `json:"org_id"`
	CellID          string             `json:"cell_id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	EnvironmentID   pgtype.UUID        `json:"environment_id"`
	RunID           pgtype.UUID        `json:"run_id"`
	DeploymentID    pgtype.UUID        `json:"deployment_id"`
	AttemptID       pgtype.UUID        `json:"attempt_id"`
	RunLeaseID      pgtype.UUID        `json:"run_lease_id"`
	AttemptNumber   pgtype.Int4        `json:"attempt_number"`
	TraceID         pgtype.Text        `json:"trace_id"`
	SpanID          pgtype.Text        `json:"span_id"`
	ParentSpanID    pgtype.Text        `json:"parent_span_id"`
	Traceparent     pgtype.Text        `json:"traceparent"`
	Category        string             `json:"category"`
	Severity        string             `json:"severity"`
	Source          string             `json:"source"`
	Kind            string             `json:"kind"`
	Message         string             `json:"message"`
	Payload         []byte             `json:"payload"`
	RedactionClass  string             `json:"redaction_class"`
	SnapshotVersion pgtype.Int8        `json:"snapshot_version"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ClaimEventIngestBatch(ctx context.Context, arg ClaimEventIngestBatchParams) ([]ClaimEventIngestBatchRow, error) {
	rows, err := q.db.Query(ctx, claimEventIngestBatch, arg.RowLimit, arg.LeaseDuration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimEventIngestBatchRow
	for rows.Next() {
		var i ClaimEventIngestBatchRow
		if err := rows.Scan(
			&i.OutboxID,
			&i.RetryCount,
			&i.IdempotencyKey,
			&i.ID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Seq,
			&i.OrgID,
			&i.CellID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.RunID,
			&i.DeploymentID,
			&i.AttemptID,
			&i.RunLeaseID,
			&i.AttemptNumber,
			&i.TraceID,
			&i.SpanID,
			&i.ParentSpanID,
			&i.Traceparent,
			&i.Category,
			&i.Severity,
			&i.Source,
			&i.Kind,
			&i.Message,
			&i.Payload,
			&i.RedactionClass,
			&i.SnapshotVersion,
			&i.ExpiresAt,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimRunLogIngestBatch = `-- name: ClaimRunLogIngestBatch :many
WITH claimed AS (
    SELECT telemetry_outbox.id
      FROM telemetry_outbox
     WHERE telemetry_outbox.stream_kind = 'run_log'
       AND telemetry_outbox.written_at IS NULL
       AND telemetry_outbox.state IN ('pending', 'claimed', 'failed')
       AND (telemetry_outbox.next_retry_at IS NULL OR telemetry_outbox.next_retry_at <= now())
     ORDER BY telemetry_outbox.id ASC
     LIMIT $1
     FOR UPDATE SKIP LOCKED
),
updated AS (
    UPDATE telemetry_outbox
       SET state = 'claimed',
           retry_count = telemetry_outbox.retry_count + 1,
           next_retry_at = now() + $2::interval,
           updated_at = now(),
           last_error = ''
      FROM claimed
     WHERE telemetry_outbox.id = claimed.id
    RETURNING telemetry_outbox.id, telemetry_outbox.org_id, telemetry_outbox.cell_id, telemetry_outbox.stream_kind, telemetry_outbox.source_kind, telemetry_outbox.source_id, telemetry_outbox.stream_name, telemetry_outbox.seq, telemetry_outbox.idempotency_key, telemetry_outbox.object_key, telemetry_outbox.cas_digest, telemetry_outbox.state, telemetry_outbox.retry_count, telemetry_outbox.next_retry_at, telemetry_outbox.written_at, telemetry_outbox.published_at, telemetry_outbox.publish_attempts, telemetry_outbox.publish_locked_until, telemetry_outbox.last_error, telemetry_outbox.created_at, telemetry_outbox.updated_at
)
SELECT updated.id AS outbox_id,
       updated.retry_count,
       updated.idempotency_key,
       chunks.org_id,
       chunks.cell_id,
       runs.project_id,
       runs.environment_id,
       chunks.run_id,
       run_leases.attempt_id,
       chunks.run_lease_id,
       chunks.attempt_number,
       chunks.stream,
       chunks.seq,
       chunks.observed_seq,
       chunks.content,
       chunks.size_bytes,
       chunks.created_at
  FROM updated
  JOIN run_log_hot_chunks AS chunks ON chunks.org_id = updated.org_id
                                   AND chunks.cell_id = updated.cell_id
                                   AND chunks.run_id = updated.source_id
                                   AND chunks.stream::text = updated.stream_name
                                   AND chunks.seq = updated.seq
  JOIN runs ON runs.org_id = chunks.org_id
           AND runs.id = chunks.run_id
  JOIN run_leases ON run_leases.org_id = chunks.org_id
                 AND run_leases.run_id = chunks.run_id
                 AND run_leases.id = chunks.run_lease_id
 ORDER BY updated.id ASC
`

type ClaimRunLogIngestBatchParams struct {
	RowLimit      int32           `json:"row_limit"`
	LeaseDuration pgtype.Interval `json:"lease_duration"`
}

type ClaimRunLogIngestBatchRow struct {
	OutboxID       int64              `json:"outbox_id"`
	RetryCount     int32              `json:"retry_count"`
	IdempotencyKey string             `json:"idempotency_key"`
	OrgID          pgtype.UUID        `json:"org_id"`
	CellID         string             `json:"cell_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	EnvironmentID  pgtype.UUID        `json:"environment_id"`
	RunID          pgtype.UUID        `json:"run_id"`
	AttemptID      pgtype.UUID        `json:"attempt_id"`
	RunLeaseID     pgtype.UUID        `json:"run_lease_id"`
	AttemptNumber  int32              `json:"attempt_number"`
	Stream         RunLogStream       `json:"stream"`
	Seq            int64              `json:"seq"`
	ObservedSeq    int64              `json:"observed_seq"`
	Content        []byte             `json:"content"`
	SizeBytes      int64              `json:"size_bytes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ClaimRunLogIngestBatch(ctx context.Context, arg ClaimRunLogIngestBatchParams) ([]ClaimRunLogIngestBatchRow, error) {
	rows, err := q.db.Query(ctx, claimRunLogIngestBatch, arg.RowLimit, arg.LeaseDuration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimRunLogIngestBatchRow
	for rows.Next() {
		var i ClaimRunLogIngestBatchRow
		if err := rows.Scan(
			&i.OutboxID,
			&i.RetryCount,
			&i.IdempotencyKey,
			&i.OrgID,
			&i.CellID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.RunID,
			&i.AttemptID,
			&i.RunLeaseID,
			&i.AttemptNumber,
			&i.Stream,
			&i.Seq,
			&i.ObservedSeq,
			&i.Content,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimWorkspaceExecTerminalOutputIngestBatch = `-- name: ClaimWorkspaceExecTerminalOutputIngestBatch :many
WITH claimed AS (
    SELECT telemetry_outbox.id
      FROM telemetry_outbox
     WHERE telemetry_outbox.stream_kind = 'terminal_output'
       AND telemetry_outbox.source_kind = 'workspace_exec'
       AND telemetry_outbox.written_at IS NULL
       AND telemetry_outbox.state IN ('pending', 'claimed', 'failed')
       AND (telemetry_outbox.next_retry_at IS NULL OR telemetry_outbox.next_retry_at <= now())
       AND EXISTS (
             SELECT 1
               FROM workspace_exec_stream_chunks AS chunks
              WHERE chunks.org_id = telemetry_outbox.org_id
                AND chunks.cell_id = telemetry_outbox.cell_id
                AND chunks.exec_id = telemetry_outbox.source_id
                AND chunks.stream::text = telemetry_outbox.stream_name
                AND chunks.offset_start = telemetry_outbox.seq
       )
     ORDER BY telemetry_outbox.id ASC
     LIMIT $1
     FOR UPDATE SKIP LOCKED
),
updated AS (
    UPDATE telemetry_outbox
       SET state = 'claimed',
           retry_count = telemetry_outbox.retry_count + 1,
           next_retry_at = now() + $2::interval,
           updated_at = now(),
           last_error = ''
      FROM claimed
     WHERE telemetry_outbox.id = claimed.id
    RETURNING telemetry_outbox.id, telemetry_outbox.org_id, telemetry_outbox.cell_id, telemetry_outbox.stream_kind, telemetry_outbox.source_kind, telemetry_outbox.source_id, telemetry_outbox.stream_name, telemetry_outbox.seq, telemetry_outbox.idempotency_key, telemetry_outbox.object_key, telemetry_outbox.cas_digest, telemetry_outbox.state, telemetry_outbox.retry_count, telemetry_outbox.next_retry_at, telemetry_outbox.written_at, telemetry_outbox.published_at, telemetry_outbox.publish_attempts, telemetry_outbox.publish_locked_until, telemetry_outbox.last_error, telemetry_outbox.created_at, telemetry_outbox.updated_at
)
SELECT updated.id AS outbox_id,
       updated.retry_count,
       updated.idempotency_key,
       chunks.org_id,
       chunks.cell_id,
       chunks.project_id,
       chunks.environment_id,
       chunks.workspace_id,
       'workspace_exec'::text AS resource_kind,
       chunks.exec_id AS resource_id,
       chunks.stream::text AS stream_name,
       chunks.offset_start,
       chunks.offset_end,
       chunks.data,
       chunks.observed_at
  FROM updated
  JOIN workspace_exec_stream_chunks AS chunks ON chunks.org_id = updated.org_id
                                             AND chunks.cell_id = updated.cell_id
                                             AND chunks.exec_id = updated.source_id
                                             AND chunks.stream::text = updated.stream_name
                                             AND chunks.offset_start = updated.seq
 ORDER BY updated.id ASC
`

type ClaimWorkspaceExecTerminalOutputIngestBatchParams struct {
	RowLimit      int32           `json:"row_limit"`
	LeaseDuration pgtype.Interval `json:"lease_duration"`
}

type ClaimWorkspaceExecTerminalOutputIngestBatchRow struct {
	OutboxID       int64              `json:"outbox_id"`
	RetryCount     int32              `json:"retry_count"`
	IdempotencyKey string             `json:"idempotency_key"`
	OrgID          pgtype.UUID        `json:"org_id"`
	CellID         string             `json:"cell_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	EnvironmentID  pgtype.UUID        `json:"environment_id"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	ResourceKind   string             `json:"resource_kind"`
	ResourceID     pgtype.UUID        `json:"resource_id"`
	StreamName     string             `json:"stream_name"`
	OffsetStart    int64              `json:"offset_start"`
	OffsetEnd      int64              `json:"offset_end"`
	Data           []byte             `json:"data"`
	ObservedAt     pgtype.Timestamptz `json:"observed_at"`
}

func (q *Queries) ClaimWorkspaceExecTerminalOutputIngestBatch(ctx context.Context, arg ClaimWorkspaceExecTerminalOutputIngestBatchParams) ([]ClaimWorkspaceExecTerminalOutputIngestBatchRow, error) {
	rows, err := q.db.Query(ctx, claimWorkspaceExecTerminalOutputIngestBatch, arg.RowLimit, arg.LeaseDuration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimWorkspaceExecTerminalOutputIngestBatchRow
	for rows.Next() {
		var i ClaimWorkspaceExecTerminalOutputIngestBatchRow
		if err := rows.Scan(
			&i.OutboxID,
			&i.RetryCount,
			&i.IdempotencyKey,
			&i.OrgID,
			&i.CellID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.WorkspaceID,
			&i.ResourceKind,
			&i.ResourceID,
			&i.StreamName,
			&i.OffsetStart,
			&i.OffsetEnd,
			&i.Data,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimWorkspacePtyTerminalOutputIngestBatch = `-- name: ClaimWorkspacePtyTerminalOutputIngestBatch :many
WITH claimed AS (
    SELECT telemetry_outbox.id
      FROM telemetry_outbox
     WHERE telemetry_outbox.stream_kind = 'terminal_output'
       AND telemetry_outbox.source_kind = 'workspace_pty'
       AND telemetry_outbox.written_at IS NULL
       AND telemetry_outbox.state IN ('pending', 'claimed', 'failed')
       AND (telemetry_outbox.next_retry_at IS NULL OR telemetry_outbox.next_retry_at <= now())
       AND EXISTS (
             SELECT 1
               FROM workspace_pty_stream_chunks AS chunks
              WHERE chunks.org_id = telemetry_outbox.org_id
                AND chunks.cell_id = telemetry_outbox.cell_id
                AND chunks.pty_session_id = telemetry_outbox.source_id
                AND chunks.stream::text = telemetry_outbox.stream_name
                AND chunks.offset_start = telemetry_outbox.seq
       )
     ORDER BY telemetry_outbox.id ASC
     LIMIT $1
     FOR UPDATE SKIP LOCKED
),
updated AS (
    UPDATE telemetry_outbox
       SET state = 'claimed',
           retry_count = telemetry_outbox.retry_count + 1,
           next_retry_at = now() + $2::interval,
           updated_at = now(),
           last_error = ''
      FROM claimed
     WHERE telemetry_outbox.id = claimed.id
    RETURNING telemetry_outbox.id, telemetry_outbox.org_id, telemetry_outbox.cell_id, telemetry_outbox.stream_kind, telemetry_outbox.source_kind, telemetry_outbox.source_id, telemetry_outbox.stream_name, telemetry_outbox.seq, telemetry_outbox.idempotency_key, telemetry_outbox.object_key, telemetry_outbox.cas_digest, telemetry_outbox.state, telemetry_outbox.retry_count, telemetry_outbox.next_retry_at, telemetry_outbox.written_at, telemetry_outbox.published_at, telemetry_outbox.publish_attempts, telemetry_outbox.publish_locked_until, telemetry_outbox.last_error, telemetry_outbox.created_at, telemetry_outbox.updated_at
)
SELECT updated.id AS outbox_id,
       updated.retry_count,
       updated.idempotency_key,
       chunks.org_id,
       chunks.cell_id,
       chunks.project_id,
       chunks.environment_id,
       chunks.workspace_id,
       'workspace_pty'::text AS resource_kind,
       chunks.pty_session_id AS resource_id,
       chunks.stream::text AS stream_name,
       chunks.offset_start,
       chunks.offset_end,
       chunks.data,
       chunks.observed_at
  FROM updated
  JOIN workspace_pty_stream_chunks AS chunks ON chunks.org_id = updated.org_id
                                            AND chunks.cell_id = updated.cell_id
                                            AND chunks.pty_session_id = updated.source_id
                                            AND chunks.stream::text = updated.stream_name
                                            AND chunks.offset_start = updated.seq
 ORDER BY updated.id ASC
`

type ClaimWorkspacePtyTerminalOutputIngestBatchParams struct {
	RowLimit      int32           `json:"row_limit"`
	LeaseDuration pgtype.Interval `json:"lease_duration"`
}

type ClaimWorkspacePtyTerminalOutputIngestBatchRow struct {
	OutboxID       int64              `json:"outbox_id"`
	RetryCount     int32              `json:"retry_count"`
	IdempotencyKey string             `json:"idempotency_key"`
	OrgID          pgtype.UUID        `json:"org_id"`
	CellID         string             `json:"cell_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	EnvironmentID  pgtype.UUID        `json:"environment_id"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	ResourceKind   string             `json:"resource_kind"`
	ResourceID     pgtype.UUID        `json:"resource_id"`
	StreamName     string             `json:"stream_name"`
	OffsetStart    int64              `json:"offset_start"`
	OffsetEnd      int64              `json:"offset_end"`
	Data           []byte             `json:"data"`
	ObservedAt     pgtype.Timestamptz `json:"observed_at"`
}

func (q *Queries) ClaimWorkspacePtyTerminalOutputIngestBatch(ctx context.Context, arg ClaimWorkspacePtyTerminalOutputIngestBatchParams) ([]ClaimWorkspacePtyTerminalOutputIngestBatchRow, error) {
	rows, err := q.db.Query(ctx, claimWorkspacePtyTerminalOutputIngestBatch, arg.RowLimit, arg.LeaseDuration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimWorkspacePtyTerminalOutputIngestBatchRow
	for rows.Next() {
		var i ClaimWorkspacePtyTerminalOutputIngestBatchRow
		if err := rows.Scan(
			&i.OutboxID,
			&i.RetryCount,
			&i.IdempotencyKey,
			&i.OrgID,
			&i.CellID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.WorkspaceID,
			&i.ResourceKind,
			&i.ResourceID,
			&i.StreamName,
			&i.OffsetStart,
			&i.OffsetEnd,
			&i.Data,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deadLetterOrphanedTelemetryOutbox = `-- name: DeadLetterOrphanedTelemetryOutbox :many
WITH candidates AS (
    SELECT telemetry_outbox.id
      FROM telemetry_outbox
     WHERE telemetry_outbox.written_at IS NULL
       AND telemetry_outbox.state IN ('pending', 'claimed', 'failed')
       AND (
            (
                telemetry_outbox.stream_kind = 'event'
                AND telemetry_outbox.source_kind IN ('run', 'deployment')
                AND NOT EXISTS (
                    SELECT 1
                      FROM event_hot_payloads AS events
                     WHERE events.org_id = telemetry_outbox.org_id
                       AND events.cell_id = telemetry_outbox.cell_id
                       AND events.subject_type = telemetry_outbox.source_kind::event_subject_type
                       AND events.subject_id = telemetry_outbox.source_id
                       AND events.seq = telemetry_outbox.seq
                )
            )
            OR (
                telemetry_outbox.stream_kind = 'run_log'
                AND NOT EXISTS (
                    SELECT 1
                      FROM run_log_hot_chunks AS chunks
                     WHERE chunks.org_id = telemetry_outbox.org_id
                       AND chunks.cell_id = telemetry_outbox.cell_id
                       AND chunks.run_id = telemetry_outbox.source_id
                       AND chunks.stream::text = telemetry_outbox.stream_name
                       AND chunks.seq = telemetry_outbox.seq
                )
            )
            OR (
                telemetry_outbox.stream_kind = 'terminal_output'
                AND telemetry_outbox.source_kind = 'workspace_exec'
                AND NOT EXISTS (
                    SELECT 1
                      FROM workspace_exec_stream_chunks AS chunks
                     WHERE chunks.org_id = telemetry_outbox.org_id
                       AND chunks.cell_id = telemetry_outbox.cell_id
                       AND chunks.exec_id = telemetry_outbox.source_id
                       AND chunks.stream::text = telemetry_outbox.stream_name
                       AND chunks.offset_start = telemetry_outbox.seq
                )
            )
            OR (
                telemetry_outbox.stream_kind = 'terminal_output'
                AND telemetry_outbox.source_kind = 'workspace_pty'
                AND NOT EXISTS (
                    SELECT 1
                      FROM workspace_pty_stream_chunks AS chunks
                     WHERE chunks.org_id = telemetry_outbox.org_id
                       AND chunks.cell_id = telemetry_outbox.cell_id
                       AND chunks.pty_session_id = telemetry_outbox.source_id
                       AND chunks.stream::text = telemetry_outbox.stream_name
                       AND chunks.offset_start = telemetry_outbox.seq
                )
            )
       )
     ORDER BY telemetry_outbox.id ASC
     LIMIT $1
     FOR UPDATE SKIP LOCKED
),
dead_lettered AS (
    UPDATE telemetry_outbox
       SET state = 'dead_lettered',
           next_retry_at = NULL,
           updated_at = now(),
           last_error = 'telemetry payload missing'
      FROM candidates
     WHERE telemetry_outbox.id = candidates.id
       AND telemetry_outbox.written_at IS NULL
    RETURNING telemetry_outbox.id, telemetry_outbox.org_id, telemetry_outbox.cell_id, telemetry_outbox.stream_kind, telemetry_outbox.source_kind, telemetry_outbox.source_id, telemetry_outbox.stream_name, telemetry_outbox.seq, telemetry_outbox.idempotency_key, telemetry_outbox.object_key, telemetry_outbox.cas_digest, telemetry_outbox.state, telemetry_outbox.retry_count, telemetry_outbox.next_retry_at, telemetry_outbox.written_at, telemetry_outbox.published_at, telemetry_outbox.publish_attempts, telemetry_outbox.publish_locked_until, telemetry_outbox.last_error, telemetry_outbox.created_at, telemetry_outbox.updated_at
),
replay_errors AS (
    INSERT INTO telemetry_replay_errors (org_id, cell_id, stream_kind, source_kind, source_id, stream_name, seq, state, retry_count, last_error, next_retry_at)
    SELECT org_id,
           cell_id,
           stream_kind,
           source_kind,
           source_id,
           stream_name,
           seq,
           'dead_lettered',
           retry_count,
           last_error,
           NULL
      FROM dead_lettered
    RETURNING id
)
SELECT dead_lettered.id
  FROM dead_lettered
 ORDER BY dead_lettered.id
`

func (q *Queries) DeadLetterOrphanedTelemetryOutbox(ctx context.Context, rowLimit int32) ([]int64, error) {
	rows, err := q.db.Query(ctx, deadLetterOrphanedTelemetryOutbox, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deadLetterTelemetryOutbox = `-- name: DeadLetterTelemetryOutbox :exec
WITH dead_lettered AS (
    UPDATE telemetry_outbox
       SET state = 'dead_lettered',
           next_retry_at = NULL,
           updated_at = now(),
           last_error = $1
     WHERE telemetry_outbox.id = $2
       AND telemetry_outbox.written_at IS NULL
    RETURNING id, org_id, cell_id, stream_kind, source_kind, source_id, stream_name, seq, idempotency_key, object_key, cas_digest, state, retry_count, next_retry_at, written_at, published_at, publish_attempts, publish_locked_until, last_error, created_at, updated_at
)
INSERT INTO telemetry_replay_errors (org_id, cell_id, stream_kind, source_kind, source_id, stream_name, seq, state, retry_count, last_error, next_retry_at)
SELECT org_id,
       cell_id,
       stream_kind,
       source_kind,
       source_id,
       stream_name,
       seq,
       'retryable',
       retry_count,
       last_error,
       NULL
  FROM dead_lettered
`

type DeadLetterTelemetryOutboxParams struct {
	LastError string `json:"last_error"`
	ID        int64  `json:"id"`
}

func (q *Queries) DeadLetterTelemetryOutbox(ctx context.Context, arg DeadLetterTelemetryOutboxParams) error {
	_, err := q.db.Exec(ctx, deadLetterTelemetryOutbox, arg.LastError, arg.ID)
	return err
}

const getRunLogIngestFrontier = `-- name: GetRunLogIngestFrontier :one
SELECT COALESCE(
    (
        SELECT MIN(seq) - 1
          FROM telemetry_outbox
         WHERE org_id = $1
           AND cell_id = $2
           AND stream_kind = 'run_log'
           AND source_kind = 'run'
           AND source_id = $3
           AND written_at IS NULL
           AND state <> 'dead_lettered'
    ),
    $4::bigint
)::bigint AS watermark_seq
`

type GetRunLogIngestFrontierParams struct {
	OrgID         pgtype.UUID `json:"org_id"`
	CellID        string      `json:"cell_id"`
	RunID         pgtype.UUID `json:"run_id"`
	MaxWrittenSeq int64       `json:"max_written_seq"`
}

func (q *Queries) GetRunLogIngestFrontier(ctx context.Context, arg GetRunLogIngestFrontierParams) (int64, error) {
	row := q.db.QueryRow(ctx, getRunLogIngestFrontier,
		arg.OrgID,
		arg.CellID,
		arg.RunID,
		arg.MaxWrittenSeq,
	)
	var watermark_seq int64
	err := row.Scan(&watermark_seq)
	return watermark_seq, err
}

const getTelemetryIngestFrontier = `-- name: GetTelemetryIngestFrontier :one
SELECT COALESCE(
    (
        SELECT MIN(seq) - 1
                 FROM telemetry_outbox
                WHERE org_id = $1
                  AND cell_id = $2
                  AND stream_kind = $3::telemetry_stream_kind
                  AND source_kind = $4
                  AND source_id = $5
                  AND stream_name = $6
                  AND written_at IS NULL
                  AND state <> 'dead_lettered'
           ),
    $7::bigint
)::bigint AS watermark_seq
`

type GetTelemetryIngestFrontierParams struct {
	OrgID         pgtype.UUID         `json:"org_id"`
	CellID        string              `json:"cell_id"`
	StreamKind    TelemetryStreamKind `json:"stream_kind"`
	SourceKind    string              `json:"source_kind"`
	SourceID      pgtype.UUID         `json:"source_id"`
	StreamName    string              `json:"stream_name"`
	MaxWrittenSeq int64               `json:"max_written_seq"`
}

func (q *Queries) GetTelemetryIngestFrontier(ctx context.Context, arg GetTelemetryIngestFrontierParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTelemetryIngestFrontier,
		arg.OrgID,
		arg.CellID,
		arg.StreamKind,
		arg.SourceKind,
		arg.SourceID,
		arg.StreamName,
		arg.MaxWrittenSeq,
	)
	var watermark_seq int64
	err := row.Scan(&watermark_seq)
	return watermark_seq, err
}

const getTerminalOutputIngestFrontier = `-- name: GetTerminalOutputIngestFrontier :one
SELECT COALESCE(
    (
        SELECT MIN(seq)
          FROM telemetry_outbox
         WHERE org_id = $1
           AND cell_id = $2
           AND stream_kind = 'terminal_output'
           AND source_kind = $3
           AND source_id = $4
           AND stream_name = $5
           AND written_at IS NULL
           AND state <> 'dead_lettered'
    ),
    $6::bigint
)::bigint AS watermark_offset
`

type GetTerminalOutputIngestFrontierParams struct {
	OrgID            pgtype.UUID `json:"org_id"`
	CellID           string      `json:"cell_id"`
	SourceKind       string      `json:"source_kind"`
	SourceID         pgtype.UUID `json:"source_id"`
	StreamName       string      `json:"stream_name"`
	MaxWrittenOffset int64       `json:"max_written_offset"`
}

func (q *Queries) GetTerminalOutputIngestFrontier(ctx context.Context, arg GetTerminalOutputIngestFrontierParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTerminalOutputIngestFrontier,
		arg.OrgID,
		arg.CellID,
		arg.SourceKind,
		arg.SourceID,
		arg.StreamName,
		arg.MaxWrittenOffset,
	)
	var watermark_offset int64
	err := row.Scan(&watermark_offset)
	return watermark_offset, err
}

const listDeadLetteredTelemetrySeqs = `-- name: ListDeadLetteredTelemetrySeqs :many
SELECT telemetry_outbox.seq
  FROM telemetry_outbox
 WHERE telemetry_outbox.org_id = $1
   AND telemetry_outbox.cell_id = $2
   AND telemetry_outbox.stream_kind = $3::telemetry_stream_kind
   AND telemetry_outbox.source_kind = $4
   AND telemetry_outbox.source_id = $5
   AND (
        $6::text = ''
        OR telemetry_outbox.stream_name = $6::text
   )
   AND telemetry_outbox.seq > $7
   AND telemetry_outbox.seq <= $8
   AND telemetry_outbox.state = 'dead_lettered'
UNION
SELECT telemetry_replay_errors.seq
  FROM telemetry_replay_errors
 WHERE telemetry_replay_errors.org_id = $1
   AND telemetry_replay_errors.cell_id = $2
   AND telemetry_replay_errors.stream_kind = $3::telemetry_stream_kind
   AND telemetry_replay_errors.source_kind = $4
   AND telemetry_replay_errors.source_id = $5
   AND (
        $6::text = ''
        OR telemetry_replay_errors.stream_name = $6::text
   )
   AND telemetry_replay_errors.seq > $7
   AND telemetry_replay_errors.seq <= $8
   AND telemetry_replay_errors.state = 'dead_lettered'
ORDER BY seq
`

type ListDeadLetteredTelemetrySeqsParams struct {
	OrgID        pgtype.UUID         `json:"org_id"`
	CellID       string              `json:"cell_id"`
	StreamKind   TelemetryStreamKind `json:"stream_kind"`
	SourceKind   string              `json:"source_kind"`
	SourceID     pgtype.UUID         `json:"source_id"`
	StreamName   string              `json:"stream_name"`
	AfterSeq     int64               `json:"after_seq"`
	WatermarkSeq int64               `json:"watermark_seq"`
}

func (q *Queries) ListDeadLetteredTelemetrySeqs(ctx context.Context, arg ListDeadLetteredTelemetrySeqsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listDeadLetteredTelemetrySeqs,
		arg.OrgID,
		arg.CellID,
		arg.StreamKind,
		arg.SourceKind,
		arg.SourceID,
		arg.StreamName,
		arg.AfterSeq,
		arg.WatermarkSeq,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var seq int64
		if err := rows.Scan(&seq); err != nil {
			return nil, err
		}
		items = append(items, seq)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTelemetryOutboxBatchFailed = `-- name: MarkTelemetryOutboxBatchFailed :exec
UPDATE telemetry_outbox
   SET state = 'failed',
       next_retry_at = now() + $1::interval,
       updated_at = now(),
       last_error = $2
 WHERE id = ANY($3::bigint[])
   AND written_at IS NULL
`

type MarkTelemetryOutboxBatchFailedParams struct {
	RetryAfter pgtype.Interval `json:"retry_after"`
	LastError  string          `json:"last_error"`
	Ids        []int64         `json:"ids"`
}

func (q *Queries) MarkTelemetryOutboxBatchFailed(ctx context.Context, arg MarkTelemetryOutboxBatchFailedParams) error {
	_, err := q.db.Exec(ctx, markTelemetryOutboxBatchFailed, arg.RetryAfter, arg.LastError, arg.Ids)
	return err
}

const markTelemetryOutboxWritten = `-- name: MarkTelemetryOutboxWritten :exec
UPDATE telemetry_outbox
   SET state = 'written',
       written_at = now(),
       retry_count = 0,
       next_retry_at = NULL,
       updated_at = now(),
       last_error = ''
 WHERE id = ANY($1::bigint[])
`

func (q *Queries) MarkTelemetryOutboxWritten(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, markTelemetryOutboxWritten, ids)
	return err
}

const pruneTelemetryOutboxWritten = `-- name: PruneTelemetryOutboxWritten :many
DELETE FROM telemetry_outbox
 WHERE (
        (
            written_at IS NOT NULL
            AND (stream_kind <> 'event' OR published_at IS NOT NULL)
            AND written_at < now() - $1::interval
        )
        OR (
            state = 'dead_lettered'
            AND updated_at < now() - $1::interval
        )
 )
RETURNING id
`

func (q *Queries) PruneTelemetryOutboxWritten(ctx context.Context, retainFor pgtype.Interval) ([]int64, error) {
	rows, err := q.db.Query(ctx, pruneTelemetryOutboxWritten, retainFor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueWrittenTelemetryOutbox = `-- name: RequeueWrittenTelemetryOutbox :exec
UPDATE telemetry_outbox
   SET state = 'failed',
       written_at = NULL,
       next_retry_at = now() + $1::interval,
       updated_at = now(),
       last_error = $2
 WHERE id = ANY($3::bigint[])
   AND written_at IS NOT NULL
`

type RequeueWrittenTelemetryOutboxParams struct {
	RetryAfter pgtype.Interval `json:"retry_after"`
	LastError  string          `json:"last_error"`
	Ids        []int64         `json:"ids"`
}

func (q *Queries) RequeueWrittenTelemetryOutbox(ctx context.Context, arg RequeueWrittenTelemetryOutboxParams) error {
	_, err := q.db.Exec(ctx, requeueWrittenTelemetryOutbox, arg.RetryAfter, arg.LastError, arg.Ids)
	return err
}
