// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telemetry_outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimEventIngestBatch = `-- name: ClaimEventIngestBatch :many
WITH candidates AS (
    SELECT telemetry_outbox.id,
           octet_length(telemetry_outbox.message)::bigint
               + octet_length(telemetry_outbox.payload::text)::bigint AS size_bytes
      FROM telemetry_outbox
     WHERE telemetry_outbox.stream_kind = 'event'
       AND telemetry_outbox.written_at IS NULL
       AND telemetry_outbox.state IN ('pending', 'claimed', 'failed')
       AND (telemetry_outbox.next_retry_at IS NULL OR telemetry_outbox.next_retry_at <= now())
     ORDER BY telemetry_outbox.id ASC
     LIMIT $1
     FOR UPDATE SKIP LOCKED
),
claimed AS (
    SELECT sized.id
      FROM (
          SELECT candidates.id,
                 SUM(candidates.size_bytes) OVER (ORDER BY candidates.id ASC) AS cumulative_size_bytes
            FROM candidates
      ) AS sized
     WHERE sized.cumulative_size_bytes <= $2::bigint
),
updated AS (
    UPDATE telemetry_outbox
       SET state = 'claimed',
           retry_count = telemetry_outbox.retry_count + 1,
           next_retry_at = now() + $3::interval,
           updated_at = now()
      FROM claimed
     WHERE telemetry_outbox.id = claimed.id
    RETURNING telemetry_outbox.id, telemetry_outbox.org_id, telemetry_outbox.stream_kind, telemetry_outbox.source_kind, telemetry_outbox.source_id, telemetry_outbox.stream_name, telemetry_outbox.idempotency_key, telemetry_outbox.project_id, telemetry_outbox.environment_id, telemetry_outbox.run_id, telemetry_outbox.deployment_id, telemetry_outbox.run_lease_id, telemetry_outbox.attempt_number, telemetry_outbox.trace_id, telemetry_outbox.span_id, telemetry_outbox.parent_span_id, telemetry_outbox.traceparent, telemetry_outbox.category, telemetry_outbox.severity, telemetry_outbox.source, telemetry_outbox.kind, telemetry_outbox.message, telemetry_outbox.payload, telemetry_outbox.content, telemetry_outbox.size_bytes, telemetry_outbox.observed_seq, telemetry_outbox.redaction_class, telemetry_outbox.retention_class, telemetry_outbox.snapshot_version, telemetry_outbox.state, telemetry_outbox.retry_count, telemetry_outbox.next_retry_at, telemetry_outbox.written_at, telemetry_outbox.published_at, telemetry_outbox.publish_attempts, telemetry_outbox.publish_locked_until, telemetry_outbox.ingest_error, telemetry_outbox.publish_error, telemetry_outbox.observed_at, telemetry_outbox.created_at, telemetry_outbox.updated_at
)
SELECT updated.id AS outbox_id,
       updated.retry_count,
       COALESCE(updated.idempotency_key, '')::text AS idempotency_key,
       updated.source_kind AS subject_type,
       updated.source_id AS subject_id,
       updated.id AS seq,
       updated.org_id,
       updated.project_id,
       updated.environment_id,
       updated.run_id,
       updated.deployment_id,
       updated.run_lease_id,
       updated.attempt_number,
       updated.trace_id,
       updated.span_id,
       updated.parent_span_id,
       updated.traceparent,
       updated.category,
       updated.severity,
       updated.source,
       updated.kind,
       updated.message,
       updated.payload,
       updated.redaction_class,
       updated.snapshot_version,
       updated.observed_at AS occurred_at,
       updated.created_at
  FROM updated
 ORDER BY updated.id ASC
`

type ClaimEventIngestBatchParams struct {
	RowLimit      int32           `json:"row_limit"`
	MaxBatchBytes int64           `json:"max_batch_bytes"`
	LeaseDuration pgtype.Interval `json:"lease_duration"`
}

type ClaimEventIngestBatchRow struct {
	OutboxID        int64              `json:"outbox_id"`
	RetryCount      int32              `json:"retry_count"`
	IdempotencyKey  string             `json:"idempotency_key"`
	SubjectType     string             `json:"subject_type"`
	SubjectID       pgtype.UUID        `json:"subject_id"`
	Seq             int64              `json:"seq"`
	OrgID           pgtype.UUID        `json:"org_id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	EnvironmentID   pgtype.UUID        `json:"environment_id"`
	RunID           pgtype.UUID        `json:"run_id"`
	DeploymentID    pgtype.UUID        `json:"deployment_id"`
	RunLeaseID      pgtype.UUID        `json:"run_lease_id"`
	AttemptNumber   pgtype.Int4        `json:"attempt_number"`
	TraceID         pgtype.Text        `json:"trace_id"`
	SpanID          pgtype.Text        `json:"span_id"`
	ParentSpanID    pgtype.Text        `json:"parent_span_id"`
	Traceparent     pgtype.Text        `json:"traceparent"`
	Category        string             `json:"category"`
	Severity        string             `json:"severity"`
	Source          string             `json:"source"`
	Kind            string             `json:"kind"`
	Message         string             `json:"message"`
	Payload         []byte             `json:"payload"`
	RedactionClass  string             `json:"redaction_class"`
	SnapshotVersion pgtype.Int8        `json:"snapshot_version"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ClaimEventIngestBatch(ctx context.Context, arg ClaimEventIngestBatchParams) ([]ClaimEventIngestBatchRow, error) {
	rows, err := q.db.Query(ctx, claimEventIngestBatch, arg.RowLimit, arg.MaxBatchBytes, arg.LeaseDuration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimEventIngestBatchRow
	for rows.Next() {
		var i ClaimEventIngestBatchRow
		if err := rows.Scan(
			&i.OutboxID,
			&i.RetryCount,
			&i.IdempotencyKey,
			&i.SubjectType,
			&i.SubjectID,
			&i.Seq,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.RunID,
			&i.DeploymentID,
			&i.RunLeaseID,
			&i.AttemptNumber,
			&i.TraceID,
			&i.SpanID,
			&i.ParentSpanID,
			&i.Traceparent,
			&i.Category,
			&i.Severity,
			&i.Source,
			&i.Kind,
			&i.Message,
			&i.Payload,
			&i.RedactionClass,
			&i.SnapshotVersion,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimLiveTelemetryOutbox = `-- name: ClaimLiveTelemetryOutbox :many
WITH claimed AS (
    SELECT telemetry_outbox.id
      FROM telemetry_outbox
     WHERE telemetry_outbox.stream_kind = 'event'
       AND telemetry_outbox.published_at IS NULL
       AND (telemetry_outbox.publish_locked_until IS NULL OR telemetry_outbox.publish_locked_until < now())
       AND NOT EXISTS (
            SELECT 1
              FROM telemetry_outbox AS earlier_outbox
             WHERE earlier_outbox.stream_kind = 'event'
               AND earlier_outbox.published_at IS NULL
               AND earlier_outbox.org_id = telemetry_outbox.org_id
               AND earlier_outbox.source_kind = telemetry_outbox.source_kind
               AND earlier_outbox.source_id = telemetry_outbox.source_id
               AND earlier_outbox.id < telemetry_outbox.id
       )
     ORDER BY telemetry_outbox.id ASC
     LIMIT $1
     FOR UPDATE SKIP LOCKED
),
updated AS (
    UPDATE telemetry_outbox
       SET publish_locked_until = now() + $2::interval,
           publish_attempts = telemetry_outbox.publish_attempts + 1,
           updated_at = now()
      FROM claimed
     WHERE telemetry_outbox.id = claimed.id
    RETURNING telemetry_outbox.id, telemetry_outbox.org_id, telemetry_outbox.stream_kind, telemetry_outbox.source_kind, telemetry_outbox.source_id, telemetry_outbox.stream_name, telemetry_outbox.idempotency_key, telemetry_outbox.project_id, telemetry_outbox.environment_id, telemetry_outbox.run_id, telemetry_outbox.deployment_id, telemetry_outbox.run_lease_id, telemetry_outbox.attempt_number, telemetry_outbox.trace_id, telemetry_outbox.span_id, telemetry_outbox.parent_span_id, telemetry_outbox.traceparent, telemetry_outbox.category, telemetry_outbox.severity, telemetry_outbox.source, telemetry_outbox.kind, telemetry_outbox.message, telemetry_outbox.payload, telemetry_outbox.content, telemetry_outbox.size_bytes, telemetry_outbox.observed_seq, telemetry_outbox.redaction_class, telemetry_outbox.retention_class, telemetry_outbox.snapshot_version, telemetry_outbox.state, telemetry_outbox.retry_count, telemetry_outbox.next_retry_at, telemetry_outbox.written_at, telemetry_outbox.published_at, telemetry_outbox.publish_attempts, telemetry_outbox.publish_locked_until, telemetry_outbox.ingest_error, telemetry_outbox.publish_error, telemetry_outbox.observed_at, telemetry_outbox.created_at, telemetry_outbox.updated_at
)
SELECT updated.id AS outbox_id,
       updated.stream_kind,
       ('helmr:events:' || updated.org_id::text || ':' || updated.source_kind || ':' || updated.source_id::text)::text AS stream_key,
       updated.publish_attempts AS attempts,
       updated.id AS seq,
       updated.org_id,
       updated.project_id,
       updated.environment_id,
       updated.source_kind,
       updated.source_id,
       updated.stream_name,
       updated.run_id,
       updated.deployment_id,
       updated.run_lease_id,
       updated.attempt_number,
       updated.trace_id,
       updated.span_id,
       updated.parent_span_id,
       updated.traceparent,
       updated.category,
       updated.severity,
       updated.source,
       updated.kind,
       updated.message,
       updated.payload,
       updated.redaction_class,
       updated.snapshot_version,
       updated.observed_at AS occurred_at,
       updated.created_at
  FROM updated
 ORDER BY updated.id ASC
`

type ClaimLiveTelemetryOutboxParams struct {
	RowLimit      int32           `json:"row_limit"`
	LeaseDuration pgtype.Interval `json:"lease_duration"`
}

type ClaimLiveTelemetryOutboxRow struct {
	OutboxID        int64               `json:"outbox_id"`
	StreamKind      TelemetryStreamKind `json:"stream_kind"`
	StreamKey       string              `json:"stream_key"`
	Attempts        int32               `json:"attempts"`
	Seq             int64               `json:"seq"`
	OrgID           pgtype.UUID         `json:"org_id"`
	ProjectID       pgtype.UUID         `json:"project_id"`
	EnvironmentID   pgtype.UUID         `json:"environment_id"`
	SourceKind      string              `json:"source_kind"`
	SourceID        pgtype.UUID         `json:"source_id"`
	StreamName      string              `json:"stream_name"`
	RunID           pgtype.UUID         `json:"run_id"`
	DeploymentID    pgtype.UUID         `json:"deployment_id"`
	RunLeaseID      pgtype.UUID         `json:"run_lease_id"`
	AttemptNumber   pgtype.Int4         `json:"attempt_number"`
	TraceID         pgtype.Text         `json:"trace_id"`
	SpanID          pgtype.Text         `json:"span_id"`
	ParentSpanID    pgtype.Text         `json:"parent_span_id"`
	Traceparent     pgtype.Text         `json:"traceparent"`
	Category        string              `json:"category"`
	Severity        string              `json:"severity"`
	Source          string              `json:"source"`
	Kind            string              `json:"kind"`
	Message         string              `json:"message"`
	Payload         []byte              `json:"payload"`
	RedactionClass  string              `json:"redaction_class"`
	SnapshotVersion pgtype.Int8         `json:"snapshot_version"`
	OccurredAt      pgtype.Timestamptz  `json:"occurred_at"`
	CreatedAt       pgtype.Timestamptz  `json:"created_at"`
}

func (q *Queries) ClaimLiveTelemetryOutbox(ctx context.Context, arg ClaimLiveTelemetryOutboxParams) ([]ClaimLiveTelemetryOutboxRow, error) {
	rows, err := q.db.Query(ctx, claimLiveTelemetryOutbox, arg.RowLimit, arg.LeaseDuration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimLiveTelemetryOutboxRow
	for rows.Next() {
		var i ClaimLiveTelemetryOutboxRow
		if err := rows.Scan(
			&i.OutboxID,
			&i.StreamKind,
			&i.StreamKey,
			&i.Attempts,
			&i.Seq,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.SourceKind,
			&i.SourceID,
			&i.StreamName,
			&i.RunID,
			&i.DeploymentID,
			&i.RunLeaseID,
			&i.AttemptNumber,
			&i.TraceID,
			&i.SpanID,
			&i.ParentSpanID,
			&i.Traceparent,
			&i.Category,
			&i.Severity,
			&i.Source,
			&i.Kind,
			&i.Message,
			&i.Payload,
			&i.RedactionClass,
			&i.SnapshotVersion,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimRunLogIngestBatch = `-- name: ClaimRunLogIngestBatch :many
WITH candidates AS (
    SELECT telemetry_outbox.id,
           telemetry_outbox.size_bytes
      FROM telemetry_outbox
     WHERE telemetry_outbox.stream_kind = 'run_log'
       AND telemetry_outbox.written_at IS NULL
       AND telemetry_outbox.state IN ('pending', 'claimed', 'failed')
       AND (telemetry_outbox.next_retry_at IS NULL OR telemetry_outbox.next_retry_at <= now())
     ORDER BY telemetry_outbox.id ASC
     LIMIT $1
     FOR UPDATE SKIP LOCKED
),
claimed AS (
    SELECT sized.id
      FROM (
          SELECT candidates.id,
                 SUM(candidates.size_bytes) OVER (ORDER BY candidates.id ASC) AS cumulative_size_bytes
            FROM candidates
      ) AS sized
     WHERE sized.cumulative_size_bytes <= $2::bigint
),
updated AS (
    UPDATE telemetry_outbox
       SET state = 'claimed',
           retry_count = telemetry_outbox.retry_count + 1,
           next_retry_at = now() + $3::interval,
           updated_at = now()
      FROM claimed
     WHERE telemetry_outbox.id = claimed.id
    RETURNING telemetry_outbox.id, telemetry_outbox.org_id, telemetry_outbox.stream_kind, telemetry_outbox.source_kind, telemetry_outbox.source_id, telemetry_outbox.stream_name, telemetry_outbox.idempotency_key, telemetry_outbox.project_id, telemetry_outbox.environment_id, telemetry_outbox.run_id, telemetry_outbox.deployment_id, telemetry_outbox.run_lease_id, telemetry_outbox.attempt_number, telemetry_outbox.trace_id, telemetry_outbox.span_id, telemetry_outbox.parent_span_id, telemetry_outbox.traceparent, telemetry_outbox.category, telemetry_outbox.severity, telemetry_outbox.source, telemetry_outbox.kind, telemetry_outbox.message, telemetry_outbox.payload, telemetry_outbox.content, telemetry_outbox.size_bytes, telemetry_outbox.observed_seq, telemetry_outbox.redaction_class, telemetry_outbox.retention_class, telemetry_outbox.snapshot_version, telemetry_outbox.state, telemetry_outbox.retry_count, telemetry_outbox.next_retry_at, telemetry_outbox.written_at, telemetry_outbox.published_at, telemetry_outbox.publish_attempts, telemetry_outbox.publish_locked_until, telemetry_outbox.ingest_error, telemetry_outbox.publish_error, telemetry_outbox.observed_at, telemetry_outbox.created_at, telemetry_outbox.updated_at
)
SELECT updated.id AS outbox_id,
       updated.retry_count,
       COALESCE(updated.idempotency_key, '')::text AS idempotency_key,
       updated.org_id,
       updated.project_id,
       updated.environment_id,
       updated.run_id,
       updated.run_lease_id,
       updated.attempt_number,
       updated.stream_name AS stream,
       updated.id AS seq,
       updated.observed_seq,
       updated.content,
       updated.size_bytes,
       updated.created_at
  FROM updated
 ORDER BY updated.id ASC
`

type ClaimRunLogIngestBatchParams struct {
	RowLimit      int32           `json:"row_limit"`
	MaxBatchBytes int64           `json:"max_batch_bytes"`
	LeaseDuration pgtype.Interval `json:"lease_duration"`
}

type ClaimRunLogIngestBatchRow struct {
	OutboxID       int64              `json:"outbox_id"`
	RetryCount     int32              `json:"retry_count"`
	IdempotencyKey string             `json:"idempotency_key"`
	OrgID          pgtype.UUID        `json:"org_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	EnvironmentID  pgtype.UUID        `json:"environment_id"`
	RunID          pgtype.UUID        `json:"run_id"`
	RunLeaseID     pgtype.UUID        `json:"run_lease_id"`
	AttemptNumber  pgtype.Int4        `json:"attempt_number"`
	Stream         string             `json:"stream"`
	Seq            int64              `json:"seq"`
	ObservedSeq    pgtype.Int8        `json:"observed_seq"`
	Content        []byte             `json:"content"`
	SizeBytes      pgtype.Int8        `json:"size_bytes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ClaimRunLogIngestBatch(ctx context.Context, arg ClaimRunLogIngestBatchParams) ([]ClaimRunLogIngestBatchRow, error) {
	rows, err := q.db.Query(ctx, claimRunLogIngestBatch, arg.RowLimit, arg.MaxBatchBytes, arg.LeaseDuration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimRunLogIngestBatchRow
	for rows.Next() {
		var i ClaimRunLogIngestBatchRow
		if err := rows.Scan(
			&i.OutboxID,
			&i.RetryCount,
			&i.IdempotencyKey,
			&i.OrgID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.RunID,
			&i.RunLeaseID,
			&i.AttemptNumber,
			&i.Stream,
			&i.Seq,
			&i.ObservedSeq,
			&i.Content,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTelemetryOutboxLifecycle = `-- name: GetTelemetryOutboxLifecycle :one
SELECT LEAST(
           (SELECT created_at
              FROM telemetry_outbox
             WHERE stream_kind = 'event'
               AND written_at IS NULL
               AND state IN ('pending', 'claimed', 'failed')
               AND (next_retry_at IS NULL OR next_retry_at <= now())
             ORDER BY id ASC LIMIT 1),
           (SELECT created_at
              FROM telemetry_outbox
             WHERE stream_kind = 'run_log'
               AND written_at IS NULL
               AND state IN ('pending', 'claimed', 'failed')
               AND (next_retry_at IS NULL OR next_retry_at <= now())
             ORDER BY id ASC LIMIT 1)
       )::timestamptz AS oldest_retry_created_at,
       (SELECT written_at
          FROM telemetry_outbox
         WHERE written_at < now() - $1::interval
           AND ((stream_kind = 'event' AND published_at IS NOT NULL) OR stream_kind = 'run_log')
         ORDER BY written_at ASC, id ASC LIMIT 1) AS oldest_gc_written_at
`

type GetTelemetryOutboxLifecycleRow struct {
	OldestRetryCreatedAt pgtype.Timestamptz `json:"oldest_retry_created_at"`
	OldestGcWrittenAt    pgtype.Timestamptz `json:"oldest_gc_written_at"`
}

func (q *Queries) GetTelemetryOutboxLifecycle(ctx context.Context, retainFor pgtype.Interval) (GetTelemetryOutboxLifecycleRow, error) {
	row := q.db.QueryRow(ctx, getTelemetryOutboxLifecycle, retainFor)
	var i GetTelemetryOutboxLifecycleRow
	err := row.Scan(&i.OldestRetryCreatedAt, &i.OldestGcWrittenAt)
	return i, err
}

const markLiveTelemetryOutboxBatchFailed = `-- name: MarkLiveTelemetryOutboxBatchFailed :execrows
WITH failures AS (
    SELECT input_ids.id,
           input_attempts.publish_attempts,
           input_retries.retry_after,
           input_errors.publish_error
      FROM unnest($1::bigint[])
           WITH ORDINALITY AS input_ids(id, position)
      JOIN unnest($2::integer[])
           WITH ORDINALITY AS input_attempts(publish_attempts, position)
        ON input_attempts.position = input_ids.position
      JOIN unnest($3::interval[])
           WITH ORDINALITY AS input_retries(retry_after, position)
        ON input_retries.position = input_ids.position
      JOIN unnest($4::text[])
           WITH ORDINALITY AS input_errors(publish_error, position)
        ON input_errors.position = input_ids.position
)
UPDATE telemetry_outbox
   SET publish_locked_until = now() + failures.retry_after,
       updated_at = now(),
       publish_error = failures.publish_error
  FROM failures
 WHERE telemetry_outbox.id = failures.id
   AND telemetry_outbox.publish_attempts = failures.publish_attempts
   AND telemetry_outbox.published_at IS NULL
`

type MarkLiveTelemetryOutboxBatchFailedParams struct {
	Ids                     []int64           `json:"ids"`
	ExpectedPublishAttempts []int32           `json:"expected_publish_attempts"`
	RetryAfters             []pgtype.Interval `json:"retry_afters"`
	PublishErrors           []string          `json:"publish_errors"`
}

func (q *Queries) MarkLiveTelemetryOutboxBatchFailed(ctx context.Context, arg MarkLiveTelemetryOutboxBatchFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markLiveTelemetryOutboxBatchFailed,
		arg.Ids,
		arg.ExpectedPublishAttempts,
		arg.RetryAfters,
		arg.PublishErrors,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markLiveTelemetryOutboxBatchPublished = `-- name: MarkLiveTelemetryOutboxBatchPublished :execrows
WITH completions AS (
    SELECT input_ids.id,
           input_attempts.publish_attempts
      FROM unnest($1::bigint[])
           WITH ORDINALITY AS input_ids(id, position)
      JOIN unnest($2::integer[])
           WITH ORDINALITY AS input_attempts(publish_attempts, position)
        ON input_attempts.position = input_ids.position
)
UPDATE telemetry_outbox
   SET published_at = now(),
       publish_locked_until = NULL,
       updated_at = now(),
       publish_error = ''
  FROM completions
 WHERE telemetry_outbox.id = completions.id
   AND telemetry_outbox.publish_attempts = completions.publish_attempts
   AND telemetry_outbox.published_at IS NULL
`

type MarkLiveTelemetryOutboxBatchPublishedParams struct {
	Ids                     []int64 `json:"ids"`
	ExpectedPublishAttempts []int32 `json:"expected_publish_attempts"`
}

func (q *Queries) MarkLiveTelemetryOutboxBatchPublished(ctx context.Context, arg MarkLiveTelemetryOutboxBatchPublishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markLiveTelemetryOutboxBatchPublished, arg.Ids, arg.ExpectedPublishAttempts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markTelemetryOutboxBatchFailed = `-- name: MarkTelemetryOutboxBatchFailed :execrows
WITH failures AS (
    SELECT input_ids.id,
           input_retries.retry_count
      FROM unnest($3::bigint[])
           WITH ORDINALITY AS input_ids(id, position)
      JOIN unnest($4::integer[])
           WITH ORDINALITY AS input_retries(retry_count, position)
        ON input_retries.position = input_ids.position
)
UPDATE telemetry_outbox
   SET state = 'failed',
       next_retry_at = now() + $1::interval,
       updated_at = now(),
       ingest_error = $2
  FROM failures
 WHERE telemetry_outbox.id = failures.id
   AND telemetry_outbox.retry_count = failures.retry_count
   AND telemetry_outbox.written_at IS NULL
`

type MarkTelemetryOutboxBatchFailedParams struct {
	RetryAfter          pgtype.Interval `json:"retry_after"`
	IngestError         string          `json:"ingest_error"`
	Ids                 []int64         `json:"ids"`
	ExpectedRetryCounts []int32         `json:"expected_retry_counts"`
}

func (q *Queries) MarkTelemetryOutboxBatchFailed(ctx context.Context, arg MarkTelemetryOutboxBatchFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markTelemetryOutboxBatchFailed,
		arg.RetryAfter,
		arg.IngestError,
		arg.Ids,
		arg.ExpectedRetryCounts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markTelemetryOutboxWritten = `-- name: MarkTelemetryOutboxWritten :execrows
WITH completions AS (
    SELECT input_ids.id,
           input_retries.retry_count
      FROM unnest($1::bigint[])
           WITH ORDINALITY AS input_ids(id, position)
      JOIN unnest($2::integer[])
           WITH ORDINALITY AS input_retries(retry_count, position)
        ON input_retries.position = input_ids.position
)
UPDATE telemetry_outbox
   SET state = 'written',
       written_at = now(),
       retry_count = 0,
       next_retry_at = NULL,
       updated_at = now(),
       ingest_error = ''
  FROM completions
 WHERE telemetry_outbox.id = completions.id
   AND telemetry_outbox.retry_count = completions.retry_count
   AND telemetry_outbox.written_at IS NULL
`

type MarkTelemetryOutboxWrittenParams struct {
	Ids                 []int64 `json:"ids"`
	ExpectedRetryCounts []int32 `json:"expected_retry_counts"`
}

func (q *Queries) MarkTelemetryOutboxWritten(ctx context.Context, arg MarkTelemetryOutboxWrittenParams) (int64, error) {
	result, err := q.db.Exec(ctx, markTelemetryOutboxWritten, arg.Ids, arg.ExpectedRetryCounts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneTelemetryOutboxWritten = `-- name: PruneTelemetryOutboxWritten :execrows
WITH eligible AS (
    SELECT id
      FROM telemetry_outbox
     WHERE written_at < now() - $1::interval
       AND (
            (stream_kind = 'event' AND published_at IS NOT NULL)
            OR stream_kind = 'run_log'
       )
     ORDER BY written_at ASC, id ASC
     LIMIT $2
     FOR UPDATE SKIP LOCKED
)
DELETE FROM telemetry_outbox
 USING eligible
 WHERE telemetry_outbox.id = eligible.id
`

type PruneTelemetryOutboxWrittenParams struct {
	RetainFor pgtype.Interval `json:"retain_for"`
	RowLimit  int32           `json:"row_limit"`
}

func (q *Queries) PruneTelemetryOutboxWritten(ctx context.Context, arg PruneTelemetryOutboxWrittenParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneTelemetryOutboxWritten, arg.RetainFor, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
