// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: waitpoint_deliveries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWaitpointDelivery = `-- name: CreateWaitpointDelivery :one
INSERT INTO waitpoint_deliveries (
    id,
    org_id,
    run_id,
    waitpoint_id,
    response_token_id,
    channel,
    recipient_kind,
    recipient,
    status,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9::waitpoint_delivery_status,
    $10
)
RETURNING id, org_id, run_id, waitpoint_id, response_token_id, channel, recipient_kind, recipient, status, last_error, metadata, sent_at, created_at, updated_at
`

type CreateWaitpointDeliveryParams struct {
	ID              pgtype.UUID             `json:"id"`
	OrgID           pgtype.UUID             `json:"org_id"`
	RunID           pgtype.UUID             `json:"run_id"`
	WaitpointID     pgtype.UUID             `json:"waitpoint_id"`
	ResponseTokenID pgtype.UUID             `json:"response_token_id"`
	Channel         string                  `json:"channel"`
	RecipientKind   string                  `json:"recipient_kind"`
	Recipient       string                  `json:"recipient"`
	Status          WaitpointDeliveryStatus `json:"status"`
	Metadata        []byte                  `json:"metadata"`
}

func (q *Queries) CreateWaitpointDelivery(ctx context.Context, arg CreateWaitpointDeliveryParams) (WaitpointDelivery, error) {
	row := q.db.QueryRow(ctx, createWaitpointDelivery,
		arg.ID,
		arg.OrgID,
		arg.RunID,
		arg.WaitpointID,
		arg.ResponseTokenID,
		arg.Channel,
		arg.RecipientKind,
		arg.Recipient,
		arg.Status,
		arg.Metadata,
	)
	var i WaitpointDelivery
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RunID,
		&i.WaitpointID,
		&i.ResponseTokenID,
		&i.Channel,
		&i.RecipientKind,
		&i.Recipient,
		&i.Status,
		&i.LastError,
		&i.Metadata,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWaitpointDeliveries = `-- name: ListWaitpointDeliveries :many
SELECT id, org_id, run_id, waitpoint_id, response_token_id, channel, recipient_kind, recipient, status, last_error, metadata, sent_at, created_at, updated_at
  FROM waitpoint_deliveries
 WHERE org_id = $1
   AND run_id = $2
   AND waitpoint_id = $3
 ORDER BY created_at ASC
`

type ListWaitpointDeliveriesParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	RunID       pgtype.UUID `json:"run_id"`
	WaitpointID pgtype.UUID `json:"waitpoint_id"`
}

func (q *Queries) ListWaitpointDeliveries(ctx context.Context, arg ListWaitpointDeliveriesParams) ([]WaitpointDelivery, error) {
	rows, err := q.db.Query(ctx, listWaitpointDeliveries, arg.OrgID, arg.RunID, arg.WaitpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaitpointDelivery
	for rows.Next() {
		var i WaitpointDelivery
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RunID,
			&i.WaitpointID,
			&i.ResponseTokenID,
			&i.Channel,
			&i.RecipientKind,
			&i.Recipient,
			&i.Status,
			&i.LastError,
			&i.Metadata,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWaitpointDeliveryFailed = `-- name: MarkWaitpointDeliveryFailed :one
UPDATE waitpoint_deliveries
   SET status = 'failed',
       last_error = $1
 WHERE org_id = $2
   AND id = $3
RETURNING id, org_id, run_id, waitpoint_id, response_token_id, channel, recipient_kind, recipient, status, last_error, metadata, sent_at, created_at, updated_at
`

type MarkWaitpointDeliveryFailedParams struct {
	LastError pgtype.Text `json:"last_error"`
	OrgID     pgtype.UUID `json:"org_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) MarkWaitpointDeliveryFailed(ctx context.Context, arg MarkWaitpointDeliveryFailedParams) (WaitpointDelivery, error) {
	row := q.db.QueryRow(ctx, markWaitpointDeliveryFailed, arg.LastError, arg.OrgID, arg.ID)
	var i WaitpointDelivery
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RunID,
		&i.WaitpointID,
		&i.ResponseTokenID,
		&i.Channel,
		&i.RecipientKind,
		&i.Recipient,
		&i.Status,
		&i.LastError,
		&i.Metadata,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWaitpointDeliverySent = `-- name: MarkWaitpointDeliverySent :one
UPDATE waitpoint_deliveries
   SET status = 'sent',
       last_error = NULL,
       sent_at = now()
 WHERE org_id = $1
   AND id = $2
RETURNING id, org_id, run_id, waitpoint_id, response_token_id, channel, recipient_kind, recipient, status, last_error, metadata, sent_at, created_at, updated_at
`

type MarkWaitpointDeliverySentParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) MarkWaitpointDeliverySent(ctx context.Context, arg MarkWaitpointDeliverySentParams) (WaitpointDelivery, error) {
	row := q.db.QueryRow(ctx, markWaitpointDeliverySent, arg.OrgID, arg.ID)
	var i WaitpointDelivery
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RunID,
		&i.WaitpointID,
		&i.ResponseTokenID,
		&i.Channel,
		&i.RecipientKind,
		&i.Recipient,
		&i.Status,
		&i.LastError,
		&i.Metadata,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
