// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: waitpoint_responses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recordWaitpointResponse = `-- name: RecordWaitpointResponse :one
WITH target_waitpoint AS (
    SELECT id, org_id, project_id, environment_id, kind, request, display_text, status, output, resolution, output_is_error, resolution_kind, expires_at, idempotency_key, idempotency_request_hash, idempotency_key_expires_at, idempotency_key_options, created_at, completed_at, updated_at
      FROM waitpoints
     WHERE waitpoints.org_id = $1
       AND waitpoints.id = $2
       AND waitpoints.kind = $3
       AND waitpoints.status IN ('pending', 'completed')
       AND (waitpoints.expires_at IS NULL OR waitpoints.expires_at > now())
     FOR UPDATE
),
existing_response AS (
    SELECT waitpoint_responses.id, waitpoint_responses.org_id, waitpoint_responses.project_id, waitpoint_responses.environment_id, waitpoint_responses.waitpoint_id, waitpoint_responses.response_key, waitpoint_responses.request_hash, waitpoint_responses.action, waitpoint_responses.resolution_kind, waitpoint_responses.resolution, waitpoint_responses.event_payload, waitpoint_responses.completed_by_principal, waitpoint_responses.completed_via, waitpoint_responses.external_subject, waitpoint_responses.metadata, waitpoint_responses.created_at, waitpoint_responses.updated_at
      FROM waitpoint_responses
      JOIN target_waitpoint ON target_waitpoint.org_id = waitpoint_responses.org_id
                           AND target_waitpoint.id = waitpoint_responses.waitpoint_id
     WHERE waitpoint_responses.response_key = $4
     FOR UPDATE OF waitpoint_responses
),
inserted_response AS (
    INSERT INTO waitpoint_responses (
        id,
        org_id,
        project_id,
        environment_id,
        waitpoint_id,
        response_key,
        request_hash,
        action,
        resolution_kind,
        resolution,
        event_payload,
        completed_by_principal,
        completed_via,
        external_subject,
        metadata
    )
    SELECT
        $5,
        target_waitpoint.org_id,
        target_waitpoint.project_id,
        target_waitpoint.environment_id,
        target_waitpoint.id,
        $4,
        $6,
        $7,
        $8,
        $9,
        $10::jsonb,
        $11,
        $12,
        $13,
        $14::jsonb
      FROM target_waitpoint
     WHERE target_waitpoint.status = 'pending'
       AND NOT EXISTS (SELECT 1 FROM existing_response)
    RETURNING id, org_id, project_id, environment_id, waitpoint_id, response_key, request_hash, action, resolution_kind, resolution, event_payload, completed_by_principal, completed_via, external_subject, metadata, created_at, updated_at
),
matching_existing_response AS (
    SELECT existing_response.id, existing_response.org_id, existing_response.project_id, existing_response.environment_id, existing_response.waitpoint_id, existing_response.response_key, existing_response.request_hash, existing_response.action, existing_response.resolution_kind, existing_response.resolution, existing_response.event_payload, existing_response.completed_by_principal, existing_response.completed_via, existing_response.external_subject, existing_response.metadata, existing_response.created_at, existing_response.updated_at
      FROM existing_response
     WHERE existing_response.request_hash = $6
)
SELECT id, org_id, project_id, environment_id, waitpoint_id, response_key, request_hash, action, resolution_kind, resolution, event_payload, completed_by_principal, completed_via, external_subject, metadata, created_at, updated_at FROM inserted_response
UNION ALL
SELECT id, org_id, project_id, environment_id, waitpoint_id, response_key, request_hash, action, resolution_kind, resolution, event_payload, completed_by_principal, completed_via, external_subject, metadata, created_at, updated_at FROM matching_existing_response
LIMIT 1
`

type RecordWaitpointResponseParams struct {
	OrgID                pgtype.UUID   `json:"org_id"`
	WaitpointID          pgtype.UUID   `json:"waitpoint_id"`
	Kind                 WaitpointKind `json:"kind"`
	ResponseKey          string        `json:"response_key"`
	ID                   pgtype.UUID   `json:"id"`
	RequestHash          string        `json:"request_hash"`
	Action               string        `json:"action"`
	ResolutionKind       pgtype.Text   `json:"resolution_kind"`
	Resolution           []byte        `json:"resolution"`
	EventPayload         []byte        `json:"event_payload"`
	CompletedByPrincipal pgtype.Text   `json:"completed_by_principal"`
	CompletedVia         pgtype.Text   `json:"completed_via"`
	ExternalSubject      pgtype.Text   `json:"external_subject"`
	Metadata             []byte        `json:"metadata"`
}

type RecordWaitpointResponseRow struct {
	ID                   pgtype.UUID        `json:"id"`
	OrgID                pgtype.UUID        `json:"org_id"`
	ProjectID            pgtype.UUID        `json:"project_id"`
	EnvironmentID        pgtype.UUID        `json:"environment_id"`
	WaitpointID          pgtype.UUID        `json:"waitpoint_id"`
	ResponseKey          string             `json:"response_key"`
	RequestHash          string             `json:"request_hash"`
	Action               string             `json:"action"`
	ResolutionKind       pgtype.Text        `json:"resolution_kind"`
	Resolution           []byte             `json:"resolution"`
	EventPayload         []byte             `json:"event_payload"`
	CompletedByPrincipal pgtype.Text        `json:"completed_by_principal"`
	CompletedVia         pgtype.Text        `json:"completed_via"`
	ExternalSubject      pgtype.Text        `json:"external_subject"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) RecordWaitpointResponse(ctx context.Context, arg RecordWaitpointResponseParams) (RecordWaitpointResponseRow, error) {
	row := q.db.QueryRow(ctx, recordWaitpointResponse,
		arg.OrgID,
		arg.WaitpointID,
		arg.Kind,
		arg.ResponseKey,
		arg.ID,
		arg.RequestHash,
		arg.Action,
		arg.ResolutionKind,
		arg.Resolution,
		arg.EventPayload,
		arg.CompletedByPrincipal,
		arg.CompletedVia,
		arg.ExternalSubject,
		arg.Metadata,
	)
	var i RecordWaitpointResponseRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.WaitpointID,
		&i.ResponseKey,
		&i.RequestHash,
		&i.Action,
		&i.ResolutionKind,
		&i.Resolution,
		&i.EventPayload,
		&i.CompletedByPrincipal,
		&i.CompletedVia,
		&i.ExternalSubject,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
