// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worker_liveness.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listStaleWorkerFenceCandidates = `-- name: ListStaleWorkerFenceCandidates :many
SELECT workers.id,
       workers.worker_group_id,
       workers.current_epoch,
       workers.state,
       COALESCE(observations.observed_at, workers.epoch_started_at, workers.updated_at) AS freshness_at,
       CASE
           WHEN workers.state = 'registering' AND observations.worker_instance_id IS NULL
               THEN 'registering_observation_missing'
           ELSE 'worker_observation_stale'
       END::text AS reason
  FROM worker_instances AS workers
  LEFT JOIN worker_observations AS observations
    ON observations.worker_instance_id = workers.id
   AND observations.worker_epoch = workers.current_epoch
 WHERE workers.state IN ('registering', 'active', 'draining')
   AND ($1::text = '' OR workers.worker_group_id = $1::text)
   AND (
       (workers.state = 'registering'
        AND observations.worker_instance_id IS NULL
        AND COALESCE(workers.epoch_started_at, workers.updated_at)
            < $2)
       OR
       (workers.state IN ('active', 'draining')
        AND COALESCE(observations.observed_at, workers.epoch_started_at, workers.updated_at)
            < $3)
   )
 ORDER BY COALESCE(observations.observed_at, workers.epoch_started_at, workers.updated_at),
          workers.id
 LIMIT $4
 FOR UPDATE OF workers SKIP LOCKED
`

type ListStaleWorkerFenceCandidatesParams struct {
	WorkerGroupID           string             `json:"worker_group_id"`
	RegistrationStaleBefore pgtype.Timestamptz `json:"registration_stale_before"`
	ObservationStaleBefore  pgtype.Timestamptz `json:"observation_stale_before"`
	RowLimit                int32              `json:"row_limit"`
}

type ListStaleWorkerFenceCandidatesRow struct {
	ID            pgtype.UUID         `json:"id"`
	WorkerGroupID string              `json:"worker_group_id"`
	CurrentEpoch  pgtype.Int8         `json:"current_epoch"`
	State         WorkerInstanceState `json:"state"`
	FreshnessAt   pgtype.Timestamptz  `json:"freshness_at"`
	Reason        string              `json:"reason"`
}

func (q *Queries) ListStaleWorkerFenceCandidates(ctx context.Context, arg ListStaleWorkerFenceCandidatesParams) ([]ListStaleWorkerFenceCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listStaleWorkerFenceCandidates,
		arg.WorkerGroupID,
		arg.RegistrationStaleBefore,
		arg.ObservationStaleBefore,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleWorkerFenceCandidatesRow
	for rows.Next() {
		var i ListStaleWorkerFenceCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkerGroupID,
			&i.CurrentEpoch,
			&i.State,
			&i.FreshnessAt,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recheckAndFenceStaleWorkerInstance = `-- name: RecheckAndFenceStaleWorkerInstance :one
WITH target AS (
    UPDATE worker_instances AS workers
       SET state = CASE
               WHEN workers.current_epoch IS NULL THEN 'disabled'::worker_instance_state
               ELSE 'lost'::worker_instance_state
           END,
           claim_version = workers.claim_version + 1,
           disabled_at = CASE
               WHEN workers.current_epoch IS NULL THEN COALESCE(workers.disabled_at, now())
               ELSE workers.disabled_at
           END,
           lost_at = CASE
               WHEN workers.current_epoch IS NOT NULL THEN COALESCE(workers.lost_at, now())
               ELSE workers.lost_at
           END,
           updated_at = now()
     WHERE workers.id = $1
       AND workers.worker_group_id = $2
       AND workers.current_epoch IS NOT DISTINCT FROM $3
       AND workers.state IN ('registering', 'active', 'draining')
       AND (
           (workers.state = 'registering'
            AND NOT EXISTS (
                SELECT 1
                  FROM worker_observations AS observations
                 WHERE observations.worker_instance_id = workers.id
                   AND observations.worker_epoch = workers.current_epoch
            )
            AND COALESCE(workers.epoch_started_at, workers.updated_at)
                < $4)
           OR
           (workers.state IN ('active', 'draining')
            AND COALESCE(
                    (SELECT observations.observed_at
                       FROM worker_observations AS observations
                      WHERE observations.worker_instance_id = workers.id
                        AND observations.worker_epoch = workers.current_epoch),
                    workers.epoch_started_at,
                    workers.updated_at
                ) < $5)
       )
    RETURNING workers.id, workers.resource_id, workers.worker_group_id, workers.attestation_fingerprint, workers.state, workers.claim_version, workers.current_epoch, workers.current_service_id, workers.protocol_version, workers.supervisor_version, workers.supports_run, workers.supports_build, workers.runtime_identity_id, workers.certified_cpu_millis, workers.certified_memory_bytes, workers.certified_workload_disk_bytes, workers.certified_scratch_bytes, workers.certified_build_cache_bytes, workers.certified_artifact_cache_bytes, workers.certified_hugepages_bytes, workers.certified_checkpoint_bytes, workers.per_vm_cpu_millis, workers.per_vm_memory_bytes, workers.per_vm_workload_disk_bytes, workers.per_vm_scratch_bytes, workers.max_vm_slots, workers.max_run_consumers, workers.max_build_executors, workers.max_runtime_starts, workers.certification_profile, workers.certification_fingerprint, workers.epoch_started_at, workers.startup_inventory_epoch, workers.startup_inventory_evidence, workers.drain_cleanup_fingerprint, workers.drain_cleanup_evidence, workers.certified_at, workers.activated_at, workers.draining_at, workers.disabled_at, workers.lost_at, workers.termination_claimed_at, workers.provider_terminated_at, workers.created_at, workers.updated_at
), revoked_credentials AS (
    UPDATE worker_instance_credentials AS credentials
       SET revoked_at = COALESCE(credentials.revoked_at, now())
      FROM target
     WHERE credentials.worker_instance_id = target.id
       AND credentials.revoked_at IS NULL
    RETURNING credentials.id
), lost_mounts AS (
    UPDATE workspace_mounts AS mounts
       SET state = 'lost', lost_at = now(), terminal_at = now(),
           terminal_reason_code = $6, updated_at = now()
      FROM target
     WHERE mounts.worker_instance_id = target.id
       AND mounts.worker_epoch = target.current_epoch
       AND mounts.state IN ('mounting', 'mounted', 'unmounting')
    RETURNING mounts.id
), lost_runtimes AS (
    UPDATE runtime_instances AS runtimes
       SET observed_state = 'lost', observed_version = runtimes.observed_version + 1,
           observed_at = now(), lost_at = now(), terminal_at = now(),
           terminal_reason_code = $6, updated_at = now()
      FROM target
     WHERE runtimes.worker_instance_id = target.id
       AND runtimes.worker_epoch = target.current_epoch
       AND runtimes.reclaimed_at IS NULL
       AND runtimes.observed_state IN ('allocated', 'preparing', 'ready', 'closing')
    RETURNING runtimes.id
), lost_slots AS (
    UPDATE worker_network_slots AS slots
       SET state = 'lost', generation = slots.generation + 1,
           lost_at = now(), state_reason_code = $6, updated_at = now()
      FROM target
     WHERE slots.worker_instance_id = target.id
       AND slots.worker_epoch = target.current_epoch
       AND slots.state IN ('assigned', 'bound', 'reclaiming', 'quarantined')
    RETURNING slots.id
)
SELECT target.id, target.worker_group_id, target.current_epoch, target.state
  FROM target
 WHERE (SELECT count(*) FROM revoked_credentials) >= 0
   AND (SELECT count(*) FROM lost_mounts) >= 0
   AND (SELECT count(*) FROM lost_runtimes) >= 0
   AND (SELECT count(*) FROM lost_slots) >= 0
`

type RecheckAndFenceStaleWorkerInstanceParams struct {
	ID                      pgtype.UUID        `json:"id"`
	WorkerGroupID           string             `json:"worker_group_id"`
	ExpectedEpoch           pgtype.Int8        `json:"expected_epoch"`
	RegistrationStaleBefore pgtype.Timestamptz `json:"registration_stale_before"`
	ObservationStaleBefore  pgtype.Timestamptz `json:"observation_stale_before"`
	ReasonCode              pgtype.Text        `json:"reason_code"`
}

type RecheckAndFenceStaleWorkerInstanceRow struct {
	ID            pgtype.UUID         `json:"id"`
	WorkerGroupID string              `json:"worker_group_id"`
	CurrentEpoch  pgtype.Int8         `json:"current_epoch"`
	State         WorkerInstanceState `json:"state"`
}

// Immediate fencing revokes credentials and terminalizes mount/runtime/slot
// observations. Run/build/workspace authority is recovered by its canonical
// expiry and recovery loops; this transition does not imply zero authority.
func (q *Queries) RecheckAndFenceStaleWorkerInstance(ctx context.Context, arg RecheckAndFenceStaleWorkerInstanceParams) (RecheckAndFenceStaleWorkerInstanceRow, error) {
	row := q.db.QueryRow(ctx, recheckAndFenceStaleWorkerInstance,
		arg.ID,
		arg.WorkerGroupID,
		arg.ExpectedEpoch,
		arg.RegistrationStaleBefore,
		arg.ObservationStaleBefore,
		arg.ReasonCode,
	)
	var i RecheckAndFenceStaleWorkerInstanceRow
	err := row.Scan(
		&i.ID,
		&i.WorkerGroupID,
		&i.CurrentEpoch,
		&i.State,
	)
	return i, err
}
