// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worker_drain.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeWorkerDrain = `-- name: CompleteWorkerDrain :one
WITH target AS MATERIALIZED (
    SELECT worker_hosts.id, worker_hosts.resource_id, worker_hosts.worker_group_id, worker_hosts.worker_pool_id, worker_hosts.status, worker_hosts.claim_version, worker_hosts.current_epoch, worker_hosts.current_service_id, worker_hosts.vm_platform_id, worker_hosts.epoch_cpu_millis, worker_hosts.epoch_memory_bytes, worker_hosts.epoch_guest_ephemeral_disk_bytes, worker_hosts.per_vm_cpu_millis, worker_hosts.per_vm_memory_bytes, worker_hosts.per_vm_guest_ephemeral_disk_bytes, worker_hosts.max_vm_slots, worker_hosts.max_vm_starts, worker_hosts.cpu_environment, worker_hosts.cpu_environment_digest, worker_hosts.observed_at, worker_hosts.run_paused_reason, worker_hosts.vm_paused_reason, worker_hosts.epoch_started_at, worker_hosts.activated_at, worker_hosts.draining_at, worker_hosts.drain_reason, worker_hosts.termination_ready_at, worker_hosts.lost_at, worker_hosts.created_at, worker_hosts.updated_at
      FROM worker_hosts
      JOIN worker_groups ON worker_groups.id = worker_hosts.worker_group_id
     WHERE worker_hosts.id = $1
       AND worker_hosts.worker_group_id = $2
       AND worker_hosts.current_epoch = $3
       AND worker_hosts.status IN ('draining', 'termination_ready')
       AND worker_hosts.claim_version IN (
           $4::bigint,
           $4::bigint + 1
       )
       AND worker_groups.status IN ('active', 'paused', 'draining')
     FOR UPDATE OF worker_hosts
), eligible AS (
    SELECT drain_target.id
      FROM target AS drain_target
     WHERE drain_target.status = 'draining'
       AND drain_target.epoch_started_at IS NOT NULL
       AND EXISTS (
           SELECT 1 FROM worker_host_secrets
            WHERE worker_host_secrets.worker_host_id = drain_target.id
              AND worker_host_secrets.claim_version = drain_target.claim_version
              AND worker_host_secrets.revoked_at IS NULL
       )
       AND NOT EXISTS (
           SELECT 1 FROM computer_leases
            WHERE computer_leases.worker_host_id=drain_target.id AND computer_leases.fenced_at IS NULL
       )
       AND NOT EXISTS (
           SELECT 1 FROM computer_preparations
            WHERE computer_preparations.worker_host_id=drain_target.id AND computer_preparations.fenced_at IS NULL
       )
), completed AS (
    UPDATE worker_hosts
       SET status = 'termination_ready',
           claim_version = worker_hosts.claim_version + 1,
           termination_ready_at = now(),
           updated_at = now()
      FROM eligible
     WHERE worker_hosts.id = eligible.id
    RETURNING worker_hosts.id, worker_hosts.worker_group_id,
              worker_hosts.current_epoch, worker_hosts.status,
              worker_hosts.claim_version, worker_hosts.termination_ready_at
), revoked AS (
    UPDATE worker_host_secrets
       SET revoked_at = now()
      FROM completed
     WHERE worker_host_secrets.worker_host_id = completed.id
       AND worker_host_secrets.revoked_at IS NULL
    RETURNING worker_host_secrets.id
), result AS (
    SELECT completed.id, completed.worker_group_id, completed.current_epoch, completed.status, completed.claim_version, completed.termination_ready_at
      FROM completed
     WHERE (SELECT count(*) FROM revoked) = 1
    UNION ALL
    SELECT target.id, target.worker_group_id, target.current_epoch, target.status,
           target.claim_version, target.termination_ready_at
      FROM target
     WHERE target.status = 'termination_ready'
       AND target.claim_version = $4 + 1
       AND target.termination_ready_at IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM completed)
)
SELECT id, worker_group_id, current_epoch, status, claim_version, termination_ready_at FROM result
`

type CompleteWorkerDrainParams struct {
	WorkerHostID         pgtype.UUID `json:"worker_host_id"`
	WorkerGroupID        pgtype.UUID `json:"worker_group_id"`
	WorkerEpoch          pgtype.Int8 `json:"worker_epoch"`
	ExpectedClaimVersion int64       `json:"expected_claim_version"`
}

type CompleteWorkerDrainRow struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkerGroupID      pgtype.UUID        `json:"worker_group_id"`
	CurrentEpoch       pgtype.Int8        `json:"current_epoch"`
	Status             string             `json:"status"`
	ClaimVersion       int64              `json:"claim_version"`
	TerminationReadyAt pgtype.Timestamptz `json:"termination_ready_at"`
}

func (q *Queries) CompleteWorkerDrain(ctx context.Context, arg CompleteWorkerDrainParams) (CompleteWorkerDrainRow, error) {
	row := q.db.QueryRow(ctx, completeWorkerDrain,
		arg.WorkerHostID,
		arg.WorkerGroupID,
		arg.WorkerEpoch,
		arg.ExpectedClaimVersion,
	)
	var i CompleteWorkerDrainRow
	err := row.Scan(
		&i.ID,
		&i.WorkerGroupID,
		&i.CurrentEpoch,
		&i.Status,
		&i.ClaimVersion,
		&i.TerminationReadyAt,
	)
	return i, err
}

const lockWorkerDrainCompletion = `-- name: LockWorkerDrainCompletion :one
SELECT worker_hosts.id, worker_hosts.status, worker_hosts.claim_version,
       worker_hosts.current_epoch, worker_hosts.termination_ready_at
  FROM worker_hosts
  JOIN worker_groups ON worker_groups.id = worker_hosts.worker_group_id
 WHERE worker_hosts.id = $1
   AND worker_hosts.worker_group_id = $2
   AND worker_hosts.current_epoch = $3
   AND worker_hosts.status IN ('draining', 'termination_ready')
   AND worker_groups.status IN ('active', 'paused', 'draining')
 FOR UPDATE OF worker_hosts
`

type LockWorkerDrainCompletionParams struct {
	WorkerHostID  pgtype.UUID `json:"worker_host_id"`
	WorkerGroupID pgtype.UUID `json:"worker_group_id"`
	WorkerEpoch   pgtype.Int8 `json:"worker_epoch"`
}

type LockWorkerDrainCompletionRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Status             string             `json:"status"`
	ClaimVersion       int64              `json:"claim_version"`
	CurrentEpoch       pgtype.Int8        `json:"current_epoch"`
	TerminationReadyAt pgtype.Timestamptz `json:"termination_ready_at"`
}

func (q *Queries) LockWorkerDrainCompletion(ctx context.Context, arg LockWorkerDrainCompletionParams) (LockWorkerDrainCompletionRow, error) {
	row := q.db.QueryRow(ctx, lockWorkerDrainCompletion, arg.WorkerHostID, arg.WorkerGroupID, arg.WorkerEpoch)
	var i LockWorkerDrainCompletionRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ClaimVersion,
		&i.CurrentEpoch,
		&i.TerminationReadyAt,
	)
	return i, err
}
