// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_stream_wakeups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimWorkspaceStreamWakeups = `-- name: ClaimWorkspaceStreamWakeups :many
WITH claimable AS (
    SELECT id
      FROM workspace_stream_wakeups
     WHERE attempts < $1::int
       AND (locked_until IS NULL OR locked_until < now())
     ORDER BY id ASC
     LIMIT $2
     FOR UPDATE SKIP LOCKED
),
updated AS (
    UPDATE workspace_stream_wakeups
       SET locked_until = now() + $3::interval,
           attempts = workspace_stream_wakeups.attempts + 1
      FROM claimable
     WHERE workspace_stream_wakeups.id = claimable.id
    RETURNING workspace_stream_wakeups.id, workspace_stream_wakeups.org_id, workspace_stream_wakeups.worker_group_id, workspace_stream_wakeups.project_id, workspace_stream_wakeups.environment_id, workspace_stream_wakeups.workspace_id, workspace_stream_wakeups.resource_kind, workspace_stream_wakeups.resource_id, workspace_stream_wakeups.stream, workspace_stream_wakeups.cursor_offset, workspace_stream_wakeups.notification_kind, workspace_stream_wakeups.attempts, workspace_stream_wakeups.locked_until, workspace_stream_wakeups.last_error, workspace_stream_wakeups.created_at
)
SELECT id, org_id, worker_group_id, project_id, environment_id, workspace_id, resource_kind, resource_id, stream, cursor_offset, notification_kind, attempts, locked_until, last_error, created_at
  FROM updated
 ORDER BY id ASC
`

type ClaimWorkspaceStreamWakeupsParams struct {
	MaxAttempts   int32           `json:"max_attempts"`
	RowLimit      int32           `json:"row_limit"`
	LeaseDuration pgtype.Interval `json:"lease_duration"`
}

type ClaimWorkspaceStreamWakeupsRow struct {
	ID               int64                           `json:"id"`
	OrgID            pgtype.UUID                     `json:"org_id"`
	WorkerGroupID    string                          `json:"worker_group_id"`
	ProjectID        pgtype.UUID                     `json:"project_id"`
	EnvironmentID    pgtype.UUID                     `json:"environment_id"`
	WorkspaceID      pgtype.UUID                     `json:"workspace_id"`
	ResourceKind     WorkspaceResourceKind           `json:"resource_kind"`
	ResourceID       pgtype.UUID                     `json:"resource_id"`
	Stream           string                          `json:"stream"`
	CursorOffset     int64                           `json:"cursor_offset"`
	NotificationKind WorkspaceStreamNotificationKind `json:"notification_kind"`
	Attempts         int32                           `json:"attempts"`
	LockedUntil      pgtype.Timestamptz              `json:"locked_until"`
	LastError        string                          `json:"last_error"`
	CreatedAt        pgtype.Timestamptz              `json:"created_at"`
}

func (q *Queries) ClaimWorkspaceStreamWakeups(ctx context.Context, arg ClaimWorkspaceStreamWakeupsParams) ([]ClaimWorkspaceStreamWakeupsRow, error) {
	rows, err := q.db.Query(ctx, claimWorkspaceStreamWakeups, arg.MaxAttempts, arg.RowLimit, arg.LeaseDuration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimWorkspaceStreamWakeupsRow
	for rows.Next() {
		var i ClaimWorkspaceStreamWakeupsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.WorkerGroupID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.WorkspaceID,
			&i.ResourceKind,
			&i.ResourceID,
			&i.Stream,
			&i.CursorOffset,
			&i.NotificationKind,
			&i.Attempts,
			&i.LockedUntil,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createWorkspaceStreamWakeup = `-- name: CreateWorkspaceStreamWakeup :one
INSERT INTO workspace_stream_wakeups (
    org_id,
    project_id,
    environment_id,
    workspace_id,
    resource_kind,
    resource_id,
    stream,
    cursor_offset,
    notification_kind
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5::workspace_resource_kind,
    $6,
    $7,
    $8,
    $9::workspace_stream_notification_kind
)
RETURNING id, org_id, worker_group_id, project_id, environment_id, workspace_id, resource_kind, resource_id, stream, cursor_offset, notification_kind, attempts, locked_until, last_error, created_at
`

type CreateWorkspaceStreamWakeupParams struct {
	OrgID            pgtype.UUID                     `json:"org_id"`
	ProjectID        pgtype.UUID                     `json:"project_id"`
	EnvironmentID    pgtype.UUID                     `json:"environment_id"`
	WorkspaceID      pgtype.UUID                     `json:"workspace_id"`
	ResourceKind     WorkspaceResourceKind           `json:"resource_kind"`
	ResourceID       pgtype.UUID                     `json:"resource_id"`
	Stream           string                          `json:"stream"`
	CursorOffset     int64                           `json:"cursor_offset"`
	NotificationKind WorkspaceStreamNotificationKind `json:"notification_kind"`
}

func (q *Queries) CreateWorkspaceStreamWakeup(ctx context.Context, arg CreateWorkspaceStreamWakeupParams) (WorkspaceStreamWakeup, error) {
	row := q.db.QueryRow(ctx, createWorkspaceStreamWakeup,
		arg.OrgID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.WorkspaceID,
		arg.ResourceKind,
		arg.ResourceID,
		arg.Stream,
		arg.CursorOffset,
		arg.NotificationKind,
	)
	var i WorkspaceStreamWakeup
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkerGroupID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.WorkspaceID,
		&i.ResourceKind,
		&i.ResourceID,
		&i.Stream,
		&i.CursorOffset,
		&i.NotificationKind,
		&i.Attempts,
		&i.LockedUntil,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkspaceStreamWakeup = `-- name: DeleteWorkspaceStreamWakeup :exec
DELETE FROM workspace_stream_wakeups
 WHERE id = $1
`

func (q *Queries) DeleteWorkspaceStreamWakeup(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceStreamWakeup, id)
	return err
}

const markWorkspaceStreamWakeupFailed = `-- name: MarkWorkspaceStreamWakeupFailed :exec
WITH deleted_exhausted_chunk AS (
    DELETE FROM workspace_stream_wakeups
     WHERE id = $4
       AND attempts >= $1::int
       AND notification_kind <> 'terminal'
    RETURNING id
)
UPDATE workspace_stream_wakeups
   SET attempts = CASE
           WHEN attempts >= $1::int THEN $1::int - 1
           ELSE attempts
       END,
       locked_until = now() + $2::interval,
       last_error = $3
 WHERE workspace_stream_wakeups.id = $4
   AND NOT EXISTS (SELECT 1 FROM deleted_exhausted_chunk)
`

type MarkWorkspaceStreamWakeupFailedParams struct {
	MaxAttempts int32           `json:"max_attempts"`
	RetryAfter  pgtype.Interval `json:"retry_after"`
	LastError   string          `json:"last_error"`
	ID          int64           `json:"id"`
}

func (q *Queries) MarkWorkspaceStreamWakeupFailed(ctx context.Context, arg MarkWorkspaceStreamWakeupFailedParams) error {
	_, err := q.db.Exec(ctx, markWorkspaceStreamWakeupFailed,
		arg.MaxAttempts,
		arg.RetryAfter,
		arg.LastError,
		arg.ID,
	)
	return err
}
